### ISSUE TITLE
plainanalyzer xref writer can never end for a file with long lines (Bugzilla #13362)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#108]
status CLOSED severity _major_ in component _analyzer_ for _0.9_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Knut Anders Hatlen

Original attachment names and IDs:
- _inv_msg_ (ID 3225)

On 2009-12-15 10:12:12 +0000, Lubos Kosco wrote:

> happened with 0.8.1
> 
> create a file with a long line containing mix of letters and numbers without any spaces
> 
> create several such files in different projects
> 
> then your indexer will be stuck on
> http://src.opensolaris.org/source/xref/opengrok/trunk/src/org/opensolaris/opengrok/analysis/plain/PlainXref.lex# 45
> 
> hence we need to refactor this method
> 
> I am not sure if the method is not thread safe , or the EOF symbol recognition is broken, will try to do deadlock detect and update this bug ...

On 2009-12-15 10:12:59 +0000, Lubos Kosco wrote:

> Created attachment 3225
> a sample file that breaks plain analyzer

On 2009-12-15 10:46:57 +0000, Lubos Kosco wrote:

> all analyzer threads are stuck with:
> "pool-2-thread-6" prio=3 tid=0x003e2400 nid=0x32 runnable [0x7647e000]
>    java.lang.Thread.State: RUNNABLE
>         at org.opensolaris.opengrok.analysis.plain.PlainXref.yylex(PlainXref.java:612)
>         at org.opensolaris.opengrok.analysis.plain.PlainXref.write(PlainXref.java:272)
>         at org.opensolaris.opengrok.analysis.plain.PlainAnalyzer.writeXref(PlainAnalyzer.java:119)
>         at org.opensolaris.opengrok.analysis.FileAnalyzer.writeXref(FileAnalyzer.java:143)
>         at org.opensolaris.opengrok.index.IndexDatabase.addFile(IndexDatabase.java:581)
>         at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:690)
>         at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:673)
>         at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:673)
>         at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:673)
>         at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:327)
>         at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:142)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
>         at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
>         at java.util.concurrent.FutureTask.run(Unknown Source)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>         at java.lang.Thread.run(Unknown Source)
> 
>    Locked ownable synchronizers:
>         - <0x7befbe98> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
> 
> I have a bad feeling JFlexXref is not thread safe, the indexer runs on 2 sparc CPUs , there seem to be 6 threads
> and last log on screen I have that all the threads started indexing the same file (attached)

On 2009-12-15 20:44:29 +0000, Knut Anders Hatlen wrote:

> Do they "never" end, or do they just take a very long time to complete? I may have seen similar issues with some of the files in Apache Derby's test suite containing ~40k characters on a single line (which is much smaller than the file you uploaded). Then the indexer seems to be stuck for minutes, but eventually completes successfully. If it's the same problem, I don't think it's a thread-safety issue, as I also see it when running single-threaded.

On 2009-12-17 06:15:12 +0000, Lubos Kosco wrote:

> I am not sure if they ever complete
> I let them index the files for more than one hour
> all threads were "stuck" on attached file still ... :(
> 
> all were doing the reading function yylex as you can see in stack
> 
> it should be easy to reproduce by creating several projects, that just contain attached file and start indexer ...

On 2009-12-17 19:45:23 +0000, Knut Anders Hatlen wrote:

> Indexing the attached file took 1 hour 54 minutes on my machine.

On 2009-12-17 20:50:05 +0000, Lubos Kosco wrote:

> :) but it's still a bug imho ...
> 2 hours for a single 900k file ? 
> there is something wrong there ... I think we still need to improve the analyzer ;)

On 2009-12-17 22:43:49 +0000, Knut Anders Hatlen wrote:

> I guess I'm more patient than you... :P
> 
> Yes, sure it's a bug!

On 2009-12-20 19:08:42 +0000, Knut Anders Hatlen wrote:

> PlainXref.lex has a number of patterns that start with {FNameChar}+. The generated parser will read the entire line before it sees that it cannot match the rest of the pattern. It then ends up matching it with the . rule, which consumes one character. Then it continues on the second character on the line, again reads the entire line, gives up, and finds a match with the . rule. And so on, and so on...
> 
> Adding a rule {FNameChar}+ that just copies the matched region to the output file makes the parsing go much faster because it avoids much of the needless backtracking. (This won't interfere with the rules whose patterns begin with {FNameChar}+, since JFlex will always pick the longest match.)
> 
> Fixed in changeset 923:57d2aa303158.
> 
> Lubos, is one second acceptable? :)

On 2009-12-21 07:31:54 +0000, Lubos Kosco wrote:

> :)
> 
> thank you very much kah, now this is what I call a great christmas gift ... going from 2 hours of analyzing to 1s :-D

**Comment by vladak** [comment]
Adding the attachment from @tarzanek's archive I still happen to have.
[3225.txt](https://github.com/oracle/opengrok/files/6078702/3225.txt)
