### ISSUE TITLE
Invalid date format may skip history generation

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#1483]
If any commit in the repository contains invalid date format it may skip the whole history creation. The expected behaviour should be that something like that the commit will not have the date - but will exists as well as the file.

It may skip the whole history because the initial history is done from the `git log` in the repository root which contains every commit.

This should not happen so often however there are some cases where it was observed:

```log
SEVERE: Failed to read from process: git
java.io.IOException: Failed to parse author date: AuthorDate: Thu, 8 Sep 2011 02:38:50 +51800
        at org.opensolaris.opengrok.history.GitHistoryParser.process(GitHistoryParser.java:102)
        at org.opensolaris.opengrok.history.GitHistoryParser.processStream(GitHistoryParser.java:68)
        at org.opensolaris.opengrok.util.Executor.exec(Executor.java:213)
        at org.opensolaris.opengrok.history.GitHistoryParser.parse(GitHistoryParser.java:161)
        at org.opensolaris.opengrok.history.GitRepository.getHistory(GitRepository.java:513)
        at org.opensolaris.opengrok.history.Repository.createCache(Repository.java:310)
        at org.opensolaris.opengrok.history.HistoryGuru.createCache(HistoryGuru.java:511)
        at org.opensolaris.opengrok.history.HistoryGuru.access$000(HistoryGuru.java:56)
        at org.opensolaris.opengrok.history.HistoryGuru$1.run(HistoryGuru.java:562)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.text.ParseException: Unparseable date: "Thu, 8 Sep 2011 02:38:50 +51800" with format "EE, d MMM yyyy HH:mm:ss Z" and locale "en_US"
        at org.opensolaris.opengrok.history.Repository$1.parse(Repository.java:434)
        at org.opensolaris.opengrok.history.GitHistoryParser.process(GitHistoryParser.java:96)
        ... 13 more
Caused by: java.text.ParseException: Unparseable date: "Thu, 8 Sep 2011 02:38:50 +51800" with format "d MMM yyyy HH:mm:ss Z" and locale "en_US"
        ... 15 more
```

**Comment by vladak** [comment]
While this is a generic problem (tracked elsewhere), this particular will be eventually fixed with #1113.
