### ISSUE TITLE
per-directory history fails for some directories

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2019]
When trying to display per-directory history (Mercurial) in 1.1-rc21 this fails for some directories with:

```
15-Feb-2018 14:03:36.301 FINE [http-nio-8888-exec-125] org.opensolaris.opengrok.util.Executor.exec Executing command [/usr/bin/hg, log, -r, reverse(0::'server'), --template, changeset: {rev}:{node|short}\nuser: {author}\ndate: {date|isodate}\ndescription: {desc|strip|obfuscate}\nfiles: {files}\nmercurial_history_end_of_entry\n, usr/src/tools] in directory /ws-local/on-server
15-Feb-2018 14:03:37.022 SEVERE [Thread-424765] org.opensolaris.opengrok.util.Executor$1.run Error during process pipe listening
 java.io.IOException: Stream Closed
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:233)
	at java.lang.UNIXProcess$DeferredCloseInputStream.read(UNIXProcess.java:647)
	at org.opensolaris.opengrok.util.Executor$SpoolHandler.processStream(Executor.java:363)
	at org.opensolaris.opengrok.util.Executor$1.run(Executor.java:183)
	at java.lang.Thread.run(Thread.java:748)
```

With dtrace's `execsnoop` script I see that the `hg log` command is being run and in fact when running it by hand it produces the expected output.

**Comment by vladak** [comment]
This does not fail for the top level directory, most likely because its history is cached. For some of its sub-directories it fails, for some it does not.
