### ISSUE TITLE
compatibility versions of JDK and Tomcat for  opengrok-1.1-rc26

### ISSUE THREAD

**Issue by sreehari83** [oracle/opengrok#2127]
Please let me know the exact compatibility versions of JDK and Tomcat for  opengrok-1.1-rc26

am trying to deploy the war from opengrok-1.1-rc26.tar.gz on my server.

my server details:
 Operating System: CentOS 6.8 x86_6
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)
 apache-tomcat-8.0.36 
 apr-util-1.4.1    
 db-5.3.21 
 openldap-2.4.32  
apache-2.2.23 
 apr-1.4.6             
CollabNet_Subversion  
ctags-5.8  

Following is the error:
===========================
SEVERE: ContainerBase.addChild: start:
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/source]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: javax.servlet.ServletContext.getClassLoader()Ljava/lang/ClassLoader;
        at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:230)
        at org.apache.catalina.startup.ContextConfig.processJarsForWebFragments(ContextConfig.java:1887)
        at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1127)
        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:779)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:306)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:95)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5202)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        ... 10 more

May 28, 2018 1:22:46 AM org.apache.catalina.startup.HostConfig deployWAR
SEVERE: Error deploying web application archive /opt/tomcat-instances/opengrok-1.1-rc26/webapps/source.war
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/source]]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:729)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

May 28, 2018 1:22:46 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /opt/tomcat-instances/opengrok-1.1-rc26/webapps/source.war has finished in 250 ms

**Comment by Orviss** [comment]
Hello,

demo is running on Tomcat 8.5.14 and Java 1.8.0_121 without problems. Also, Java 10 worked.

Hth,
Adam

**Comment by vladak** [comment]
Out of the exception stack trace the following sticks out:

```
Caused by: java.lang.NoSuchMethodError: javax.servlet.ServletContext.getClassLoader()
```

I thought `javax.servlet` is provided by Tomcat itself.

**Comment by sreehari83** [comment]
I can able to deploy war file from  opengrok-0.13-rc1.tar.gz but not from opengrok-1.1-rc26.tar.gz
but requirements for both versions are same java 1.8 and tomcat 8

Please let me know what is the problem with  opengrok-1.1-rc26.tar.gz

**Comment by Orviss** [comment]
According to this <http://tomcat.apache.org/whichversion.html> there is no difference in supported servlet spec. version between `8.0` and `8.5`. Also `getClassLoader` was added in `3.0` <https://docs.oracle.com/javaee/6/api/javax/servlet/ServletContext.html#getClassLoader()> . However, we have a dependency to `2.5` so we cannot call it explicitly.

**Comment by sreehari83** [comment]
am still facing same problem with war file form  opengrok-1.1-rc26.tar.gz
JAVA  version "1.8.0_121" and tomcat-8.5.14
/WEB-INF/lib:
servlet-api-2.5.jar
opengrok-1.1-rc26.jar

please help me out as how to resolve this issue.

SEVERE: ContainerBase.addChild: start:
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/source]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: javax.servlet.ServletContext.getClassLoader()Ljava/lang/ClassLoader;
        at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:241)
        at org.apache.catalina.startup.ContextConfig.processJarsForWebFragments(ContextConfig.java:1898)
        at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1126)
        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:775)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5105)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 10 more

May 29, 2018 2:18:26 AM org.apache.catalina.startup.HostConfig deployWAR
SEVERE: Error deploying web application archive /opt/tomcat-instances/opengrok-1.1-rc26/webapps/source.war
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/source]]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:756)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by vladak** [comment]
Checking the `web.xml` shipped with 1.1-rc26, it starts with:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app version="2.5" xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd">
```

so theoretically this should tell to the container server that Servlet 2.5 is required.

Looking at the source code of Tomcat 8.5, java/org/apache/tomcat/util/scan/StandardJarScanner.java contains this code:

```java
234      protected void doScanClassPath(JarScanType scanType, ServletContext context,
235              JarScannerCallback callback, Set<URL> processedURLs) {
236          if (log.isTraceEnabled()) {
237              log.trace(sm.getString("jarScan.classloaderStart"));
238          }
239  
240          ClassLoader stopLoader = null;
241          if (!isScanBootstrapClassPath()) {
242              // Stop when we reach the bootstrap class loader
243              stopLoader = ClassLoader.getSystemClassLoader().getParent();
244          }
245  
246          ClassLoader classLoader = context.getClassLoader();
```

which is called at the very end of scan(). Given it does not check Servlet version I guess it takes Servlet 3.0 as a minimal supported version ?

Anyhow, it is strange that elsewhere with Tomcat 8.5.28 and Java 1.8.0_172-b11 it works fine.

**Comment by vladak** [comment]
I guess once #2089 is fixed this will cease being a problem.

**Comment by vladak** [comment]
Hence, closing as a dup.

**Comment by vladak** [comment]
Soon. @Orviss will give it a try on the demo instance first.

Dne út 29. 5. 2018 19:37 uživatel sreehari83 <notifications@github.com>
napsal:

**Comment by Orviss** [comment]
It is already up :) <http://demo.opengrok.org>

**Comment by idodeclare** [comment]
@sreehari83, @vladak pushed an rc27 release today.
