### ISSUE TITLE
ERROR: java.lang.NoSuchMethodException: <unbound>=Project.setDescription

### ISSUE THREAD

**Issue by sreehari83** [oracle/opengrok#2136]
Following index command is giving the error :
Please let me know how to solve it

java 
====
java version "1.8.0_121"
tomcat apache-tomcat-8.5.14
command:
=============
 /usr/java/default/bin/java \
> -server -Xms8048m -Xmx16096m \
> -Dorg.opensolaris.opengrok.history.Subversion=/opt/CollabNet_Subversion/bin/svn \
> -Dorg.opensolaris.opengrok.history.cvs=/usr/bin/cvs \
> -Djava.util.logging.config.file=/vol/opengrok_scm/logging.properties.parallel \
> -jar /opt/tomcat-instances/opengrok-1.1-rc27/lib/opengrok.jar \
> -O on \
> -T 24 \
> -R /vol/opengrok_scm/conf_parallel/dcp.xml \
> -S
ERROR: java.lang.NoSuchMethodException: <unbound>=Project.setDescription("dcp");

/vol/opengrok_scm/conf_parallel/dcp.xml 
================================
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE java [
<!ELEMENT boolean ( #PCDATA ) >

<!ELEMENT java ( object ) >
<!ATTLIST java class NMTOKEN #REQUIRED >
<!ATTLIST java version NMTOKEN #REQUIRED >

<!ELEMENT object ( void+ ) >
<!ATTLIST object class ( org.opensolaris.opengrok.configuration.Configuration | org.opensolaris.opengrok.configuration.Project | org.opensolaris.opengrok.history.RepositoryInfo ) #REQUIRED >
<!ATTLIST object id NMTOKEN #IMPLIED >

<!ELEMENT string ( #PCDATA ) >

<!ELEMENT void ( boolean | object | string | void )* >
<!ATTLIST void method ( add ) #IMPLIED >
<!ATTLIST void property NMTOKEN #IMPLIED >
]>

<java version="1.8.0_121" class="java.beans.XMLDecoder">

 <object class="org.opensolaris.opengrok.configuration.Configuration">
  
  <void property="allowLeadingWildcard">
   <boolean>true</boolean>
  </void>

  
  <void property="ctags">
   <string>/opt/ctags/bin/ctags</string>
  </void>

  
  <void property="dataRoot">
   <string>/vol/opengrok_scm/index_data_parallel</string>
  </void>

  

  
  <void property="ignoredNames">
   <void property="items">
    <void method="add">
     <string>*.bz2</string>
    </void>
    <void method="add">
     <string>*.srecord</string>
    </void>
    <void method="add">
     <string>*.zip</string>
    </void>
    <void method="add">
     <string>*.jar</string>
    </void>
    <void method="add">
     <string>*.tar</string>
    </void>
   </void>
  </void>

  <void property="projects">

   <void method="add">
    <object class="org.opensolaris.opengrok.configuration.Project">
     <void property="description">
      <string>dcp</string>
     </void>
     <void property="path">
      <string>/dcp</string>
     </void>
    </object>
   </void>

  </void>

  
  <void property="repositories">

   <void method="add">
    <object class="org.opensolaris.opengrok.history.RepositoryInfo">
     <void property="datePattern">
      <string>yyyy-MM-dd'T'HH:mm:ss.SSS'Z'</string>
     </void>
     <void property="directoryName">
      <string>/vol/opengrok_scm/source_data_parallel/dcp</string>
     </void>
     <void property="type">
      <string>Subversion</string>
     </void>
     <void property="working">
      <boolean>true</boolean>
     </void>
    </object>
   </void>

   </void>

  
  <void property="sourceRoot">
   <string>/vol/opengrok_scm/source_data_parallel</string>
  </void>
 </object>
</java>

Even am getting same error with web deployment 
========================================
May 30, 2018 8:56:12 PM org.opensolaris.opengrok.web.WebappListener contextInitialized
WARNING: Configuration error. Failed to read config file:
java.io.IOException: java.lang.NoSuchMethodException: <unbound>=Project.setDescription("DEV_BRANCH");
        at org.opensolaris.opengrok.configuration.Configuration.decodeObject(Configuration.java:1379)
        at org.opensolaris.opengrok.configuration.Configuration.read(Configuration.java:1344)
        at org.opensolaris.opengrok.configuration.RuntimeEnvironment.readConfiguration(RuntimeEnvironment.java:1385)
        at org.opensolaris.opengrok.web.WebappListener.contextInitialized(WebappListener.java:72)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodException: <unbound>=Project.setDescription("DEV_BRANCH");
        at java.beans.Statement.invokeInternal(Statement.java:313)
        at java.beans.Statement.access$000(Statement.java:58)
        at java.beans.Statement$2.run(Statement.java:185)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.beans.Statement.invoke(Statement.java:182)
        at java.beans.Expression.getValue(Expression.java:155)
        at com.sun.beans.decoder.ObjectElementHandler.getValueObject(ObjectElementHandler.java:166)
        at com.sun.beans.decoder.NewElementHandler.getValueObject(NewElementHandler.java:123)
        at com.sun.beans.decoder.ElementHandler.endElement(ElementHandler.java:169)
        at com.sun.beans.decoder.DocumentHandler.endElement(DocumentHandler.java:318)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
        at com.sun.beans.decoder.DocumentHandler$1.run(DocumentHandler.java:375)
        at com.sun.beans.decoder.DocumentHandler$1.run(DocumentHandler.java:372)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at com.sun.beans.decoder.DocumentHandler.parse(DocumentHandler.java:372)
        at java.beans.XMLDecoder$1.run(XMLDecoder.java:201)
        at java.beans.XMLDecoder$1.run(XMLDecoder.java:199)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.beans.XMLDecoder.parsingComplete(XMLDecoder.java:199)
        at java.beans.XMLDecoder.readObject(XMLDecoder.java:250)
        at org.opensolaris.opengrok.configuration.Configuration.decodeObject(Configuration.java:1366)
        ... 16 more

May 30, 2018 8:56:12 PM org.opensolaris.opengrok.authorization.AuthorizationFramework reload
WARNING: Plugin directory not found or not readable: null. All requests allowed.
May 30, 2018 8:56:12 PM org.opensolaris.opengrok.web.WebappListener contextInitialized
INFO: Could not load statistics from a file.
java.io.FileNotFoundException: Statistics file is not set (null)
        at org.opensolaris.opengrok.configuration.RuntimeEnvironment.loadStatistics(RuntimeEnvironment.java:1768)
        at org.opensolaris.opengrok.web.WebappListener.contextInitialized(WebappListener.java:108)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

May 30, 2018 8:56:12 PM org.opensolaris.opengrok.web.WebappListener contextInitialized
INFO: Could not load statistics from a file.
java.io.FileNotFoundException: Statistics file is not set (null)
        at org.opensolaris.opengrok.configuration.RuntimeEnvironment.loadStatistics(RuntimeEnvironment.java:1768)
        at org.opensolaris.opengrok.web.WebappListener.contextInitialized(WebappListener.java:122)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by sreehari83** [comment]
/vol/opengrok_scm/conf_parallel/dcp.xml
===============================
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE java [
<!ELEMENT boolean ( #PCDATA ) >

<!ELEMENT java ( object ) >
<!ATTLIST java class NMTOKEN #REQUIRED >
<!ATTLIST java version NMTOKEN #REQUIRED >

<!ELEMENT object ( void+ ) >
<!ATTLIST object class ( org.opensolaris.opengrok.configuration.Configuration | org.opensolaris.opengrok.configuration.Project | org.opensolaris.opengrok.history.RepositoryInfo ) #REQUIRED >
<!ATTLIST object id NMTOKEN #IMPLIED >

<!ELEMENT string ( #PCDATA ) >

<!ELEMENT void ( boolean | object | string | void )* >
<!ATTLIST void method ( add ) #IMPLIED >
<!ATTLIST void property NMTOKEN #IMPLIED >
]>

<java version="1.8.0_121" class="java.beans.XMLDecoder">

 <object class="org.opensolaris.opengrok.configuration.Configuration">
  
  <void property="allowLeadingWildcard">
   <boolean>true</boolean>
  </void>

  
  <void property="ctags">
   <string>/opt/ctags/bin/ctags</string>
  </void>

  
  <void property="dataRoot">
   <string>/vol/opengrok_scm/index_data_parallel</string>
  </void>

  

  
  <void property="ignoredNames">
   <void property="items">
    <void method="add">
     <string>*.bz2</string>
    </void>
    <void method="add">
     <string>*.srecord</string>
    </void>
    <void method="add">
     <string>*.zip</string>
    </void>
    <void method="add">
     <string>*.jar</string>
    </void>
    <void method="add">
     <string>*.tar</string>
    </void>
   </void>
  </void>

  <void property="projects">

   <void method="add">
    <object class="org.opensolaris.opengrok.configuration.Project">
     <void property="description">
      <string>dcp</string>
     </void>
     <void property="path">
      <string>/dcp</string>
     </void>
    </object>
   </void>

  </void>

  
  <void property="repositories">

   <void method="add">
    <object class="org.opensolaris.opengrok.history.RepositoryInfo">
     <void property="datePattern">
      <string>yyyy-MM-dd'T'HH:mm:ss.SSS'Z'</string>
     </void>
     <void property="directoryName">
      <string>/vol/opengrok_scm/source_data_parallel/dcp</string>
     </void>
     <void property="type">
      <string>Subversion</string>
     </void>
     <void property="working">
      <boolean>true</boolean>
     </void>
    </object>
   </void>


   </void>

  
  <void property="sourceRoot">
   <string>/vol/opengrok_scm/source_data_parallel</string>
  </void>
 </object>
</java>

**Comment by Orviss** [comment]
You are probably reading an old config file. Run indexer which will generate a new one and replace the old one with it.

**Comment by vladak** [comment]
I think some old project properties are in the read-only configuration. If
I recall correctly project description changed to project mame.

Dne čt 31. 5. 2018 9:03 uživatel Adam Hornáček <notifications@github.com>
napsal:

**Comment by vladak** [comment]
See b3976d82.
