### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by sreehari83** [oracle/opengrok#2142]
Am getting the following error while starting the Tomcat  with new configuration file which is generated by following index command
=========================================

 /usr/java/default/bin/java -server -Xms8048m -Xmx16096m -Dorg.opensolaris.opengrok.history.Subversion=/opt/CollabNet_Subversion/bin/svn -Dorg.opensolaris.opengrok.history.cvs=/usr/bin/cvs -Djava.util.logging.config.file=/vol/opengrok_scm/logging.properties.parallel -jar /opt/tomcat-instances/opengrok-1.1-rc27/lib/opengrok.jar -O on -T 24 -d /vol/opengrok_scm/index_data_parallel -s /vol/opengrok_scm/source_data_parallel -c /opt/ctags/bin/ctags -W /vol/opengrok_scm/conf_parallel/dcp1.xml -S -P -H -r on

Java:
java version "1.8.0_121"

Tomcat:
apache-tomcat-8.5.14

Error:
==============
SEVERE: Exception sending context initialized event to listener instance of class org.opensolaris.opengrok.web.WebappListener
java.lang.ArrayIndexOutOfBoundsException: 0
        at java.beans.XMLDecoder.readObject(XMLDecoder.java:250)
        at org.opensolaris.opengrok.configuration.Configuration.decodeObject(Configuration.java:1366)
        at org.opensolaris.opengrok.configuration.Configuration.read(Configuration.java:1344)
        at org.opensolaris.opengrok.configuration.RuntimeEnvironment.readConfiguration(RuntimeEnvironment.java:1385)
        at org.opensolaris.opengrok.web.WebappListener.contextInitialized(WebappListener.java:72)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Jun 04, 2018 8:07:06 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Jun 04, 2018 8:07:06 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/source] startup failed due to previous errors
Jun 04, 2018 8:07:06 PM org.opensolaris.opengrok.configuration.RuntimeEnvironment stopWatchDogService
INFO: Watchdog stoped

**Comment by vladak** [comment]
The usual question: when exactly this started happening ? What changed ?

**Comment by vladak** [comment]
Based on the above log snippet, the webapp did not accept new configuration. Either the configuration is corrupted or the webapp is running different version than indexer.

First thing to verify is that webapp indeed reads `/vol/opengrok_scm/conf_parallel/dcp1.xml`. What is configured in `web.xml` ? Normally it contains something like this:

```xml
    <context-param>
        <description>Full path to the configuration file where OpenGrok can read its configuration</description>
        <param-name>CONFIGURATION</param-name>
        <param-value>/opengrok/etc/configuration.xml</param-value>
    </context-param>
```

so in your case it should look like this:

```xml
    <context-param>
        <description>Full path to the configuration file where OpenGrok can read its configuration</description>
        <param-name>CONFIGURATION</param-name>
        <param-value>/vol/opengrok_scm/conf_parallel/dcp1.xml</param-value>
    </context-param>
```

Now, people do leave the default location in place and use symlinks however that is not very robust.
The `deploy` command of the `OpenGrok` shell script has a piece of code that repacks `source.war` so that it contains the correct path to configuration (based on configuration passed via environment variables).

Next thing to check is that the indexer has the same `opengrok.jar` version as the webapp. The version can be determined as follows:

```shell
java -jar opengrok.jar -V
```

So, use `-V` with `opengrok.jar` in distribution directory (`/opt/tomcat-instances/opengrok-1.1-rc27/lib/opengrok.jar` in your case) and in the Tomcat directory (e.g. `/var/tomcat8/webapps/source/WEB-INF/lib/opengrok.jar`) and compare the versions reported.

**Comment by sreehari83** [comment]
After generating the /vol/opengrok_scm/conf_parallel/dcp1.xml file and have copied to /var/opengrok/etc/configuration.xml

and both versions of opengrok.jar files are smae.

/opt/tomcat-instances/opengrok/webapps/source/WEB-INF:
==============================================
<context-param>
        <description>Full path to the configuration file where OpenGrok can read its configuration</description>
        <param-name>CONFIGURATION</param-name>
        <param-value>/var/opengrok/etc/configuration.xml</param-value>
    </context-param>

/opt/tomcat-instances/opengrok/webapps/source/WEB-INF/lib:
==================================================
java -jar opengrok.jar -V 
OpenGrok v1.1-rc27 rev d5581ed33b419405de129d7e1812ae163dde0fea

/opt/tomcat-instances/opengrok/lib
==============================
 java -jar opengrok.jar -V 
OpenGrok v1.1-rc27 rev d5581ed33b419405de129d7e1812ae163dde0fea

/opt/tomcat-instances/opengrok/webapps/source/WEB-INF/lib:
================================================
In this path opengrok-1.1-rc27.jar is available instead of opengrok.jar .
and copied  opengrok.jar from /opt/tomcat-instances/opengrok/lib to /opt/tomcat-instances/opengrok/webapps/source/WEB-INF/lib

Still facing the same error.

SEVERE: Exception sending context initialized event to listener instance of class org.opensolaris.opengrok.web.WebappListener
java.lang.ArrayIndexOutOfBoundsException: 0
        at java.beans.XMLDecoder.readObject(XMLDecoder.java:250)
        at org.opensolaris.opengrok.configuration.Configuration.decodeObject(Configuration.java:1366)
        at org.opensolaris.opengrok.configuration.Configuration.read(Configuration.java:1344)
        at org.opensolaris.opengrok.configuration.RuntimeEnvironment.readConfiguration(RuntimeEnvironment.java:1385)
        at org.opensolaris.opengrok.web.WebappListener.contextInitialized(WebappListener.java:72)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Jun 05, 2018 3:03:35 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Jun 05, 2018 3:03:35 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/source] startup failed due to previous errors
Jun 05, 2018 3:03:35 AM org.opensolaris.opengrok.configuration.RuntimeEnvironment stopWatchDogService
INFO: Watchdog stoped

**Comment by vladak** [comment]
Is it possible to post the full configuration file somewhere ?

**Comment by sreehari83** [comment]
ok will share full file 
/var/opengrok/etc/configuration.xml

**Comment by sreehari83** [comment]
sorry its my mistake , have copied wrong file to /var/opengrok/etc/configuration.xml.

Now its working ...

Thank you for your Support.
