### ISSUE TITLE
indexing failure while linking pending paths

### ISSUE THREAD

**Issue by xiangp126** [oracle/opengrok#2174]
OpenGrok 1.1-rc29
OS : CentOS 6.9
Git: version 2.18
JDK: 8u172
Tomcat: version 8
Ctag: latest version from github(universal-ctag)

Loading the default instance configuration ...
10:18:02 WARNING: Error from ctags: ctags: Warning: Language "clojure" already defined
10:18:02 WARNING: Error from ctags: ctags: Warning: Language "rust" already defined
10:18:02 WARNING: Error from ctags: ctags: Warning: Language "pascal" already defined
10:30:22 WARNING: Failed to link: /opt/opengrok/data/xref/linux-4.17/scripts/dtc/include-prefixes/openrisc -> ../../../arch/openrisc/boot/dts
10:30:22 WARNING: Failed to link: /opt/opengrok/data/xref/linux-4.17/scripts/dtc/include-prefixes/xtensa -> ../../../arch/xtensa/boot/dts
10:30:22 WARNING: Failed to link: /opt/opengrok/data/xref/linux-4.17/scripts/dtc/include-prefixes/arm64 -> ../../../arch/arm64/boot/dts
10:30:22 WARNING: Failed to link: /opt/opengrok/data/xref/linux-4.17/scripts/dtc/include-prefixes/mips -> ../../../arch/mips/boot/dts
10:30:22 WARNING: Failed to link: /opt/opengrok/data/xref/linux-4.17/scripts/dtc/include-prefixes/arm -> ../../../arch/arm/boot/dts
10:30:22 WARNING: Failed to link: /opt/opengrok/data/xref/linux-4.17/scripts/dtc/include-prefixes/arc -> ../../../arch/arc/boot/dts
10:30:22 WARNING: Failed to link: /opt/opengrok/data/xref/linux-4.17/scripts/dtc/include-prefixes/microblaze -> ../../../arch/microblaze/boot/dts
10:30:22 WARNING: Failed to link: /opt/opengrok/data/xref/linux-4.17/scripts/dtc/include-prefixes/h8300 -> ../../../arch/h8300/boot/dts
10:30:22 WARNING: Failed to link: /opt/opengrok/data/xref/linux-4.17/scripts/dtc/include-prefixes/powerpc -> ../../../arch/powerpc/boot/dts
10:30:22 WARNING: Failed to link: /opt/opengrok/data/xref/linux-4.17/scripts/dtc/include-prefixes/sh -> ../../../arch/sh/boot/dts
10:30:22 WARNING: Failed to link: /opt/opengrok/data/xref/linux-4.17/scripts/dtc/include-prefixes/dt-bindings -> ../../../include/dt-bindings
10:30:22 WARNING: Failed to link: /opt/opengrok/data/xref/linux-4.17/scripts/dtc/include-prefixes/nios2 -> ../../../arch/nios2/boot/dts
10:30:22 WARNING: Failed to link: /opt/opengrok/data/xref/linux-4.17/scripts/dtc/include-prefixes/c6x -> ../../../arch/c6x/boot/dts
10:30:22 WARNING: An error occurred while finishing writer and completer
java.io.IOException: 13 failures (100.0%) while linking pending paths
        at org.opensolaris.opengrok.index.PendingFileCompleter.completeLinkages(PendingFileCompleter.java:306)
        at org.opensolaris.opengrok.index.PendingFileCompleter.complete(PendingFileCompleter.java:169)
        at org.opensolaris.opengrok.index.IndexDatabase.finishWriting(IndexDatabase.java:1613)
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:516)
        at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:222)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.NoSuchFileException: /opt/opengrok/data/xref/linux-4.17/scripts/dtc/include-prefixes/openrisc
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.createSymbolicLink(UnixFileSystemProvider.java:457)
        at java.nio.file.Files.createSymbolicLink(Files.java:1043)
        at org.opensolaris.opengrok.index.PendingFileCompleter.doLink(PendingFileCompleter.java:353)
        at org.opensolaris.opengrok.index.PendingFileCompleter.lambda$completeLinkages$6(PendingFileCompleter.java:289)
        at java.util.stream.Collectors.lambda$groupingByConcurrent$51(Collectors.java:1070)
        at java.util.stream.ReferencePipeline.lambda$collect$1(ReferencePipeline.java:496)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

10:30:22 SEVERE: Problem updating lucene index database:
java.io.IOException: 13 failures (100.0%) while linking pending paths
        at org.opensolaris.opengrok.index.PendingFileCompleter.completeLinkages(PendingFileCompleter.java:306)
        at org.opensolaris.opengrok.index.PendingFileCompleter.complete(PendingFileCompleter.java:169)
        at org.opensolaris.opengrok.index.IndexDatabase.finishWriting(IndexDatabase.java:1613)
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:516)
        at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:222)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.NoSuchFileException: /opt/opengrok/data/xref/linux-4.17/scripts/dtc/include-prefixes/openrisc
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.createSymbolicLink(UnixFileSystemProvider.java:457)
        at java.nio.file.Files.createSymbolicLink(Files.java:1043)
        at org.opensolaris.opengrok.index.PendingFileCompleter.doLink(PendingFileCompleter.java:353)
        at org.opensolaris.opengrok.index.PendingFileCompleter.lambda$completeLinkages$6(PendingFileCompleter.java:289)
        at java.util.stream.Collectors.lambda$groupingByConcurrent$51(Collectors.java:1070)
        at java.util.stream.ReferencePipeline.lambda$collect$1(ReferencePipeline.java:496)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

When on Mac the indexing procedure is OK, but on CentOS it ends up with above error
I delete opengrok/data/* for many times, but still failed

can anyone has any idea about this? thanks very much.

**Comment by vladak** [comment]
closing as a dup of #2148
