### ISSUE TITLE
No index is created if linking symlinks fails (java.io.IOException: 1 failures (100.0%) while linking pending paths)

### ISSUE THREAD

**Issue by caminada** [oracle/opengrok#2183]
If a symlink linking fails during creation of index, no index is created at all.

Exception:
```
WARNING: Failed to link: /data/grok/index/xref/test/base/devel/unittests/shared/bash -> ../../shared/bash
Jun 25, 2018 8:00:35 PM org.opensolaris.opengrok.index.IndexDatabase finishWriting
WARNING: An error occurred while finishing writer and completer
java.io.IOException: 1 failures (100.0%) while linking pending paths
	at org.opensolaris.opengrok.index.PendingFileCompleter.completeLinkages(PendingFileCompleter.java:306)
	at org.opensolaris.opengrok.index.PendingFileCompleter.complete(PendingFileCompleter.java:169)
	at org.opensolaris.opengrok.index.IndexDatabase.finishWriting(IndexDatabase.java:1613)
	at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:516)
	at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:222)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.NoSuchFileException: /data/grok/index/xref/test/base/devel/unittests/shared/bash
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createSymbolicLink(UnixFileSystemProvider.java:457)
	at java.nio.file.Files.createSymbolicLink(Files.java:1043)
	at org.opensolaris.opengrok.index.PendingFileCompleter.doLink(PendingFileCompleter.java:353)
	at org.opensolaris.opengrok.index.PendingFileCompleter.lambda$completeLinkages$6(PendingFileCompleter.java:289)
	at java.util.stream.Collectors.lambda$groupingByConcurrent$51(Collectors.java:1070)
	at java.util.stream.ReferencePipeline.lambda$collect$1(ReferencePipeline.java:496)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:496)
	at org.opensolaris.opengrok.index.PendingFileCompleter.completeLinkages(PendingFileCompleter.java:286)
	... 9 more

Jun 25, 2018 8:00:35 PM org.opensolaris.opengrok.index.IndexDatabase$1 run
SEVERE: Problem updating lucene index database: 
java.io.IOException: 1 failures (100.0%) while linking pending paths
	at org.opensolaris.opengrok.index.PendingFileCompleter.completeLinkages(PendingFileCompleter.java:306)
	at org.opensolaris.opengrok.index.PendingFileCompleter.complete(PendingFileCompleter.java:169)
	at org.opensolaris.opengrok.index.IndexDatabase.finishWriting(IndexDatabase.java:1613)
	at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:516)
	at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:222)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.NoSuchFileException: /data/grok/index/xref/test/base/devel/unittests/shared/bash
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createSymbolicLink(UnixFileSystemProvider.java:457)
	at java.nio.file.Files.createSymbolicLink(Files.java:1043)
	at org.opensolaris.opengrok.index.PendingFileCompleter.doLink(PendingFileCompleter.java:353)
	at org.opensolaris.opengrok.index.PendingFileCompleter.lambda$completeLinkages$6(PendingFileCompleter.java:289)
	at java.util.stream.Collectors.lambda$groupingByConcurrent$51(Collectors.java:1070)
	at java.util.stream.ReferencePipeline.lambda$collect$1(ReferencePipeline.java:496)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:496)
	at org.opensolaris.opengrok.index.PendingFileCompleter.completeLinkages(PendingFileCompleter.java:286)
	... 9 more
```

This results in a broken index:
```
[grok@engey ~]$ ll /data/grok/index/index/test/
total 4
-rw-rw-r--. 1 grok grok  0 Jun 25 19:48 dirty
-rw-rw-r--. 1 grok grok 69 Jun 25 19:48 segments_1
[grok@engey ~]$
```
The corresponding path to ``/data/grok/index/xref/test/base/devel/unittests/shared/bash`` in the sources exists and is a valid symlink to a directory containing one file:
```
[grok@engey ~]$ ll /data/grok/sources/test/base/devel/unittests/shared/
total 0
lrwxrwxrwx. 1 grok grok 17 Jun 25 19:30 bash -> ../../shared/bash
[grok@engey ~]$ ll /data/grok/sources/test/base/devel/unittests/shared/bash
lrwxrwxrwx. 1 grok grok 17 Jun 25 19:30 /data/grok/sources/test/base/devel/unittests/shared/bash -> ../../shared/bash
[grok@engey ~]$ ll /data/grok/sources/test/base/devel/unittests/shared/bash/
total 4
-rw-rw-r--. 1 grok grok 25 Jun 25 19:36 test.sh
[grok@engey ~]$ 
```

Tested with latest release 1.1-rc30
Here is the sample tar.gz of the sources I've tested with: [https://1drv.ms/u/s!ApkkPUya9cYwhu5AAlpG8HKTsIPelg](https://1drv.ms/u/s!ApkkPUya9cYwhu5AAlpG8HKTsIPelg)

**Comment by caminada** [comment]
The exception occurs on code introduced in https://github.com/oracle/opengrok/issues/2080

**Comment by vladak** [comment]
closing as dup of #2148
