### ISSUE TITLE
REST errors when indexing

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2193]
After the upgrade with the #2184 bits and deploying the new webapp the indexer started throwing out these messages:

```
Couldn't notify the webapp: InboundJaxrsResponse{context=ClientResponse{method=PUT, uri=http://localhost:8080/source/api/v1/projects/apr-util-1.3/indexed, status=302, reason=Found}}
11:01:20 SEVERE: Failed to send configuration to http://localhost:8080/source (is web application server running with opengrok deployed?)
java.io.IOException: InboundJaxrsResponse{context=ClientResponse{method=PUT, uri=http://localhost:8080/source/api/v1/configuration?reindex=true, status=302, reason=Found}}
        at org.opensolaris.opengrok.configuration.RuntimeEnvironment.writeConfiguration(RuntimeEnvironment.java:1393)
        at org.opensolaris.opengrok.index.Indexer.sendToConfigHost(Indexer.java:1118)
        at org.opensolaris.opengrok.index.Indexer.main(Indexer.java:309)
```

**Comment by vladak** [comment]
The 302 is redirection, so this is probably specific to the staging environment I am running this in.

**Comment by vladak** [comment]
Yes, this is due to the fact that in that environment Tomcat listens on port 8888 and Apache serves as reverse proxy. The 8080 port is configured in Apache for HTTPS redirect + it enforces SSO login, hence the redirect.

**Comment by tulinkry** [comment]
But shouldn't it work also for the 8080?

**Comment by vladak** [comment]
In this setup no. 8080 is just a convenience for redirection.

Dne pá 29. 6. 2018 11:35 uživatel Kryštof Tulinger <notifications@github.com>
napsal:

**Comment by Orviss** [comment]
Maybe it would solve to add:
```java
property(ClientProperties.FOLLOW_REDIRECTS, Boolean.TRUE)
```
to the REST API call.

Not sure if it's desired though.

**Comment by vladak** [comment]
That won't help. The request does not even reach Tomcat.

Dne pá 29. 6. 2018 11:39 uživatel Adam Hornáček <notifications@github.com>
napsal:

**Comment by tulinkry** [comment]
I think the client should follow the redirects.
This is the default behaviour for `wget`.

**Comment by tulinkry** [comment]
> That won't help. The request does not even reach Tomcat.

It doesn't reach because it doesn't follow the apache redirect.

**Comment by vladak** [comment]
Well, in our env it would have to have the authn headers/cookie but I get
the point.

Dne pá 29. 6. 2018 11:49 uživatel Kryštof Tulinger <notifications@github.com>
napsal:
