### ISSUE TITLE
check whether -U value is correctly formed URI

### ISSUE THREAD

**Issue by TusharPawar11** [oracle/opengrok#2216]
I am install 
1.opengrok-1.1-rc33.tar.gz
2.apache-tomcat-8.5.32.tar.gz
3.jdk-10.0.1_linux-x64_bin.tar.gz
4.ctags-5.8-1.i386.rpm
5.code checkout using SVN 

and set the path and all config setting .

While update got the below error .may i know for this required  glassfish web server .

Please suggest.

Jul 13, 2018 6:25:37 PM org.opensolaris.opengrok.index.Indexer doIndexerExecution
INFO: Starting indexing
Jul 13, 2018 6:25:43 PM org.opensolaris.opengrok.index.IndexDatabase update
SEVERE: Failed with unexpected RuntimeException
java.lang.IllegalArgumentException: Schema specific part is opaque.
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.checkSsp(JerseyUriBuilder.java:714)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:356)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:72)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:154)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:60)
        at org.opensolaris.opengrok.index.IndexDatabase.markProjectIndexed(IndexDatabase.java:375)
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:515)
        at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:224)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)

Jul 13, 2018 6:25:43 PM org.opensolaris.opengrok.index.IndexDatabase$1 run
SEVERE: Problem updating lucene index database:
java.lang.IllegalArgumentException: Schema specific part is opaque.
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.checkSsp(JerseyUriBuilder.java:714)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:356)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:72)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:154)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:60)
        at org.opensolaris.opengrok.index.IndexDatabase.markProjectIndexed(IndexDatabase.java:375)
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:515)
        at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:224)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)

Jul 13, 2018 6:25:45 PM org.opensolaris.opengrok.index.IndexDatabase update
SEVERE: Failed with unexpected RuntimeException
java.lang.IllegalArgumentException: Schema specific part is opaque.
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.checkSsp(JerseyUriBuilder.java:714)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:356)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:72)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:154)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:60)
        at org.opensolaris.opengrok.index.IndexDatabase.markProjectIndexed(IndexDatabase.java:375)
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:515)
        at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:224)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)

Jul 13, 2018 6:25:45 PM org.opensolaris.opengrok.index.IndexDatabase$1 run
SEVERE: Problem updating lucene index database:
java.lang.IllegalArgumentException: Schema specific part is opaque.
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.checkSsp(JerseyUriBuilder.java:714)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:356)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:72)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:154)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:60)
        at org.opensolaris.opengrok.index.IndexDatabase.markProjectIndexed(IndexDatabase.java:375)
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:515)
        at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:224)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)

Jul 13, 2018 6:25:52 PM org.opensolaris.opengrok.index.DefaultIndexChangedListener fileRemove
INFO: Remove file:/FC_STANDIN_DEV_10Oct17/javaprojects/com.ofss.fc.standin.infra/src/com/ofss/fc/infra/core/config/SfConfigDtlsLoader.java
Jul 13, 2018 6:25:52 PM org.opensolaris.opengrok.index.DefaultIndexChangedListener fileRemove
INFO: Remove file:/FC_STANDIN_DEV_10Oct17/javaprojects/com.ofss.fc.standin.validation/src/com/iflex/fcr/xface/account/validator/CustomerAccountMapValidator.java
Jul 13, 2018 6:25:52 PM org.opensolaris.opengrok.index.DefaultIndexChangedListener fileRemove
INFO: Remove file:/FC_STANDIN_DEV_10Oct17/javaprojects/com.ofss.fc.standin.webservice.client.epi/src/com/iflex/fcr/xface/account/casa/FetchCurrentAndSavingsAccountResponseDTO.java
Jul 13, 2018 6:25:54 PM org.opensolaris.opengrok.index.IndexDatabase update
SEVERE: Failed with unexpected RuntimeException
java.lang.IllegalArgumentException: Schema specific part is opaque.
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.checkSsp(JerseyUriBuilder.java:714)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:356)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:72)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:154)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:60)
        at org.opensolaris.opengrok.index.IndexDatabase.markProjectIndexed(IndexDatabase.java:375)
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:515)
        at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:224)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)

Jul 13, 2018 6:25:54 PM org.opensolaris.opengrok.index.IndexDatabase$1 run
SEVERE: Problem updating lucene index database:
java.lang.IllegalArgumentException: Schema specific part is opaque.
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.checkSsp(JerseyUriBuilder.java:714)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:356)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:72)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:154)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:60)
        at org.opensolaris.opengrok.index.IndexDatabase.markProjectIndexed(IndexDatabase.java:375)
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:515)
        at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:224)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)

Jul 13, 2018 6:26:01 PM org.opensolaris.opengrok.index.IndexDatabase update
SEVERE: Failed with unexpected RuntimeException
java.lang.IllegalArgumentException: Schema specific part is opaque.
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.checkSsp(JerseyUriBuilder.java:714)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:356)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:72)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:154)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:60)
        at org.opensolaris.opengrok.index.IndexDatabase.markProjectIndexed(IndexDatabase.java:375)
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:515)
        at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:224)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)

Jul 13, 2018 6:26:01 PM org.opensolaris.opengrok.index.IndexDatabase$1 run
SEVERE: Problem updating lucene index database:
java.lang.IllegalArgumentException: Schema specific part is opaque.
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.checkSsp(JerseyUriBuilder.java:714)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:356)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:72)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:154)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:60)
        at org.opensolaris.opengrok.index.IndexDatabase.markProjectIndexed(IndexDatabase.java:375)
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:515)
        at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:224)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by Orviss** [comment]
You need to change the `-U` option to the address where your application is deployed: e.g. `http://localhost:8080/source` because of the movement to REST API.

**Comment by vladak** [comment]
The -U optarg should be checked if it is correctly formed.

**Comment by TusharPawar11** [comment]
Hi Orviss ,

java -Xms2048m -Xmx4096m -jar /mnt/devops_0/opengrok/lib/opengrok.jar -U localhost:8080 -R /mnt/devops_0/opengrok/data/configuration.xml


using this command for indexing but the getting same error .

opengrok page is opening  but  not with projects

**Comment by TusharPawar11** [comment]
Hi ,

On webpage 


There was an error!
CONFIGURATION parameter has not been configured in web.xml! Please configure your webapp.

Unable to determine source root path. Missing configuration?

java.io.FileNotFoundException: Unable to determine source root path. Missing configuration?
	at org.opensolaris.opengrok.web.PageConfig.checkSourceRootExistence(PageConfig.java:1609)
	at org.apache.jsp.index_jsp._jspService(index_jsp.java:219)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opensolaris.opengrok.web.ResponseHeaderFilter.doFilter(ResponseHeaderFilter.java:41)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opensolaris.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:55)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opensolaris.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:97)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by Orviss** [comment]
You can check the current config of the webapp by `http://localhost:8080/api/v1/configuration`.

It will be probably empty since you see that message. So check if the `/var/opengrok/etc/configuration.xml` file exists or if you have different configuration path then check if `web.xml` has this path specified.

Otherwise, you can use `-W path` option when running indexer to store it somewhere.

However, this is for a long conversation, check: <https://github.com/oracle/opengrok/wiki/Read-only-configuration>

**Comment by tulinkry** [comment]
> Hi ,
On webpage
There was an error!
CONFIGURATION parameter has not been configured in web.xml! Please configure your webapp.

This is a case of missing configuration, use `-W path` like @Orviss told you.

**Comment by TusharPawar11** [comment]
Dear all ,

Thanks for your help ....

Issue is that all after deploying the source.jar file in tomcat there are 2 web.xml files(apache_tomcat/conf/web.xml and another at apache_tomcat/webapps/source/WEB-INF/web.xml) generated in the tomcat server . we need to the change the path of data in the WEB-INF web.xml file after that its working proper .

**Comment by vladak** [comment]
If you mean the CONFIGURATION path in web.xml the deploy script takes care
of the substitution if passed the correct variable.

Dne čt 19. 7. 2018 8:05 uživatel TusharPawar11 <notifications@github.com>
napsal:
