### ISSUE TITLE
LdapFacade error messages should be specific about the server pool

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2281]
During LDAP outages I have seen messages like "Server pool is still broken" or "Tried all servers in a pool but no server works". Those were not very helpful on a setup with multiple server pools. The messages should be specific about the server pool that is experiencing a problem.

**Comment by vladak** [comment]
To get some more context, the following problem (which is probably caused by not optimal LDAP search base configuration) sparked the issue. The server pool had just 1 server in it (that is internally load balanced AFAIK):

```
09-Aug-2018 13:18:41.240 SEVERE [http-nio-8080-exec-173] opengrok.auth.plugin.ldap.LdapFacade.lookup An arbitrary LDAP error occurred.
 javax.naming.ServiceUnavailableException: ldap.server.foo:389; socket closed; remaining name 'dc=oracle,dc=com'
        at com.sun.jndi.ldap.Connection.readReply(Connection.java:454)
        at com.sun.jndi.ldap.LdapClient.getSearchReply(LdapClient.java:638)
        at com.sun.jndi.ldap.LdapClient.search(LdapClient.java:561)
        at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:1985)
        at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1844)
        at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1769)
        at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:392)
        at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:358)
        at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:341)
        at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:267)
        at opengrok.auth.plugin.ldap.LdapServer.search(LdapServer.java:214)
        at opengrok.auth.plugin.ldap.LdapServer.search(LdapServer.java:182)
        at opengrok.auth.plugin.ldap.LdapFacade.lookup(LdapFacade.java:317)
        at opengrok.auth.plugin.ldap.LdapFacade.lookup(LdapFacade.java:275)
        at opengrok.auth.plugin.ldap.LdapFacade.lookupLdapContent(LdapFacade.java:248)
        at opengrok.auth.plugin.LdapUserPlugin.fillSession(LdapUserPlugin.java:115)
        at opengrok.auth.plugin.AbstractLdapPlugin.ensureSessionExists(AbstractLdapPlugin.java:261)
        at opengrok.auth.plugin.AbstractLdapPlugin.isAllowed(AbstractLdapPlugin.java:302)
...
```
