### ISSUE TITLE
When using the "Author" as search, return duplicated records

### ISSUE THREAD

**Issue by tiffanyzhou** [oracle/opengrok#2326]
When using the "Author" as search condition with History search in OpenGrok，the results show two duplicated records. 

the system info:
Opengrok version is 1.1-rc34, and git version is 2.18.0

![two_identical_records](https://user-images.githubusercontent.com/39646571/44826450-a8d23400-ac41-11e8-8a1c-f8dfa5d729c6.jpg)

**Comment by vladak** [comment]
Cannot replicate this, at least on http://demo.opengrok.org (currently running 1.1-rc38)

Could you try with latest 1.1-rc38 and possibly construct a simple Git repo which can be used to replicate the problem ?

**Comment by tiffanyzhou** [comment]
I think this is not opengrok version caused，maybe other problems cauesd，when i run command "OPENGROK_VERBOSE=true OPENGROK_INSTANCE_BASE=/var/opengrok/ /var/opengrok/bin/OpenGrok index /var/opengrok/src/", it will report errors,such as "SEVERE: Mis-configuration of webapp host", "Failed to send configuration to http://localhost:8080/source (is web application server running with opengrok deployed", "SEVERE: CTag reader cycle was interrupted!" 
I don't know how to resolve these issues，please help ，thanks a lot

**Comment by vladak** [comment]
For the first problem: Is your webapp deployed ? Check its logs.
For the second problem: could you try the latest Universal ctags ?

**Comment by tiffanyzhou** [comment]
Yes, my webapp deployed, in the logs of opengrok have some exceptions,such as :"FINE t1607 IndexDatabase.addFile: Exception from analyzer org.opensolaris.opengrok.analysis.archive.ZipAnalyzer", "FINE t1602 ClientExecutorProvidersConfigurator.lookupManagedScheduledExecutorService: null"
And I installed the lastest version of Exuberant ctags, do I have to replace it whit Universal ctags?

**Comment by tiffanyzhou** [comment]
I installed it with Universal ctags and reindex , there is no errors , but at the last log message where the index was created  ,there was a message about configuration.xml, and I wasn't sure if it was related to the LDAP integration.

"Couldn't notify the webapp: InboundJaxrsResponse{context=ClientResponse{method=PUT, uri=http://localhost:8080/source/api/v1/projecauthorized}}
11:11:11 SEVERE: Failed to send configuration to http://localhost:8080/source (is web application server running with opengrok dep
java.io.IOException: InboundJaxrsResponse{context=ClientResponse{method=PUT, uri=http://localhost:8080/source/api/v1/configurationhorized}}
	at org.opensolaris.opengrok.configuration.RuntimeEnvironment.writeConfiguration(RuntimeEnvironment.java:1395)
	at org.opensolaris.opengrok.index.Indexer.sendToConfigHost(Indexer.java:1124)
	at org.opensolaris.opengrok.index.Indexer.main(Indexer.java:311)
"

**Comment by vladak** [comment]
The `lookupManagedScheduledExecutorService` message in the log is innocuous, see #2211

**Comment by vladak** [comment]
The RESTful API URLs look really strange, as if they were rewritten somehow.

**Comment by tiffanyzhou** [comment]
hi, I upgrade opengrok to opengrok-1.1-rc41, when not restart tomcat how can I reindex (python) ? like 'sh OpenGrok update /var/opengrok/src/'(shell), there is not any infomation to refer to in this release
