### ISSUE TITLE
run pylint from venv

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2442]
For #2441 I tried running pylint from venv like so:
```diff
commit b2190ed558f6356812cb5aa4644c808599b577b3
Author: Vladimir Kotal <vlada@devnull.cz>
Date:   Wed Oct 24 17:38:12 2018 +0200

    run pylint from venv

diff --git a/dev/install-python-packages.sh b/dev/install-python-packages.sh
index 7272a696..b078fbca 100755
--- a/dev/install-python-packages.sh
+++ b/dev/install-python-packages.sh
@@ -8,7 +8,7 @@ if [[ $? != 0 ]]; then
 	exit 1
 fi
 
-python3 -m pip install pep8 flake8 virtualenv pylint
+python3 -m pip install pep8 flake8 virtualenv
 if [[ $? != 0 ]]; then
 	echo "cannot install Python packages"
 	exit 1
diff --git a/opengrok-tools/pom.xml b/opengrok-tools/pom.xml
index 2a08e73b..a7927bcb 100644
--- a/opengrok-tools/pom.xml
+++ b/opengrok-tools/pom.xml
@@ -139,21 +139,6 @@ Portions Copyright (c) 2017-2018, Chris Fraire <cfraire@me.com>.
                             <goal>exec</goal>
                         </goals>
                     </execution>
-                    <execution>
-                        <id>Python lint</id>
-                        <configuration>
-                            <executable>pylint</executable>
-                            <arguments>
-                                <argument>-E</argument>
-                                <argument>${project.build.sourceDirectory}/opengrok_tools</argument>
-                                <argument>${project.build.directory}/setup.py</argument>
-                            </arguments>
-                        </configuration>
-                        <phase>verify</phase>
-                        <goals>
-                            <goal>exec</goal>
-                        </goals>
-                    </execution>
                     <execution>
                         <id>generate python env</id>
                         <configuration>
@@ -201,6 +186,37 @@ Portions Copyright (c) 2017-2018, Chris Fraire <cfraire@me.com>.
                             <goal>exec</goal>
                         </goals>
                     </execution>
+                    <execution>
+                        <id>Install Python lint</id>
+                        <configuration>
+                            <executable>${project.build.directory}/env/bin/pip3</executable>
+                            <arguments>
+                                <argument>install</argument>
+                                <argument>pylint</argument>
+                            </arguments>
+                        </configuration>
+                        <phase>verify</phase>
+                        <goals>
+                            <goal>exec</goal>
+                        </goals>
+                    </execution>
+
+                    <execution>
+                        <id>Python lint</id>
+                        <configuration>
+                            <executable>${project.build.directory}/env/bin/pylint</executable>
+                            <workingDirectory>${project.build.directory}</workingDirectory>
+                            <arguments>
+                                <argument>-E</argument>
+                                <argument>${project.build.sourceDirectory}/opengrok_tools</argument>
+                                <argument>${project.build.directory}/setup.py</argument>
+                            </arguments>
+                        </configuration>
+                        <phase>verify</phase>
+                        <goals>
+                            <goal>exec</goal>
+                        </goals>
+                    </execution>
                     <execution>
                         <id>python-test</id>
                         <configuration>
diff --git a/opengrok-tools/src/main/python/requirements.txt b/opengrok-tools/src/main/python/requirements.txt
index 03114e98..92985bb0 100644
--- a/opengrok-tools/src/main/python/requirements.txt
+++ b/opengrok-tools/src/main/python/requirements.txt
@@ -6,7 +6,7 @@ jsonschema==2.6.0
 JsonSir==0.0.2
 Python-EasyConfig==0.1.7
 PyYAML==3.13
-requests>=2.2.1
+requests==2.19.1
 Resource==0.2.1
-six>=1.5.0
-urllib3>=1.7
+six==1.11.0
+urllib3==1.23
diff --git a/dev/install-python-packages.sh b/dev/install-python-packages.sh
index b078fbca..609660e8 100755
--- a/dev/install-python-packages.sh
+++ b/dev/install-python-packages.sh
@@ -2,12 +2,6 @@
 
 python3 -m pip install --upgrade pip
 
-python3 -m pip install -r opengrok-tools/src/main/python/requirements.txt
-if [[ $? != 0 ]]; then
-	echo "cannot install Python requirement packages"
-	exit 1
-fi
-
 python3 -m pip install pep8 flake8 virtualenv
 if [[ $? != 0 ]]; then
 	echo "cannot install Python packages"
```
however for Travis Linux build this failed with:
```
[INFO] --- exec-maven-plugin:1.6.0:exec (Install Python lint) @ opengrok-tools ---
Downloading/unpacking pylint
Downloading/unpacking mccabe (from pylint)
  Downloading mccabe-0.6.1-py2.py3-none-any.whl
Downloading/unpacking isort>=4.2.5 (from pylint)
Downloading/unpacking astroid>=2.0.0 (from pylint)
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/home/travis/build/oracle/opengrok/opengrok-tools/target/env/lib/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2482, in _dep_map
    return self.__dep_map
  File "/home/travis/build/oracle/opengrok/opengrok-tools/target/env/lib/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2344, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/oracle/opengrok/opengrok-tools/target/env/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/travis/build/oracle/opengrok/opengrok-tools/target/env/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/travis/build/oracle/opengrok/opengrok-tools/target/env/lib/python3.4/site-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/home/travis/build/oracle/opengrok/opengrok-tools/target/env/lib/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/home/travis/build/oracle/opengrok/opengrok-tools/target/env/lib/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/travis/build/oracle/opengrok/opengrok-tools/target/env/lib/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2517, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/home/travis/build/oracle/opengrok/opengrok-tools/target/env/lib/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2514, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/home/travis/build/oracle/opengrok/opengrok-tools/target/env/lib/python-wheels/setuptools-3.3-py2.py3-none-any.whl/_markerlib/markers.py", line 113, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'implementation_name' is not defined
```
which is likely a problem within the packages or environment (the Linux build runs on Ubuntu 14.04.5 LTS) so I am filing this as a placeholder for future changes.

**Comment by vladak** [comment]
Found 2 matching issues:
  - jupyter/notebook/issues/2605
    - solved by either `pip3 install --upgrade pip` or `pip3 install --upgrade setuptools`
  - ihabunek/toot/issues/10
    - solved by avoiding `~=` in `requirements.txt`
