### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: offset -1,length 4

### ISSUE THREAD

**Issue by jvaneck** [oracle/opengrok#2603]
I'm using release v1.1

When manually navigating to a folder structure (via http://ServerName/RepoName/xref/FolderName), we're getting the following error and I'm not sure quite why it's happening. 

If someone can point me in the right direction, that would be greatly appreciated

(this error shows up below the "search" / "clear" / "help" buttons that show up on the main search screen. 

```
offset -1,length 4

java.lang.StringIndexOutOfBoundsException: offset -1,length 4
	at java.base/java.lang.String.checkOffset(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.insert(Unknown Source)
	at java.base/java.lang.StringBuilder.insert(Unknown Source)
	at org.apache.jsp.list_jsp._jspService(list_jsp.java:465)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:99)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by vladak** [comment]
Is there anything special about this directory ? Does this happen every
time or just in some cases ? Does it happen for other directories as well ?
Was it happening before 1.1 ? Lastly, Could you provide full listing of the
directory ? (Ala `ls -al` , could have the names obfuscated)

pá 28. 12. 2018 20:37 odesílatel Jake VanEck <notifications@github.com>
napsal:

**Comment by jvaneck** [comment]
I didn't think there was any other folders doing it but there are a bunch out of the main 27 folders that are doing it. So I'm going to try to narrow down what's similar about them and report back my findings. 

Thanks for giving me some suggestions

**Comment by vladak** [comment]
Another thing that could be relevant is directory structure.

pá 28. 12. 2018 21:41 odesílatel Jake VanEck <notifications@github.com>
napsal:

**Comment by vladak** [comment]
I don't have access to the tooling right now, however the next thing to look at would be the Java source code at `list_jsp.java:465`.

**Comment by jvaneck** [comment]
Turns out this is not an opengrok bug and a bug caused by someone at our company manually modifying the opengrok source. :(

Super sorry about the hassle and thanks for pointing out that line of code. 


> 
> 
> I don't have access to the tooling right now, however the next thing to look at would be the Java source code at `list_jsp.java:465`.

**Comment by vladak** [comment]
No worries. Every experience counts.

po 31. 12. 2018 16:52 odesílatel Jake VanEck <notifications@github.com>
napsal:
