### ISSUE TITLE
Suggester initialization effect

### ISSUE THREAD

**Issue by Teriand** [oracle/opengrok#2622]
Continue #2618
"how to put the suggester initialization into effect (and how does it work if the terms supplied in the data are not present in the index)"

Currently "Suggestions:" box - empty

**Comment by vladak** [comment]
Reusing my sample project I performed these steps:

- see the initial popularity data
```
$ curl --include 'http://localhost:8080/source/api/v1/suggest/popularity/hints'
HTTP/1.1 200 
Content-Type: application/json
Content-Length: 2
Date: Tue, 15 Jan 2019 15:42:41 GMT

[]
```
- initialize the popularity with raw data:
```
$ curl --include --request POST --header "Content-Type: application/json" --data-binary "[{\"project\":\"hints\",\"field\":\"defs\",\"token\":\"getMessages\",\"increment\":100}]"  'http://localhost:8080/source/api/v1/suggest/init/raw'
HTTP/1.1 204 
Date: Tue, 15 Jan 2019 15:54:55 GMT
```
- see the state of the data again
```
$ curl --include 'http://localhost:8080/source/api/v1/suggest/popularity/hints'
HTTP/1.1 200 
Content-Type: application/json
Content-Length: 2
Date: Tue, 15 Jan 2019 15:54:58 GMT
```
- initialize suggester rebuild
```
$ curl -X PUT --include 'http://localhost:8080/source/api/v1/suggest/rebuild/hints'
HTTP/1.1 204 
Date: Tue, 15 Jan 2019 15:55:08 GMT
```
- wait a bit and see if the rebuild is finished (comparing modified times to the last time):
```
$ ls -al /var/opengrok/data/suggester/hints/
...
```
- retrieve the popularity data again:
```
$ curl --include 'http://localhost:8080/source/api/v1/suggest/popularity/hints'
HTTP/1.1 200 
Content-Type: application/json
Content-Length: 2
Date: Tue, 15 Jan 2019 15:55:24 GMT

[]
```

The`getMessages` definition is present in the index so I'd expect that it should be reflected in popularity data.

Also, interestingly the 2nd query to `suggest/popularity` endpoint returned empty output rather than empty JSON array.

**Comment by vladak** [comment]
The request to retrieve popularity data was not well formed, it should be:
```
$ curl --include 'http://localhost:8080/source/api/v1/suggest/popularity/hints?field=defs&all='
HTTP/1.1 200 
Content-Type: application/json
Content-Length: 46
Date: Tue, 15 Jan 2019 16:08:42 GMT

[{"getMessages":102},{"GetMessagesGrouped":1}]
```
Prior to the raw initialization I made 2 queries via the UI so this appears to be working correctly.

Also, no rebuild is needed for the number to be increased.

I hope this answered the question, if not feel free to reopen.

**Comment by Teriand** [comment]
```
curl --include --request POST --header "Content-Type: application/json" --data-binary "[{\"project\":\"hints\",\"field\":\"defs\",\"token\":\"getMessages\",\"increment\":100}]"  'http://localhost:8080/source_test/api/v1/suggest/init/raw'
HTTP/1.1 500
Content-Type: application/json
Content-Length: 16
Date: Thu, 17 Jan 2019 08:33:56 GMT
Connection: close
```

catalina log:
```
17-Jan-2019 11:56:42.526 WARNING [http-nio-8080-exec-6] org.opengrok.web.api.error.GenericExceptionMapper.toResponse Exception while processing request
 java.lang.NullPointerException
        at org.opengrok.suggest.Suggester.increaseSearchCount(Suggester.java:474)
        at org.opengrok.web.api.v1.suggester.provider.service.impl.SuggesterServiceImpl.increaseSearchCount(SuggesterServiceImpl.java:258)
        at org.opengrok.web.api.v1.controller.SuggesterController.addSearchCountsRaw(SuggesterController.java:264)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:183)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:59)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:61)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1458)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by tulinkry** [comment]
Do you have a project named hints? (I'm just assuming from the JSON)

**Comment by vladak** [comment]
What does `curl 'http://localhost:8080/source_test/api/v1/projects' say ?

That said, the null pointer dereference should be handled more gracefully - with a nice warning in the log.

**Comment by Teriand** [comment]
yes, i dont see project in 
```
\"project\":\"hints\"
```
with "MAIN" return 204

**Comment by Teriand** [comment]
work (opera browser):
![image](https://user-images.githubusercontent.com/26705069/51318966-d8f16680-1a6c-11e9-9c2b-7fe389a767c6.png)

in IE11 dont work:
```
Файл: search
SCRIPT438: Объект не поддерживает свойство или метод "includes"
Файл: utils-0.0.25.js, строка: 1787, столбец: 5
```

**Comment by vladak** [comment]
You are mixing different problems into single issue.
