### ISSUE TITLE
Failing maven tests in DragonFly BSD

### ISSUE THREAD

**Issue by tuxillo** [oracle/opengrok#2656]
Hi,

Some tests fail when running "./mvnw package" in DragonFly BSD. Can you please guys give me some pointers as to what could be failing?

Complete maven output: https://leaf.dragonflybsd.org/~tuxillo/archive/temp/maven_opengrok.log

Thanks,
Antonio Huete

**Comment by vladak** [comment]
It seems that some of the suggester tests are failing. This stands out:

```
[ERROR] incrementByValueTest(org.opengrok.suggest.SuggesterProjectDataTest)  Time elapsed: 1.145 s  <<< ERROR!
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/dragonflybsd-x86-64/libjnidispatch.so) not found in resource path ([file:/home/antonioh/s/opengrok/suggester/target/surefire/surefirebooter8864955201123584479.jar, file:/home/antonioh/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar])
	at org.opengrok.suggest.SuggesterProjectDataTest.init(SuggesterProjectDataTest.java:100)
	at org.opengrok.suggest.SuggesterProjectDataTest.incrementByValueTest(SuggesterProjectDataTest.java:201)
```

Looks like local Java problem.

**Comment by tuxillo** [comment]
Who should place that file there, maven?

**Comment by vladak** [comment]
My guess would be JDK.

so 2. 2. 2019 10:44 odesílatel Antonio Huete Jimenez <
notifications@github.com> napsal:

**Comment by vladak** [comment]
JNA comes from Maven central indeed. The source lives on https://github.com/java-native-access/jna. It is needed by Chronicle map library which is used by the Suggester implementation.

**Comment by vladak** [comment]
Downloaded jna.jar from http://repo1.maven.org/maven2/net/java/dev/jna/jna/5.2.0/jna-5.2.0.jar and indeed, the dynamic library is not present in the archive for Dragonfly BSD:
```
$ jar tvf jna-5.2.0.jar  | grep libjnidispatch.so
102591 Sat Jul 14 21:49:40 CEST 2018 com/sun/jna/linux-x86/libjnidispatch.so
112848 Sat Jul 14 21:52:22 CEST 2018 com/sun/jna/linux-x86-64/libjnidispatch.so
107656 Sat Jul 14 22:06:31 CEST 2018 com/sun/jna/linux-arm/libjnidispatch.so
111792 Sat Jul 14 22:14:47 CEST 2018 com/sun/jna/linux-armel/libjnidispatch.so
105072 Sat Jul 14 22:23:38 CEST 2018 com/sun/jna/linux-aarch64/libjnidispatch.so
123208 Sat Jul 14 22:43:00 CEST 2018 com/sun/jna/linux-ppc/libjnidispatch.so
133504 Sun Jul 15 00:04:28 CEST 2018 com/sun/jna/linux-ppc64le/libjnidispatch.so
133176 Sun Jul 15 00:17:33 CEST 2018 com/sun/jna/linux-mips64el/libjnidispatch.so
132568 Sat Jul 14 22:55:06 CEST 2018 com/sun/jna/linux-s390x/libjnidispatch.so
121092 Sun Jul 15 11:13:22 CEST 2018 com/sun/jna/sunos-x86/libjnidispatch.so
132256 Sun Jul 15 11:08:22 CEST 2018 com/sun/jna/sunos-x86-64/libjnidispatch.so
127516 Sun Jul 15 12:16:20 CEST 2018 com/sun/jna/sunos-sparc/libjnidispatch.so
139208 Sun Jul 15 11:59:12 CEST 2018 com/sun/jna/sunos-sparcv9/libjnidispatch.so
105689 Sun Jul 15 14:28:16 CEST 2018 com/sun/jna/freebsd-x86/libjnidispatch.so
112729 Sun Jul 15 14:19:30 CEST 2018 com/sun/jna/freebsd-x86-64/libjnidispatch.so
107831 Sun Jul 15 14:49:48 CEST 2018 com/sun/jna/openbsd-x86/libjnidispatch.so
114265 Sun Jul 15 14:46:36 CEST 2018 com/sun/jna/openbsd-x86-64/libjnidispatch.so
```
Similar problem: https://github.com/java-native-access/jna/issues/585
