### ISSUE TITLE
Cannot get opengrok to build on Debian 9 at all (tried multiple versions of Java)

### ISSUE THREAD

**Issue by reflectivist** [oracle/opengrok#2661]
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   PageConfigTest.canProcessHistory:112->assertCanProcess:534 expected:<> but was:<null>
[ERROR]   PageConfigTest.canProcessXref:132->assertCanProcess:534 expected:<> but was:<null>
[ERROR]   PageConfigTest.testCheckSourceRootExistence4:492 This should throw an exception when the file is not readable
[ERROR]   PageConfigTest.testGetAnnotation:396
[ERROR]   PageConfigTest.testGetLatestRevisionValid:259 expected:<aa35c258> but was:<null>
[ERROR]   PageConfigTest.testGetRevisionLocation:284
[ERROR]   PageConfigTest.testGetRevisionLocationNullQuery:310
[INFO] 
[ERROR] Tests run: 762, Failures: 7, Errors: 0, Skipped: 21
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OpenGrok ........................................... SUCCESS [  1.123 s]
[INFO] OpenGrok Indexer ................................... FAILURE [09:19 min]
[INFO] OpenGrok authorization plugins ..................... SKIPPED
[INFO] OpenGrok Suggester ................................. SKIPPED
[INFO] OpenGrok Web ....................................... SKIPPED
[INFO] OpenGrok tools ..................................... SKIPPED
[INFO] Distribution ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:20 min
[INFO] Finished at: 2019-02-02T18:39:24-08:00
[INFO] Final Memory: 51M/965M
[INFO] ------------------------------------------------------------------------
 
INFO: Failed to parse integer abcdef
java.lang.NumberFormatException: For input string: "abcdef"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at org.opengrok.indexer.web.PageConfig.getIntParam(PageConfig.java:517)
	at org.opengrok.indexer.web.PageConfigTest.testGetIntParam(PageConfigTest.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)

[ERROR] Tests run: 16, Failures: 7, Errors: 0, Skipped: 0, Time elapsed: 1.105 s <<< FAILURE! - in org.opengrok.indexer.web.PageConfigTest
[ERROR] testCheckSourceRootExistence4(org.opengrok.indexer.web.PageConfigTest)  Time elapsed: 0.01 s  <<< FAILURE!
java.lang.AssertionError: This should throw an exception when the file is not readable
	at org.opengrok.indexer.web.PageConfigTest.testCheckSourceRootExistence4(PageConfigTest.java:492)

[ERROR] testGetRevisionLocation(org.opengrok.indexer.web.PageConfigTest)  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AssertionError
	at org.opengrok.indexer.web.PageConfigTest.testGetRevisionLocation(PageConfigTest.java:284)

[ERROR] testGetLatestRevisionValid(org.opengrok.indexer.web.PageConfigTest)  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.AssertionError: expected:<aa35c258> but was:<null>
	at org.opengrok.indexer.web.PageConfigTest.testGetLatestRevisionValid(PageConfigTest.java:259)

[ERROR] testGetAnnotation(org.opengrok.indexer.web.PageConfigTest)  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AssertionError
	at org.opengrok.indexer.web.PageConfigTest.testGetAnnotation(PageConfigTest.java:396)

[ERROR] testGetRevisionLocationNullQuery(org.opengrok.indexer.web.PageConfigTest)  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AssertionError
	at org.opengrok.indexer.web.PageConfigTest.testGetRevisionLocationNullQuery(PageConfigTest.java:310)

[ERROR] canProcessHistory(org.opengrok.indexer.web.PageConfigTest)  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.AssertionError: expected:<> but was:<null>
	at org.opengrok.indexer.web.PageConfigTest.assertCanProcess(PageConfigTest.java:534)
	at org.opengrok.indexer.web.PageConfigTest.canProcessHistory(PageConfigTest.java:112)

[ERROR] canProcessXref(org.opengrok.indexer.web.PageConfigTest)  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.AssertionError: expected:<> but was:<null>
	at org.opengrok.indexer.web.PageConfigTest.assertCanProcess(PageConfigTest.java:534)
	at org.opengrok.indexer.web.PageConfigTest.canProcessXref(PageConfigTest.java:132)

OpenGrok trunk code from like a week ago.

(tried various versions of Java)
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

Maven home: /usr/share/maven
Java version: 1.8.0_201, vendor: Oracle Corporation
Java home: /opt/jdk1.8.0_201/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.82", arch: "amd64", family: "unix"

Apache Tomcat Version 9.0.14

Linux deb 4.9.82 #1 SMP Wed Feb 28 08:56:29 PST 2018 x86_64 GNU/Linux
"Debian GNU/Linux 9 (stretch)"

**Comment by tulinkry** [comment]
It's hard to say why. Can you run that test `PageConfigTest` in your IDE and possible debug some of the cases why it fails?

**Comment by tulinkry** [comment]
Do you have git installed? What is the version of your git?
