### ISSUE TITLE
org.opensolaris.opengrok.index.Indexer main SEVERE: Unexpected Exception

### ISSUE THREAD

**Issue by adambielecki** [oracle/opengrok#2668]
So I run command -
`java -jar lib/opengrok.jar -m 16 -i big5.js -i gbk.js -i *.zip -i *.dll -i *.pdb -i *.lib -W etc/configuration.xml -P -S -v -s src -d data -w productName -U localhost:8009`

Logging filehandler pattern: %h/java%u.log
java.net.SocketException: Connection reset
Continuing ...
java.net.SocketException: Broken pipe (Write failed)
Continuing ...
Feb 04, 2019 7:11:41 PM org.opensolaris.opengrok.index.Indexer main
SEVERE: Unexpected Exception
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.net.SocketInputStream.read(SocketInputStream.java:224)
        at org.opensolaris.opengrok.configuration.messages.Message.write(Message.java:298)
        at org.opensolaris.opengrok.index.Indexer.main(Indexer.java:246)

Exception: Connection reset

Using opengrok-1.1-rc18 and apache-tomcat-8.5.24.

Thank you for any help.

**Comment by ahornace** [comment]
Any update?

**Comment by ahornace** [comment]
Closing due to inactivity.
