### ISSUE TITLE
NullPointerException in SearchHelper.getSuggestions() due to missing searcher

### ISSUE THREAD

**Issue by u11** [oracle/opengrok#2700]
当查找一个不存在的Definition时会出现空指针异常，出现异常时的页面会混乱。问题可复现。
部署时的版本：https://github.com/oracle/opengrok/releases/download/1.2.2/opengrok-1.2.2.tar.gz
`java.lang.NullPointerException
	at org.opengrok.indexer.web.SearchHelper.getSuggestions(SearchHelper.java:474)
	at org.apache.jsp.search_jsp._jspService(search_jsp.java:731)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:99)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by u11** [comment]
![错误时的界面](https://user-images.githubusercontent.com/3949101/53402043-f0b4f680-39eb-11e9-89ea-0318bbe81f11.JPG)

**Comment by vladak** [comment]
Looks like `searcher` was null for some reason:

```java
468          for (String proj : name) {
469              Suggestion s = new Suggestion(proj);
470              try {
471                  if (!closeOnDestroy) {
472                      SuperIndexSearcher searcher = RuntimeEnvironment.getInstance().getIndexSearcher(proj);
473                      searcherList.add(searcher);
474                      ir = searcher.getIndexReader();
```

`getIndexSearcher()` returns `null` on failure. Are some preceding entries in the log that would highlight the problem ?

All in all, `SearchHelper.getSuggestions()` should deal with this possibility.

**Comment by vladak** [comment]
Is there a way how to reproduce this problem ?

**Comment by u11** [comment]
> Is there a way how to reproduce this problem ?

yes,you can input a long word ,such as 'ssssssssssssssssssssssssssssssssssssssssssssssssssss';

alos ,you may take a glance at the capture.

https://user-images.githubusercontent.com/3949101/53402043-f0b4f680-39eb-11e9-89ea-0318bbe81f11.JPG
