### ISSUE TITLE
ERROR: Complete output from command python setup.py egg_info: ERROR: warning: no previously-included files found matching 'pyproject.toml'

### ISSUE THREAD

**Issue by liucongvg** [oracle/opengrok#2810]
I run the following command:
python3 -m pip install opengrok-tools.tar.gz

but got following error:  
```
Processing ./opengrok-tools.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: warning: no previously-included files found matching 'pyproject.toml'
    
    Installed /tmp/pip-req-build-2gzxajet/.eggs/setuptools-41.0.1-py3.5.egg
    Searching for pytest-runner
    Reading https://pypi.python.org/simple/pytest-runner/
    Best match: pytest-runner 5.1
    Downloading https://files.pythonhosted.org/packages/d9/6d/4b41a74b31720e25abd4799be72d54811da4b4d0233e38b75864dcc1f7ad/pytest-runner-5.1.tar.gz#sha256=25a013c8d84f0ca60bb01bd11913a3bcab420f601f0f236de4423074af656e7a
    Processing pytest-runner-5.1.tar.gz
    Writing /tmp/easy_install-in6cnwe9/pytest-runner-5.1/setup.cfg
    Running pytest-runner-5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-in6cnwe9/pytest-runner-5.1/egg-dist-tmp-jiclpwl6
    zip_safe flag not set; analyzing archive contents...
    Moving pytest_runner-5.1-py3.5.egg to /tmp/pip-req-build-2gzxajet/.eggs
    
    Installed /tmp/pip-req-build-2gzxajet/.eggs/pytest_runner-5.1-py3.5.egg
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2237, in resolve
        return functools.reduce(getattr, self.attrs, module)
    AttributeError: module 'setuptools.dist' has no attribute 'check_specifier'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-2gzxajet/setup.py", line 70, in <module>
        'opengrok-sync=opengrok_tools.sync:main',
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2239, in resolve
        raise ImportError(str(exc))
    ImportError: module 'setuptools.dist' has no attribute 'check_specifier'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-2gzxajet/
```
what's wrong? how to solve this problem?

btw:
my opengrok version is 1.2.9

**Comment by vladak** [comment]
You need to upgrade `setuptools` first, i.e.:
```
python3 -m pip install --upgrade setuptools
```
Best done in virtual environment.
