### ISSUE TITLE
python tools - variable not initialized

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2823]
```
Command output in project 'xxxxxxx' contains errors:
  sudo -u tulinkry opengrok-mirror -c /Users/tulinkry/workspace/tulinkry/OpenGrok/local/mirror-config.yml -U http://localhost:8080 r3
    Traceback (most recent call last):
      File "/usr/local/bin/opengrok-mirror", line 10, in <module>
        sys.exit(main())
      File "/usr/local/lib/python3.7/site-packages/opengrok_tools/mirror.py", line 169, in main
        worker_args.append([x, logdir, args.loglevel,
    UnboundLocalError: local variable 'logdir' referenced before assignment
```

**Comment by vladak** [comment]
I see the same warning in IDEA.

**Comment by vladak** [comment]
Technically, this is not a problem since the `worker()` will only use `logdir` if `batch` is true and `__main__()` has this:
```python
    # Log messages to dedicated log file if running in batch mode.
    if args.batch:
        logdir = config.get(LOGDIR_PROPERTY)
        if not logdir:
            fatal("The {} property is required in batch mode".
                  format(LOGDIR_PROPERTY))
```
It should be sufficient to initialize `logdir` to `None`.
