### ISSUE TITLE
python tools - undefined property

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2824]
```
  sudo -u tulinkry opengrok-mirror -c /Users/tulinkry/workspace/tulinkry/OpenGrok/local/mirror-config.yml --incoming --batch -U http://localhost:8080 xxxx
    multiprocessing.pool.RemoteTraceback: 
    """
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
        result = (True, func(*args, **kwds))
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
        return list(map(*args))
      File "/usr/local/lib/python3.7/site-packages/opengrok_tools/mirror.py", line 70, in worker
        uri, source_root)
      File "/usr/local/lib/python3.7/site-packages/opengrok_tools/utils/mirror.py", line 253, in mirror_project
        if repo.incoming():
      File "/usr/local/lib/python3.7/site-packages/opengrok_tools/scm/git.py", line 61, in incoming
        self.logger.info(cmd.geterroutputstr())
      File "/usr/local/lib/python3.7/site-packages/opengrok_tools/utils/command.py", line 390, in geterroutputstr
        return "".join(self.err).strip()
    AttributeError: 'Command' object has no attribute 'err'
```

looks like python3.7 is a little violent like in #2823

**Comment by vladak** [comment]
I guess it might help to initialize `self.err` in the `__init__()` ?

**Comment by vladak** [comment]
It seems this only happens with the `--incoming` option.
