### ISSUE TITLE
NPE when deleting history for a project

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2837]
There can be a NPE when deleting history for a project which does not exist

```
27-Jun-2019 11:58:48.524 WARNING [http-nio-8080-exec-14] org.opengrok.web.api.error.GenericExceptionMapper.toResponse Exception while processing request
	java.lang.NullPointerException
		at org.opengrok.web.api.v1.controller.ProjectsController.deleteHistoryCache(ProjectsController.java:213)
		at org.opengrok.web.api.v1.controller.ProjectsController.deleteProjectData(ProjectsController.java:196)
		at org.opengrok.web.api.v1.controller.ProjectsController.deleteProject(ProjectsController.java:156)
		at sun.reflect.GeneratedMethodAccessor361.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)

```

I'm not sure if this can happen normally or if I just misused the flow.

**Comment by vladak** [comment]
NPE should not be thrown no matter what when dealing with API calls.

**Comment by vladak** [comment]
Is there a preceding `deleting history cache for project` line in the log ?

**Comment by vladak** [comment]
I am asking because `deleteHistoryCache()` calls `disableProject()` first and if the project cannot be found, it will throw `IllegalStateException` so will not get to referencing `HistoryGuru`.

That said, `deleteHistoryCache()` is a standalone API endpoint so needs to be made robust anyway.

**Comment by tulinkry** [comment]
I'm sorry but I do hocuspocus with opengrok lately so I don't have the logs anymore.

**Comment by tulinkry** [comment]
> That said, deleteHistoryCache() is a standalone API endpoint so needs to be made robust anyway for cases when the project exists but its history cache is not present for some reason.

I could see on my page that I had a bunch of projects (not repositories) listed however on the disc they actually have the .git repository. So there was something wrong going on and maybe this was the result.
