### ISSUE TITLE
SVN History does no work

### ISSUE THREAD

**Issue by elkin5** [oracle/opengrok#2856]
Istallation: Docker

Source: /opengrok/src
Svn Project: /opengrok/src/pro
Svn Checkout: svn checkout svn://serverSrc.project.com.co/project pro/

it is indexed but the svn history does no work.

**Comment by vladak** [comment]
What does the indexer log say ?

**Comment by elkin5** [comment]
what is the path of the indexer log?. Docker Installation

**Comment by vladak** [comment]
see https://github.com/oracle/opengrok/blob/master/docker/README.md#indexer-logs

**Comment by elkin5** [comment]
This is the most relevant information:

org.opengrok.indexer.history.SubversionRepository.getInfoDocument Failed to execute svn info for [/opengrok/src/SAO]. Repository disabled.
04-Jul-2019 19:56:33.544 SEVERE [invalidate-repos-1441] org.opengrok.indexer.util.Executor.exec Failed to read from process: /usr/bin/svn
        java.io.IOException: An error occurred while parsing the xml output
                at org.opengrok.indexer.history.SubversionHistoryParser.processStream(SubversionHistoryParser.java:194)
                at org.opengrok.indexer.util.Executor.exec(Executor.java:222)
                at org.opengrok.indexer.history.SubversionHistoryParser.parse(SubversionHistoryParser.java:165)
                at org.opengrok.indexer.history.SubversionRepository.getHistory(SubversionRepository.java:292)
                at org.opengrok.indexer.history.SubversionRepository.determineCurrentVersion(SubversionRepository.java:428)
                at org.opengrok.indexer.history.RepositoryFactory.getRepository(RepositoryFactory.java:171)
                at org.opengrok.indexer.history.RepositoryFactory.getRepository(RepositoryFactory.java:210)
                at org.opengrok.indexer.history.HistoryGuru$3.run(HistoryGuru.java:953)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
        Caused by: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 1; XML document structures must start and end within the same entity.
                at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
                at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
                at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
                at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
                at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
                at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.endEntity(XMLDocumentFragmentScannerImpl.java:899)
                at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.endEntity(XMLDocumentScannerImpl.java:559)
                at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.endEntity(XMLEntityManager.java:1398)
                at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1916)
                at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(XMLEntityScanner.java:1551)
                at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2821)
                at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
                at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
                at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
                at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
                at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
                at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
                at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
                at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
                at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
                at org.opengrok.indexer.history.SubversionHistoryParser.processStream(SubversionHistoryParser.java:192)
                ... 12 more

**Comment by vladak** [comment]
Okay, try running `svn info --xml` from withing the Docker container using https://github.com/oracle/opengrok/blob/master/docker/README.md#inspecting-the-container

This command needs to be run in the directory the repository is mapped to, i.e. `/opengrok/src/SAO`

**Comment by vladak** [comment]
Also, are there any preceding WARNING messages in the log ?

**Comment by elkin5** [comment]
thanks for the aswers, i solvet it.

**Comment by vladak** [comment]
What was the problem then ?

**Comment by elkin5** [comment]
The svn could not update.
i execute these commands:
- svn upgrade
- svn update
 Enter credentials for user

**Comment by vladak** [comment]
Okay, so the authentication was the problem. This will help to generate the history however the webapp needs to be able to execute svn commands too so this is not the final solution.

The Docker image is basically very simple appliance. Maybe not very suitable for this use case.
