### ISSUE TITLE
Authorization: cannot load decoder opengrok.auth.plugin.decoders.HttpBasicAuthHeaderDecoder

### ISSUE THREAD

**Issue by elkin5** [oracle/opengrok#2879]
25-Jul-2019 18:16:30.342 SEVERE [localhost-startStop-1] org.opengrok.indexer.authorization.AuthorizationPlugin.load Plugin "opengrok.auth.plugin.UserPlugin" has failed while loading with exception:
	java.lang.RuntimeException: cannot load decoder opengrok.auth.plugin.decoders.HttpBasicAuthHeaderDecoder
		at opengrok.auth.plugin.UserPlugin.load(UserPlugin.java:82)
		at org.opengrok.indexer.authorization.AuthorizationPlugin.load(AuthorizationPlugin.java:121)
		at org.opengrok.indexer.authorization.AuthorizationStack.load(AuthorizationStack.java:148)
		at org.opengrok.indexer.authorization.AuthorizationFramework.loadAllPlugins(AuthorizationFramework.java:293)
		at org.opengrok.indexer.authorization.AuthorizationFramework.afterReload(AuthorizationFramework.java:357)
		at org.opengrok.indexer.framework.PluginFramework.reload(PluginFramework.java:379)
		at org.opengrok.web.WebappListener.contextInitialized(WebappListener.java:86)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4770)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:744)
		at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1135)
		at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1869)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.ClassNotFoundException: Class "opengrok.auth.plugin.decoders.HttpBasicAuthHeaderDecoder" was not found
		at org.opengrok.indexer.framework.PluginClassLoader.loadClass(PluginClassLoader.java:287)
		at org.opengrok.indexer.framework.PluginClassLoader.loadClass(PluginClassLoader.java:201)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:264)
		at opengrok.auth.plugin.UserPlugin.getDecoder(UserPlugin.java:62)
		at opengrok.auth.plugin.UserPlugin.load(UserPlugin.java:79)

**Comment by elkin5** [comment]
i have followed the example (https://github.com/oracle/opengrok/wiki/Authorization-based-on-HTTP-Basic-Authentication), but i have not had expected results.
this error comes out when starting tomcat.
i don't know if this is the problem

there is not acces to any project

![Capture](https://user-images.githubusercontent.com/4118198/61916038-95d8ea00-af0c-11e9-931b-1693d1c221ae.PNG)

**Comment by vladak** [comment]
The decoder was renamed to `UserPrincipalDecoder` in the last moment before merging the pull request. Fixed.
