### ISSUE TITLE
use IndexVersion class in both webapp and indexer by default

### ISSUE THREAD

**Issue by hlayson** [oracle/opengrok#2909]
Just installed 1.3.1 and getting the following error when I try to any search
RHEL: 7.6
Tomcat 8.5.39
JAVA java-1.8.0-openjdk-1.8.0.222.b10-0.el7_6.x86_64

There was an error!
indexCreatedVersionMajor is in the future: 8

java.lang.IllegalArgumentException: indexCreatedVersionMajor is in the future: 8
	at org.apache.lucene.index.SegmentInfos.<init>(SegmentInfos.java:169)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:323)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:291)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:61)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:58)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:688)
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:81)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63)
	at org.apache.lucene.search.SearcherManager.<init>(SearcherManager.java:125)
	at org.opengrok.indexer.configuration.RuntimeEnvironment.getIndexSearcher(RuntimeEnvironment.java:1729)
	at org.opengrok.indexer.configuration.RuntimeEnvironment.getMultiReader(RuntimeEnvironment.java:1789)
	at org.opengrok.indexer.web.SearchHelper.prepareExec(SearchHelper.java:307)
	at org.apache.jsp.search_jsp._jspService(search_jsp.java:243)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:99)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vladak** [comment]
Seems like you are still runnig old webapp while the index was created with
new indexer.

Dne st 28. 8. 2019 21:52 uživatel hlayson <notifications@github.com> napsal:

**Comment by hlayson** [comment]
Thank you! That was it.

**Comment by vladak** [comment]
I think the `check` method from the `IndexVersion` class needs to be used every time webapp is started or indexer runs and there is index present.

**Comment by vladak** [comment]
The question is whether to cancel the whole process (web app startup / indexer startup) if for some reason only some subset of indexes (assuming projects are enable) has the old version. I'd be in favour of strictness here.
