### ISSUE TITLE
OutputThread needs to be careful with printing UTF-8 strings

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2926]
As mentioned in #2923 I have been struggling with hanging indexer (reindexing from scratch). Eventually I reproduced the problem and I found out that the `OutputThread` stopped running which lead to the Java process hanging on attempts to write to `stderr` as the pipe was full. The reason why the thread was not running was UTF-8 decoding issue:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/opengrok-upgrade/dist/bin/venv/lib/python3.4/site-packages/opengrok_tools/utils/command.py", line 180, in run
    print(line.rstrip())
UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 132: ordinal not in range(128)
```

This only happens if the `Command` is set with `doprint=True` (hence PR #2924)

**Comment by vladak** [comment]
Probably the main problem is that the `opengrok-indexer` script is run without the appropriate environment variables (`LANG="en_US.UTF-8" LC_ALL="en_US.UTF-8"`).

The `OutputThread` should be more resilient, though.
