### ISSUE TITLE
Opengrok not able to index Java files due to stricter Universal ctags handling of kinds

### ISSUE THREAD

**Issue by ankitjhil** [oracle/opengrok#2930]
I am getting a strange issue.. While trying to index my project, opengrok seems to throw errors for all java files. It looks like to be something related to ctags, but i am not getting any clue.
Following are the versions:

**Ctags:**
Universal Ctags 0.0.0(126781c), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Sep 15 2019, 23:38:09
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +case-insensitive-filenames, +packcc

**OpenGrok: 1.3.1**

Following are the error logs:
`
2019-09-15 23:41:09.207+0530 FINEST t89 AnalyzerGuru.find: /aoaprod/app/common/service/facade/src/main/java/com/alipay/ap/aoaprod/service/facade/result/AOARefundReceiptProcessResult.java: chosen by suffix: JavaAnalyzerFactory

2019-09-15 23:41:09.208+0530 FINE t89 DefaultIndexChangedListener.fileAdd: Add: /aoaprod/app/common/service/facade/src/main/java/com/alipay/ap/aoaprod/service/facade/result/AOARefundReceiptProcessResult.java (JavaAnalyzer)

2019-09-15 23:41:09.219+0530 FINE t89 Ctags.initialize: Executing ctags command [/usr/local/bin/ctags --c-kinds=+l --langmap=clojure:+.cljs --langmap=clojure:+.cljx --java-kinds=+l --sql-kinds=+l --Fortran-kinds=+L --C++-kinds=+l --file-scope=yes -u --filter=yes --filter-terminator=__ctags_done_with_file__
 --fields=-anf+iKnS --excmd=pattern --langmap=sh:+.kshlib --langmap=sql:+.plb --langmap=sql:+.pls --langmap=sql:+.pld --langmap=sql:+.pks --langmap=sql:+.pkb --langmap=sql:+.pck --langmap=javascript:+.ts --langdef=scala --langmap=scala:+.scala --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*(private|protected)?[[:space:]]*class[[:space:]]+([a-zA-Z0-9_]+)/\4/c,classes/ --regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy)[[:space:]]*)*(private|protected)?[[:space:]]*object[[:space:]]+([a-zA-Z0-9_]+)/\4/o,objects/ --regex-scala=/^[[:space:]]*((abstract|final|seale........

2019-09-15 23:41:09.273+0530 INFO t89 IndexDatabase.addFile: Skipped file '/aoaprod/app/common/service/facade/src/main/java/com/alipay/ap/aoaprod/service/facade/result/AOARefundReceiptProcessResult.java' because the analyzer didn't understand it.

2019-09-15 23:41:09.274+0530 FINE t89 IndexDatabase.addFile: Exception from analyzer org.opengrok.indexer.analysis.java.JavaAnalyzer
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at org.opengrok.indexer.analysis.Ctags.doCtags(Ctags.java:389)
        at org.opengrok.indexer.analysis.plain.PlainAnalyzer.analyze(PlainAnalyzer.java:109)
        at org.opengrok.indexer.analysis.AnalyzerGuru.populateDocument(AnalyzerGuru.java:585)
        at org.opengrok.indexer.index.IndexDatabase.addFile(IndexDatabase.java:752)
        at org.opengrok.indexer.index.IndexDatabase.lambda$null$1(IndexDatabase.java:1191)
        at java.util.stream.Collectors.lambda$groupingByConcurrent$51(Collectors.java:1070)
        at java.util.stream.ReferencePipeline.lambda$collect$1(ReferencePipeline.java:496)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

2019-09-15 23:41:09.275+0530 FINE t89 BoundedBlockingObjectPool.handleInvalidReturn: createNew() to handle invalid class org.opengrok.indexer.analysis.Ctags

23:11:43 WARNING: File '/aoaprod/app/common/service/facade/src/main/java/com/alipay/ap/aoaprod/service/facade/result/AOARefundReceiptProcessResult.java' interrupted--tagLine == null
23:11:43 WARNING: Error from ctags: ctags: Non-alphanumeric char is used in kind name: 'case classes' in "--regex-scala" option
23:11:43 WARNING: ctags: Unexpected end of file!
23:11:43 WARNING: ctags exited with code: 1
`

Infact, all my java files are not getting indexed. Please help.

**Comment by idodeclare** [comment]
Oh no. A [PR just merged into universal ctags](https://github.com/universal-ctags/ctags/pull/1737) makes strict the allowed format of a "kind name": "The first character of the name must be alphabetic, and the rest [of the] characters must be alphanumeric (`[a-zA-Z][a-zA-Z0-9]*`)."

As that error message reads, OpenGrok's Scala configuration for the "kind" `"case classes"` is breaking with the new strictness. In quickly scanning through code, I see OpenGrok's Kotlin and Clojure ctags configurations also have invalid "kind names" according to the new ctags enforcement.

At the moment, [126781c](https://github.com/universal-ctags/ctags/commit/126781c6e1678e5ef3096fd9da7d2bf7f9dce3e4) is the latest commit to u-ctags. One workaround would be to roll back your u-ctags to [6adbc59](https://github.com/universal-ctags/ctags/commit/6adbc5922f60a0f7490d1c83c0b8cdbd440d7450) pending an update from OpenGrok.

**Comment by ankitjhil** [comment]
> Oh no. A [PR just merged into universal ctags](https://github.com/universal-ctags/ctags/pull/1737) makes strict the allowed format of a "kind name": "The first character of the name must be alphabetic, and the rest [of the] characters must be alphanumeric (`[a-zA-Z][a-zA-Z0-9]*`)."
> 
> As that error message reads, OpenGrok's Scala configuration for the "kind" `"case classes"` is breaking with the new strictness. In quickly scanning through code, I see OpenGrok's Kotlin and Clojure ctags configurations also have invalid "kind names" according to the new ctags enforcement.
> 
> At the moment, [126781c](https://github.com/universal-ctags/ctags/commit/126781c6e1678e5ef3096fd9da7d2bf7f9dce3e4) is the latest commit to u-ctags. One workaround would be to roll back your u-ctags to [6adbc59](https://github.com/universal-ctags/ctags/commit/6adbc5922f60a0f7490d1c83c0b8cdbd440d7450) pending an update from OpenGrok.

Can you tell how this can be done? How to install specific ctag version using homebrew?

**Comment by idodeclare** [comment]
U-ctags is a HEAD-only formula, so i don’t think it could be done with Homebrew.

Building from u-ctags source is straight-forward in my experience. You would clone u-ctags, check out the historical commit (from above), and then follow the Build Manually steps (e.g. on http://docs.ctags.io/en/latest/osx.html). You wouldn’t necessarily have to uninstall Homebrew u-ctags; you would just run OpenGrok specifying your built version with `—ctags`.

**Comment by hwbest** [comment]
Hi idodeclare,

I got the same issue, and thanks for your suggestion:
At the moment, 126781c is the latest commit to u-ctags. One workaround would be to roll back your u-ctags to 6adbc59 pending an update from OpenGrok.

Could you please share the plan, when Opengrok can be updated to compatible with latest u-tags?

Thanks
