### ISSUE TITLE
Web application downtime at the end of the reindex

### ISSUE THREAD

**Issue by marceloavilaoliveira** [oracle/opengrok#2932]
- OpenGrok 1.2.25
- OpenJDK 1.8.0_212
- Ubuntu 18.04
- Tomcat
- Chrome & Firefox

Every night I run the reindexer using the opengrok.jar, everything is working fine but at the end, apparently when the indexer automatically attempts to upload newly generated configuration, the web application stays for about 5 minutes inaccessible.

During this downtime I get the following in the /logs/opengrok0.0.log:

```
2019-09-19T04:47:36 ... PUT /source/api/v1/configuration?reindex=true ...
<web application inaccessible>
2019-09-19T04:53:23 Configuration update routine done, check log output for errors.
```

At the tomcat/logs/catalina.out I get the following:

```
19-Sep-2019 04:53:21.260 INFO [http-nio-8090-exec-5] org.opengrok.indexer.util.Statistics.report done invalidating 111 repositories (took 0:05:44)
```

This issue happens all the times the reindex is executed.

**Comment by vladak** [comment]
Looks like the 5 minutes spent in `invalidateRepositories()` correlates with the 5 minutes of down time. `setConfiguration()` holds `configLock` but only for a short while.

**Comment by vladak** [comment]
Inaccessible means the request just wait or do you get an error back ?

**Comment by vladak** [comment]
Also, what sort of request ?

**Comment by vladak** [comment]
I modified `setConfiguration()` to sleep inside the body (`TimeUnit.SECONDS.sleep(300);`) and then uploaded the config:
```
curl -X PUT -H 'Content-Type: application/xml' -d @/var/opengrok/etc/configuration.xml 'http://localhost:8080/source/api/v1/configuration?reindex=true'
```
The related thread looks like so:
```
"http-nio-8080-exec-6@3371" daemon prio=5 tid=0x2e nid=NA sleeping
  java.lang.Thread.State: TIMED_WAITING
	 blocks http-nio-8080-exec-5@3370
	 blocks http-nio-8080-exec-3@3368
	  at java.lang.Thread.sleep(Thread.java:-1)
	  at java.lang.Thread.sleep(Thread.java:340)
	  at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	  at org.opengrok.indexer.configuration.RuntimeEnvironment.setConfiguration(RuntimeEnvironment.java:1555)
	  - locked <0xb3d> (a org.opengrok.indexer.configuration.RuntimeEnvironment)
	  at org.opengrok.indexer.configuration.RuntimeEnvironment.setConfiguration(RuntimeEnvironment.java:1533)
	  at org.opengrok.indexer.configuration.RuntimeEnvironment.applyConfig(RuntimeEnvironment.java:1665)
	  at org.opengrok.indexer.configuration.RuntimeEnvironment.applyConfig(RuntimeEnvironment.java:1652)
	  at org.opengrok.web.api.v1.controller.ConfigurationController.set(ConfigurationController.java:59)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	  at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$$Lambda$241.1855609645.invoke(Unknown Source:-1)
	  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	  at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159)
	  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	  at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	  at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	  at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	  at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	  at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	  at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	  at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	  at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	  at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	  at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	  at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
	  at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
	  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
	  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	  at org.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:59)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	  at org.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:60)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	  at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	  - locked <0x280d> (a org.apache.tomcat.util.net.NioChannel)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	  at java.lang.Thread.run(Thread.java:748)
```
where line 1555 in RuntimeEnvironment.java was the added sleep.

and I accessed the main page which resulted in:
```
"http-nio-8080-exec-5@3370" daemon prio=5 tid=0x2d nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for http-nio-8080-exec-6@3371 to release lock on <merged>(a org.opengrok.indexer.configuration.RuntimeEnvironment)
	  at org.opengrok.indexer.configuration.RuntimeEnvironment.getAuthorizationFramework(RuntimeEnvironment.java:1604)
	  at org.opengrok.indexer.web.PageConfig.<init>(PageConfig.java:1532)
	  at org.opengrok.indexer.web.PageConfig.get(PageConfig.java:1525)
	  at org.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:64)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	  at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	  - locked <merged>(a org.apache.tomcat.util.net.NioChannel)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	  at java.lang.Thread.run(Thread.java:748)
```

**Comment by vladak** [comment]
This seems to be caused by `RuntimeEnvironment:setConfiguration()` and `RuntimeEnvironment:getAuthorizationFramework()` to be defined as `synchronized`. This probably results in both trying to grab the class lock rather than object level lock.

**Comment by vladak** [comment]
The authorization framework locking was added in PR #1616 to protect the object from getter/setter races I believe. It can be replaced by R/W lock.

**Comment by marceloavilaoliveira** [comment]
Release 1.3.3 resolved this issue. Thanks!
