### ISSUE TITLE
Not possible to show diff between revisions

### ISSUE THREAD

**Issue by Z4rc** [oracle/opengrok#2950]
**Describe the bug**
I use opengrok for a git repository. When I try to compare two revisions of a file, I get the following error message: "Error: Unable to get revision XXX for file: XXX". I get this message every time I try to compare revisions. History option is enabled.

I use opengrok 1.3.2 and tomcat 9.0.2.

**To Reproduce**

- Select file
- Click "History"
- Select two Revisions and click "Compare"

**Expected behavior**
Show diff between revisions.

**Screenshots**
![image](https://user-images.githubusercontent.com/10116005/66295469-b3063d80-e8eb-11e9-8a8b-5cafe467c473.png)

**Comment by vladak** [comment]
Does this happen for other files in the same repo ? Does this happen for all revisions of the `/tools/setup` file or just for some ?

Anything interesting in `catalina.out` log file ?

**Comment by vladak** [comment]
also see https://github.com/oracle/opengrok/wiki/Debugging#web-application

**Comment by Z4rc** [comment]
Yes, it appears to alle files in the same repo and for all revisions.
Error message in catalina.out:
```
07-Oct-2019 12:21:07.233 WARNING [http-nio-8090-exec-46] org.opengrok.indexer.util.Executor.exec Non-zero exit status 128 from command [git, show, 691a170c:../../../tools/setup] in directory /gitworkspace/grok/source/tools: fatal: '../../../tools/setup' is outside repository
07-Oct-2019 12:21:07.234 SEVERE [http-nio-8090-exec-46] org.opengrok.indexer.history.GitRepository.getHistoryGet Failed to get original revision: /gitworkspace/grok/source/tools/setup (revision 691a170c)
 java.io.IOException: Invalid file path string: /gitworkspace/tools/setup
	at org.opengrok.indexer.history.GitRepository.findOriginalName(GitRepository.java:312)
	at org.opengrok.indexer.history.GitRepository.getHistoryGet(GitRepository.java:256)
	at org.opengrok.indexer.history.Repository.getHistoryGet(Repository.java:228)
	at org.opengrok.indexer.history.HistoryGuru.getRevision(HistoryGuru.java:300)
	at org.opengrok.indexer.web.PageConfig.getDiffData(PageConfig.java:260)
	at org.apache.jsp.diff_jsp._jspService(diff_jsp.java:220)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:444)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:619)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:501)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```
I am using symlinks in the grok source folder:
```
$ ls -l source
tools -> /gitworkspace/tools/
```

**Comment by vladak** [comment]
As you discovered from the logs the symlink is the cause. You can use the `--symlink` option of the Indexer. Also see #2920.

**Comment by Z4rc** [comment]
I thought --symlink option is only need if the symlink is not directly under the source dir.
```
  --symlink /path/to/symlink
	Allow this symlink to be followed. Option may be repeated.
	By default only symlinks directly under source root directory
	are allowed.

```
But it also does not work with if I call the indexer with:
```
  --symlink tools
```

**Comment by vladak** [comment]
That probably means you will have to wait for the above mentioned fix.
