### ISSUE TITLE
XrefTest.java tests fail in Travis Windows environment

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3018]
In Travis Windows environment all `*XrefTest.java` tests fail, e.g.:
```
AdaXrefTest.sampleTest:38->XrefTestBase.writeAndCompare:62->XrefTestBase.writeAndCompare:90 org.opengrok.indexer.analysis.ada.AdaAnalyzerFactory xref--should have no diffs
```
with:
```
[INFO] Running org.opengrok.indexer.analysis.ada.AdaXrefTest
@@ -1,50 +1,50 @@
- <!DOCTYPE html>

- <html lang="en">

- <head>

- <meta charset="UTF-8">

- <title>sampleFile - OpenGrok cross reference for /sampleFile</title></head><body>

- <a class="l" name="1" href="#1">1</a><span class="c">--</span>

- <a class="l" name="2" href="#2">2</a><span class="c">-- CDDL HEADER START</span>

- <a class="l" name="3" href="#3">3</a><span class="c">--</span>

- <a class="l" name="4" href="#4">4</a><span class="c">-- The contents of this file are subject to the terms of the</span>

- <a class="l" name="5" href="#5">5</a><span class="c">-- Common Development and Distribution License (the &quot;License&quot;).</span>

- <a class="l" name="6" href="#6">6</a><span class="c">-- You may not use this file except in compliance with the License.</span>

- <a class="l" name="7" href="#7">7</a><span class="c">--</span>

- <a class="l" name="8" href="#8">8</a><span class="c">-- See LICENSE.txt included in this distribution for the specific</span>

- <a class="l" name="9" href="#9">9</a><span class="c">-- language governing permissions and limitations under the License.</span>

- <a class="hl" name="10" href="#10">10</a><span class="c">--</span>

- <a class="l" name="11" href="#11">11</a><span class="c">-- When distributing Covered Code, include this CDDL HEADER in each</span>

- <a class="l" name="12" href="#12">12</a><span class="c">-- file and include the License file at LICENSE.txt.</span>

- <a class="l" name="13" href="#13">13</a><span class="c">-- If applicable, add the following below this CDDL HEADER, with the</span>

- <a class="l" name="14" href="#14">14</a><span class="c">-- fields enclosed by brackets &quot;[]&quot; replaced with your own identifying</span>

- <a class="l" name="15" href="#15">15</a><span class="c">-- information: Portions Copyright [yyyy] [name of copyright owner]</span>

- <a class="l" name="16" href="#16">16</a><span class="c">--</span>

- <a class="l" name="17" href="#17">17</a><span class="c">-- CDDL HEADER END</span>

- <a class="l" name="18" href="#18">18</a><span class="c">--</span>

- <a class="l" name="19" href="#19">19</a>

- <a class="hl" name="20" href="#20">20</a><span class="c">--</span>

- <a class="l" name="21" href="#21">21</a><span class="c">-- Copyright (c) 2017, Chris Fraire &lt;cfraire@me.com&gt;.</span>

- <a class="l" name="22" href="#22">22</a><span class="c">--</span>

- <a class="l" name="23" href="#23">23</a>

- <a class="l" name="24" href="#24">24</a><b>with</b> <b>Ada</b>.<b>Text_IO</b>; <b>use</b> <b>Ada</b>.<b>Text_IO</b>;

- <a class="l" name="25" href="#25">25</a><b>procedure</b> <a href="/source/s?defs=Hello" class="intelliWindow-symbol" data-definition-place="undefined-in-file">Hello</a> <b>is</b>

- <a class="l" name="26" href="#26">26</a><b>begin</b>

- <a class="l" name="27" href="#27">27</a>	<b>Put_Line</b>(<span class="s">&quot;Hello, world!&quot;</span>);

- <a class="l" name="28" href="#28">28</a>	<b>Put_Line</b>(<span class="s">&quot;&quot;&quot;</span>

- <a class="l" name="29" href="#29">29</a><span class="s">		Hello?&quot;&quot;&quot;</span>);

- <a class="hl" name="30" href="#30">30</a>	<b>Put_Line</b>(<span class="s">&apos;?&apos;</span>);

- <a class="l" name="31" href="#31">31</a>	<b>Put_Line</b>(<span class="s">&apos;</span>

- <a class="l" name="32" href="#32">32</a><span class="s">&apos;</span>);

- <a class="l" name="33" href="#33">33</a>	<b>Put</b>(<span class="n">0</span>);

- <a class="l" name="34" href="#34">34</a>	<b>Put</b>(<span class="n">12</span>);

- <a class="l" name="35" href="#35">35</a>	<b>Put</b>(<span class="n">123_456</span>);

- <a class="l" name="36" href="#36">36</a>	<b>Put</b>(<span class="n">3.14159_26</span>);

- <a class="l" name="37" href="#37">37</a>	<b>Put</b>(<span class="n">2#1111_1111#</span>);

- <a class="l" name="38" href="#38">38</a>	<b>Put</b>(<span class="n">16#E#E1</span>);

- <a class="l" name="39" href="#39">39</a>	<b>Put</b>(<span class="n">16#F.FF#E+2</span>);

- <a class="hl" name="40" href="#40">40</a>	<b>Put_Line</b>();

- <a class="l" name="41" href="#41">41</a>	<b>Put_Line</b>(<span class="s">&quot;Archimedes said &quot;&quot;&#917;&#973;&#961;&#951;&#954;&#945;&quot;&quot;&quot;</span>);

- <a class="l" name="42" href="#42">42</a><b>end</b> <a href="/source/s?defs=Hello" class="intelliWindow-symbol" data-definition-place="undefined-in-file">Hello</a>;

- <a class="l" name="43" href="#43">43</a>

- <a class="l" name="44" href="#44">44</a><span class="c">-- Test a URL that is not matched fully by a rule using just {URIChar} and</span>

- <a class="l" name="45" href="#45">45</a><span class="c">-- {FnameChar}:</span>

+ <!DOCTYPE html>
+ <html lang="en">
+ <head>
+ <meta charset="UTF-8">
+ <title>sampleFile - OpenGrok cross reference for /sampleFile</title></head><body>
+ <a class="l" name="1" href="#1">1</a><span class="c">--</span>
+ <a class="l" name="2" href="#2">2</a><span class="c">-- CDDL HEADER START</span>
+ <a class="l" name="3" href="#3">3</a><span class="c">--</span>
+ <a class="l" name="4" href="#4">4</a><span class="c">-- The contents of this file are subject to the terms of the</span>
+ <a class="l" name="5" href="#5">5</a><span class="c">-- Common Development and Distribution License (the &quot;License&quot;).</span>
+ <a class="l" name="6" href="#6">6</a><span class="c">-- You may not use this file except in compliance with the License.</span>
+ <a class="l" name="7" href="#7">7</a><span class="c">--</span>
+ <a class="l" name="8" href="#8">8</a><span class="c">-- See LICENSE.txt included in this distribution for the specific</span>
+ <a class="l" name="9" href="#9">9</a><span class="c">-- language governing permissions and limitations under the License.</span>
+ <a class="hl" name="10" href="#10">10</a><span class="c">--</span>
+ <a class="l" name="11" href="#11">11</a><span class="c">-- When distributing Covered Code, include this CDDL HEADER in each</span>
+ <a class="l" name="12" href="#12">12</a><span class="c">-- file and include the License file at LICENSE.txt.</span>
+ <a class="l" name="13" href="#13">13</a><span class="c">-- If applicable, add the following below this CDDL HEADER, with the</span>
+ <a class="l" name="14" href="#14">14</a><span class="c">-- fields enclosed by brackets &quot;[]&quot; replaced with your own identifying</span>
+ <a class="l" name="15" href="#15">15</a><span class="c">-- information: Portions Copyright [yyyy] [name of copyright owner]</span>
+ <a class="l" name="16" href="#16">16</a><span class="c">--</span>
+ <a class="l" name="17" href="#17">17</a><span class="c">-- CDDL HEADER END</span>
+ <a class="l" name="18" href="#18">18</a><span class="c">--</span>
+ <a class="l" name="19" href="#19">19</a>
+ <a class="hl" name="20" href="#20">20</a><span class="c">--</span>
+ <a class="l" name="21" href="#21">21</a><span class="c">-- Copyright (c) 2017, Chris Fraire &lt;cfraire@me.com&gt;.</span>
+ <a class="l" name="22" href="#22">22</a><span class="c">--</span>
+ <a class="l" name="23" href="#23">23</a>
+ <a class="l" name="24" href="#24">24</a><b>with</b> <b>Ada</b>.<b>Text_IO</b>; <b>use</b> <b>Ada</b>.<b>Text_IO</b>;
+ <a class="l" name="25" href="#25">25</a><b>procedure</b> <a href="/source/s?defs=Hello" class="intelliWindow-symbol" data-definition-place="undefined-in-file">Hello</a> <b>is</b>
+ <a class="l" name="26" href="#26">26</a><b>begin</b>
+ <a class="l" name="27" href="#27">27</a>	<b>Put_Line</b>(<span class="s">&quot;Hello, world!&quot;</span>);
+ <a class="l" name="28" href="#28">28</a>	<b>Put_Line</b>(<span class="s">&quot;&quot;&quot;</span>
+ <a class="l" name="29" href="#29">29</a><span class="s">		Hello?&quot;&quot;&quot;</span>);
+ <a class="hl" name="30" href="#30">30</a>	<b>Put_Line</b>(<span class="s">&apos;?&apos;</span>);
+ <a class="l" name="31" href="#31">31</a>	<b>Put_Line</b>(&apos;
+ <a class="l" name="32" href="#32">32</a>&apos;);
+ <a class="l" name="33" href="#33">33</a>	<b>Put</b>(<span class="n">0</span>);
+ <a class="l" name="34" href="#34">34</a>	<b>Put</b>(<span class="n">12</span>);
+ <a class="l" name="35" href="#35">35</a>	<b>Put</b>(<span class="n">123_456</span>);
+ <a class="l" name="36" href="#36">36</a>	<b>Put</b>(<span class="n">3.14159_26</span>);
+ <a class="l" name="37" href="#37">37</a>	<b>Put</b>(<span class="n">2#1111_1111#</span>);
+ <a class="l" name="38" href="#38">38</a>	<b>Put</b>(<span class="n">16#E#E1</span>);
+ <a class="l" name="39" href="#39">39</a>	<b>Put</b>(<span class="n">16#F.FF#E+2</span>);
+ <a class="hl" name="40" href="#40">40</a>	<b>Put_Line</b>();
+ <a class="l" name="41" href="#41">41</a>	<b>Put_Line</b>(<span class="s">&quot;Archimedes said &quot;&quot;&#917;&#973;&#961;&#951;&#954;&#945;&quot;&quot;&quot;</span>);
+ <a class="l" name="42" href="#42">42</a><b>end</b> <a href="/source/s?defs=Hello" class="intelliWindow-symbol" data-definition-place="undefined-in-file">Hello</a>;
+ <a class="l" name="43" href="#43">43</a>
+ <a class="l" name="44" href="#44">44</a><span class="c">-- Test a URL that is not matched fully by a rule using just {URIChar} and</span>
+ <a class="l" name="45" href="#45">45</a><span class="c">-- {FnameChar}:</span>
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.399 s <<< FAILURE! - in org.opengrok.indexer.analysis.ada.AdaXrefTest
[ERROR] sampleTest  Time elapsed: 0.397 s  <<< FAILURE!
java.lang.AssertionError: org.opengrok.indexer.analysis.ada.AdaAnalyzerFactory xref--should have no diffs
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.opengrok.indexer.util.CustomAssertions.assertLinesEqual(CustomAssertions.java:101)
	at org.opengrok.indexer.analysis.XrefTestBase.writeAndCompare(XrefTestBase.java:90)
	at org.opengrok.indexer.analysis.XrefTestBase.writeAndCompare(XrefTestBase.java:62)
	at org.opengrok.indexer.analysis.ada.AdaXrefTest.sampleTest(AdaXrefTest.java:38)
```
which is caused by extra newline - the generated HTML file has extra new line for each line. This does not happen in AppVeyor builds so it is likely tied to the Travis env, perhaps GitBash plays a role there.

**Comment by vladak** [comment]
ref https://travis-ci.org/vladak/OpenGrok/jobs/636224410?utm_medium=notification&utm_source=github_status

**Comment by ginoaugustine** [comment]
@vladak Can we close this since we moved away from Travis build
