### ISSUE TITLE
HistoryGuruTest.testGetRevision fails in Travis Windows environment

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3019]
The `HistoryGuruTest.testGetRevision` fails in Travis Windows env due to:
```
Jan 13, 2020 8:17:15 AM org.opengrok.indexer.util.Executor exec

WARNING: Non-zero exit status -1 from command [blame Makefile] in directory C:\Users\travis\AppData\Local\Temp\source975669849041833016\rcs_test

[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 16.187 s <<< FAILURE! - in org.opengrok.indexer.history.HistoryGuruTest

[ERROR] testGetRevision  Time elapsed: 0.449 s  <<< FAILURE!

java.lang.AssertionError: Failed to get revision 1.1 of C:\Users\travis\AppData\Local\Temp\source975669849041833016\razor\Razor-Simple\SimpleCProgram\main.c

	at org.junit.Assert.fail(Assert.java:88)

	at org.junit.Assert.assertTrue(Assert.java:41)

	at org.junit.Assert.assertNotNull(Assert.java:712)

	at org.opengrok.indexer.history.HistoryGuruTest.testGetRevision(HistoryGuruTest.java:110)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	at org.junit.rules.RunRules.evaluate(RunRules.java:20)

	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)

	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)

	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)

	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:40)

	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)

	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)

	at java.util.Iterator.forEachRemaining(Iterator.java:116)

	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)

	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)

	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)

	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)

	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)

	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)

	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)

	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:71)

	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)

	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)

	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)

	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)

	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)

	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)

	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:120)

	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)

	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)

	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)

	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

Jan 13, 2020 8:17:22 AM org.opengrok.indexer.history.RazorRepository getHistoryGet

SEVERE: getHistoryGet( C:\Users\travis\AppData\Local\Temp\source975669849041833016\razor\Razor-Simple\SimpleCProgram, main.c, 1.1)

java.io.IOException: Invalid RCS file format: 1.1:line::java.lang.NumberFormatException

	at org.opengrok.indexer.history.RCSRepository.wrapInIOException(RCSRepository.java:120)

	at org.opengrok.indexer.history.RCSget.<init>(RCSget.java:70)

	at org.opengrok.indexer.history.RazorRepository.getHistoryGet(RazorRepository.java:245)

	at org.opengrok.indexer.history.Repository.getHistoryGet(Repository.java:228)

	at org.opengrok.indexer.history.HistoryGuru.getRevision(HistoryGuru.java:302)

	at org.opengrok.indexer.history.HistoryGuruTest.testGetRevision(HistoryGuruTest.java:108)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	at org.junit.rules.RunRules.evaluate(RunRules.java:20)

	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)

	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)

	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)

	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:40)

	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)

	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)

	at java.util.Iterator.forEachRemaining(Iterator.java:116)

	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)

	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)

	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)

	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)

	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)

	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)

	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)

	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:71)

	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)

	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)

	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)

	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)

	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)

	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)

	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:120)

	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)

	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)

	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)

	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

Caused by: org.suigeneris.jrcs.rcs.InvalidFileFormatException: 1.1:line::java.lang.NumberFormatException

	at org.suigeneris.jrcs.rcs.impl.Node.patch(Node.java:580)

	at org.suigeneris.jrcs.rcs.impl.Path.patch(Path.java:178)

	at org.suigeneris.jrcs.rcs.Archive.getRevision(Archive.java:1208)

	at org.suigeneris.jrcs.rcs.Archive.getRevision(Archive.java:1168)

	at org.suigeneris.jrcs.rcs.Archive.getRevision(Archive.java:1092)

	at org.opengrok.indexer.history.RCSget.<init>(RCSget.java:58)

	... 50 more

"

	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)

	at java.lang.Integer.parseInt(Integer.java:580)

	at java.lang.Integer.parseInt(Integer.java:615)

	at org.suigeneris.jrcs.rcs.impl.Node.patch(Node.java:576)

	... 55 more
```

**Comment by vladak** [comment]
ref https://travis-ci.org/vladak/OpenGrok/jobs/636224410?utm_medium=notification&utm_source=github_status

**Comment by vladak** [comment]
no Travis anymore
