### ISSUE TITLE
Indexing failed on updated image

### ISSUE THREAD

**Issue by Ymoise** [oracle/opengrok#3068]
Used to run the indexer using a VERY old docker image of opengrok (about 14 months old), and it indexed fine, it just took forever even after only one file was altered, so I pulled the latest image, created a new container, cloned my repo into it, ran the indexer and then I got a thousand and one issues. It started with:

Mar 09, 2020 6:11:08 AM org.opengrok.indexer.analysis.Ctags readTags
WARNING: CTags parsing problem:
java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:336)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at org.opengrok.indexer.analysis.Ctags.readTags(Ctags.java:547)
        at org.opengrok.indexer.analysis.Ctags.lambda$doCtags$2(Ctags.java:455)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Then continued with:

WARNING: ERROR addFile(): **Path to a file I can't put on here, because it's company data**
java.lang.ArrayIndexOutOfBoundsException: -65536
        at org.apache.lucene.index.TermsHashPerField.writeByte(TermsHashPerField.java:198)
        at org.apache.lucene.index.TermsHashPerField.writeVInt(TermsHashPerField.java:224)
        at org.apache.lucene.index.FreqProxTermsWriterPerField.writeOffsets(FreqProxTermsWriterPerField.java:101)
        at org.apache.lucene.index.FreqProxTermsWriterPerField.addTerm(FreqProxTermsWriterPerField.java:186)
        at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:185)
        at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:862)
        at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:442)
        at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:406)
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:250)
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:495)
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1594)
        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1213)
        at org.opengrok.indexer.index.IndexDatabase.addFile(IndexDatabase.java:774)
        at org.opengrok.indexer.index.IndexDatabase.lambda$indexParallel$2(IndexDatabase.java:1271)
        at java.util.stream.Collectors.lambda$groupingByConcurrent$51(Collectors.java:1070)
        at java.util.stream.ReferencePipeline.lambda$collect$1(ReferencePipeline.java:496)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Then I got:

Mar 09, 2020 7:04:28 AM org.opengrok.indexer.index.IndexDatabase lambda$indexParallel$2
SEVERE: ERROR addFile(): **Same thing, different file**
org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
        at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:681)
        at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:695)
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1591)
        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1213)
        at org.opengrok.indexer.index.IndexDatabase.addFile(IndexDatabase.java:774)
        at org.opengrok.indexer.index.IndexDatabase.lambda$indexParallel$2(IndexDatabase.java:1271)
        at java.util.stream.Collectors.lambda$groupingByConcurrent$51(Collectors.java:1070)
        at java.util.stream.ReferencePipeline.lambda$collect$1(ReferencePipeline.java:496)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -65536
        at org.apache.lucene.index.TermsHashPerField.writeByte(TermsHashPerField.java:198)
        at org.apache.lucene.index.TermsHashPerField.writeVInt(TermsHashPerField.java:224)
        at org.apache.lucene.index.FreqProxTermsWriterPerField.writeOffsets(FreqProxTermsWriterPerField.java:101)
        at org.apache.lucene.index.FreqProxTermsWriterPerField.addTerm(FreqProxTermsWriterPerField.java:186)
        at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:185)
        at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:862)
        at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:442)
        at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:406)
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:250)
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:495)
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1594)
        ... 15 more

And finally:

Mar 09, 2020 7:20:04 AM org.opengrok.indexer.index.IndexDatabase indexParallel
WARNING: 12597 failures (5.9%) while parallel-indexing
Mar 09, 2020 7:20:04 AM org.opengrok.indexer.index.IndexDatabase update
SEVERE: Failed with unexpected RuntimeException
org.apache.lucene.store.AlreadyClosedException: count=6
        at org.opengrok.indexer.index.IndexDatabase.indexParallel(IndexDatabase.java:1341)
        at org.opengrok.indexer.index.IndexDatabase.update(IndexDatabase.java:491)
        at org.opengrok.indexer.index.IndexDatabase$1.run(IndexDatabase.java:221)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Mar 09, 2020 7:20:04 AM org.opengrok.indexer.index.IndexDatabase$1 run
SEVERE: Problem updating index database in directory /data/index/main:
org.apache.lucene.store.AlreadyClosedException: count=6
        at org.opengrok.indexer.index.IndexDatabase.indexParallel(IndexDatabase.java:1341)
        at org.opengrok.indexer.index.IndexDatabase.update(IndexDatabase.java:491)
        at org.opengrok.indexer.index.IndexDatabase$1.run(IndexDatabase.java:221)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Followed by:

SEVERE: Unexpected Exception
java.io.FileNotFoundException: /var/opengrok/etc/configuration.xml (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at org.opengrok.indexer.configuration.Configuration.write(Configuration.java:1281)
        at org.opengrok.indexer.configuration.RuntimeEnvironment.writeConfiguration(RuntimeEnvironment.java:1470)
        at org.opengrok.indexer.index.Indexer.writeConfigToFile(Indexer.java:863)
        at org.opengrok.indexer.index.Indexer.main(Indexer.java:350)

I'm running opengrok off of the opengrok/docker:latest image in a container. 

Please help :(

**Comment by vladak** [comment]
This looks like a systemic problem with the environment. In particular, the last exception is from method that merely creates a file: https://github.com/oracle/opengrok/blob/73e2f8d19909113822e5bc6b3d452dcaf798a452/opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java#L1280-L1284

What is more strange however is the location of the file - this does not match the location used by the official docker image: https://github.com/oracle/opengrok/blob/73e2f8d19909113822e5bc6b3d452dcaf798a452/docker/index.sh#L27

Looking at  https://microbadger.com/images/opengrok/docker the latest is definitely behind official releases, need to look into that.

**Comment by vladak** [comment]
The default configuration file used by Docker container was changed prior 1.3.0 in cset 3185e592 so that's indeed strange.

**Comment by vladak** [comment]
Actually, the Microbadger is wrong, https://hub.docker.com/r/opengrok/docker/tags correctly contains the 1.3.9 released today.

**Comment by Ymoise** [comment]
Closing issue. User error.

My apologies.

**Comment by vladak** [comment]
Okie dokie. At least I found out that Microbadger needs updating.

**Comment by Ymoise** [comment]
Glad it wasn't a complete waste of your time, then. That's a relief.
