### ISSUE TITLE
Index is failing with NullPointerException when indexing Subversion repository

### ISSUE THREAD

**Issue by sreehari83** [oracle/opengrok#3111]
opengrok: v1.3.9
version 1.9.7
I have indexed couple of projects successfully and later i got the following errors.

```
/usr/bin/java -server -Xms8048m -Xmx50096m -Djava.util.logging.config.file=/data/grok/logging.properties.parallel -jar /data/software/opengrok/lib/opengrok.jar  -R /data/grok/conf/rel_201.xml -O on  --depth 6  -r on -H -S 
Apr 12, 2020 4:31:52 PM org.opengrok.indexer.history.HistoryGuru$3 run
WARNING: Could not create Subversion for '/data/grok/src/RELEASE_xxx_THROTTLE
java.lang.NullPointerException
	at java.util.Calendar.setTime(Calendar.java:1770)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
	at java.text.DateFormat.format(DateFormat.java:345)
	at org.opengrok.indexer.history.Repository.format(Repository.java:522)
	at org.opengrok.indexer.history.SubversionRepository.determineCurrentVersion(SubversionRepository.java:417)
	at org.opengrok.indexer.history.RepositoryFactory.getRepository(RepositoryFactory.java:220)
	at org.opengrok.indexer.history.RepositoryFactory.getRepository(RepositoryFactory.java:137)
	at org.opengrok.indexer.history.RepositoryFactory.getRepository(RepositoryFactory.java:260)
	at org.opengrok.indexer.history.HistoryGuru$3.run(HistoryGuru.java:889)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Apr 12, 2020 4:31:54 PM org.opengrok.indexer.index.Indexer main
SEVERE: Unexpected Exception
java.lang.NullPointerException
	at java.util.Calendar.setTime(Calendar.java:1770)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
	at java.text.DateFormat.format(DateFormat.java:345)
	at org.opengrok.indexer.history.Repository.format(Repository.java:522)
	at org.opengrok.indexer.history.SubversionRepository.determineCurrentVersion(SubversionRepository.java:417)
	at org.opengrok.indexer.history.RepositoryFactory.getRepository(RepositoryFactory.java:220)
	at org.opengrok.indexer.history.HistoryGuru.addRepositories(HistoryGuru.java:415)
	at org.opengrok.indexer.history.HistoryGuru.addRepositories(HistoryGuru.java:438)
	at org.opengrok.indexer.history.HistoryGuru.addRepositories(HistoryGuru.java:485)
	at org.opengrok.indexer.configuration.RuntimeEnvironment.setRepositories(RuntimeEnvironment.java:797)
	at org.opengrok.indexer.index.Indexer.prepareIndexer(Indexer.java:960)
	at org.opengrok.indexer.index.Indexer.main(Indexer.java:338)

Exception: null
```

**Comment by sreehari83** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<java version="1.8.0_242" class="java.beans.XMLDecoder">
 <object class="org.opengrok.indexer.configuration.Configuration" id="Configuration0">
  <void property="cmds">
   <object class="java.util.Collections" method="unmodifiableMap">
    <object class="java.util.HashMap">
     <void method="put">
      <string>org.opengrok.indexer.history.SubversionRepository</string>
      <string>/usr/bin/svn</string>
     </void>
     <void method="put">
      <string>org.opengrok.indexer.history.ClearCaseRepository</string>
      <string>cleartool</string>
     </void>
     <void method="put">
      <string>org.opengrok.indexer.history.PerforceRepository</string>
      <string>p4</string>
     </void>
    </object>
   </object>
  </void>
  <void property="ctags">
   <string>/data/software/ctags/ctags</string>
  </void>
  <void property="dataRoot">
   <string>/data/grok/data</string>
  </void>
  <void id="IgnoredNames0" property="ignoredNames">
   <void id="IgnoredDirs0" property="ignoredDirs">
    <void property="items">
     <void method="add">
      <string>.git</string>
     </void>
     <void method="add">
      <string>.hg</string>
     </void>
     <void method="add">
      <string>.repo</string>
     </void>
     <void method="add">
      <string>.bk</string>
     </void>
     <void method="add">
      <string>.bzr</string>
     </void>
     <void method="add">
      <string>.svn</string>
     </void>
     <void method="add">
      <string>SCCS</string>
     </void>
     <void method="add">
      <string>.razor</string>
     </void>
     <void method="add">
      <string>RCS</string>
     </void>
     <void method="add">
      <string>CVS</string>
     </void>
     <void method="add">
      <string>CVSROOT</string>
     </void>
    </void>
   </void>
   <void id="IgnoredFiles0" property="ignoredFiles">
    <void property="items">
     <void method="add">
      <string>.git</string>
     </void>
     <void method="add">
      <string>.hgtags</string>
     </void>
     <void method="add">
      <string>.hgignore</string>
     </void>
     <void method="add">
      <string>.cvsignore</string>
     </void>
     <void method="add">
      <string>.p4config</string>
     </void>
    </void>
   </void>
  </void>
  <void property="projects">
   <void method="put">
    <string>RELEASE_xxx_THROTTLE</string>
    <object class="org.opengrok.indexer.configuration.Project">
     <void property="indexed">
      <boolean>true</boolean>
     </void>
     <void property="name">
      <string>RELEASE_xxx_THROTTLE</string>
     </void>
     <void property="path">
      <string>/RELEASE_xxx_THROTTLE</string>
     </void>
    </object>
   </void>
  </void>
  <void property="projectsEnabled">
   <boolean>true</boolean>
  </void>
  <void property="repositories">
   <void method="add">
    <object class="org.opengrok.indexer.history.RepositoryInfo">
     <void property="branch">
      <string>RELEASE_xxx_THROTTLE</string>
     </void>
     <void property="currentVersion">
     </void>
     <void property="datePatterns">
      <array class="java.lang.String" length="3">
       <void index="0">
        <string>yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS&apos;Z&apos;</string>
       </void>
       <void index="1">
        <string>yyyy-MM-dd&apos;T&apos;HH:mm:ss.&apos;Z&apos;</string>
       </void>
       <void index="2">
        <string>yyyy-MM-dd&apos;T&apos;HH:mm:ss&apos;Z&apos;</string>
       </void>
      </array>
     </void>
     <void property="directoryNameRelative">
      <string>/RELEASE_xxx_THROTTLE</string>
     </void>
     <void property="parent">
      <string>svn+ssh://svn@svn.server/repo/branches/RELEASE_xxx_THROTTLE</string>
     </void>
     <void property="remote">
      <boolean>true</boolean>
     </void>
     <void property="type">
      <string>Subversion</string>
     </void>
    </object>
   </void>
  </void>
  <void property="scanningDepth">
   <int>6</int>
  </void>
  <void property="sourceRoot">
   <string>/data/grok/src</string>
  </void>
 </object>
</java>

**Comment by idodeclare** [comment]
Does `svn log` in that repo show anything odd? E.g. an access issue causing history to be partially undefined?

**Comment by sreehari83** [comment]
it is working after deleting -s option from index. commad.

thank you for verifying this.

**Comment by vladak** [comment]
https://github.com/oracle/opengrok/issues/3111#issuecomment-612643270 has nothing inside the `currentVersion` element which is consequence of the NPE I think.

`determineCurrentVersion()` uses history retrieval to determine current version so this had to fail for some reason - that's why @idodeclare asked about the output from `svn log` for that repository.

I don't think not using `-s` is related.

**Comment by vladak** [comment]
The code that handles this
https://github.com/oracle/opengrok/blob/2b7010dd0cf2616194ca2e8816a0310f788f9727/opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionRepository.java#L413-L421
is already pretty cautious however it could be a bit more.

In this case it seems that `he.getDate()` was `null`.

**Comment by vladak** [comment]
Anyway, the root cause seems to be rather in the repository itself than the code handling it.
