### ISSUE TITLE
Indexer OOM Errors in Docker

### ISSUE THREAD

**Issue by davjr96** [oracle/opengrok#3123]
**Describe the bug**
I'm getting the following error while trying to run the indexer. I have about 40 Perforce projects around 20GB (some smaller at 1-2GB) and most of them index fine however a few (4 to be exact) throw this error with no discernable difference from the other repositories.

The VM it is running on has 12 CPU cores and 80GB of RAM. It never goes above 40GB RAM usage, so I don't think it is actually running out of memory. Note this is not a HEAP error (I get those if heap is 12GB). 

```
Apr 20, 2020 3:42:15 PM org.opengrok.indexer.index.IndexDatabase$1 run
SEVERE: Problem updating index database in directory /opengrok/data/index/XXXXXX:
java.lang.OutOfMemoryError
        at java.base/java.io.ByteArrayOutputStream.hugeCapacity(ByteArrayOutputStream.java:125)
        at java.base/java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:119)
        at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95)
        at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:156)
        at org.opengrok.indexer.util.Executor$SpoolHandler.processStream(Executor.java:388)
        at org.opengrok.indexer.util.Executor.exec(Executor.java:230)
        at org.opengrok.indexer.util.Executor.exec(Executor.java:143)
        at org.opengrok.indexer.util.Executor.exec(Executor.java:132)
        at org.opengrok.indexer.history.PerforceHistoryParser.parseDirectory(PerforceHistoryParser.java:128)
        at org.opengrok.indexer.history.PerforceHistoryParser.parse(PerforceHistoryParser.java:100)
        at org.opengrok.indexer.history.PerforceRepository.getHistory(PerforceRepository.java:228)
        at org.opengrok.indexer.history.Repository.createCache(Repository.java:382)
        at org.opengrok.indexer.history.HistoryGuru.createCache(HistoryGuru.java:531)
        at org.opengrok.indexer.history.HistoryGuru.ensureHistoryCacheExists(HistoryGuru.java:761)
        at org.opengrok.indexer.index.IndexDatabase.update(IndexDatabase.java:442)
        at org.opengrok.indexer.index.IndexDatabase$1.run(IndexDatabase.java:221)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
 
I am using the opengrok official docker container (1.3.11) and the following custom indexer options

```
opengrok-indexer \
    -J=-Xmx24g \
    -a /opengrok/lib/opengrok.jar -- \
    -m 256 \
    -s /opengrok/src \
    -d /opengrok/data \
    --remote on \
    -R /var/opengrok/etc/read-only.xml \
    -W /opengrok/etc/configuration.xml \
    -U "$URI" \
    $OPS \
    $INDEXER_OPT "$@"
```

```
cat read-only.xml 
<?xml version="1.0" encoding="UTF-8"?>
<java version="11.0.6" class="java.beans.XMLDecoder">
 <object class="org.opengrok.indexer.configuration.Configuration">
   <void property="ctagsTimeout"> <!-- name of the property in configuration -->
        <long>120</long> <!-- java type and value -->
  </void>
 </object>
</java>

```

Any suggestions of possible debugging steps or options to tune?

**Comment by davjr96** [comment]
Well I saw there was a new build last night 1.3.13 and the problem has gone away there.

**Comment by vladak** [comment]
That's quite strange. 1.3.11 was actually the version that addressed JVM heap problem (#3094), the newer changes were not related I think. Looking at the stack trace it could be that some of the Perforce fixes in 1.3.12 helped.

**Comment by idodeclare** [comment]
Yes, @gtoph  added the `filelog` `-s` switch to ignore "non-contributory integrations". That apparently kept it under your memory constraint.

The stack trace you captured indicates another possible future optimization. The `ByteArrayOutputStream` use by `Executor` shows that the Perforce parser is copying all `filelog` output into memory and then parsing it into `History`. Other parsers parse directly into `History` without the intermediate copy; that could be done for `PerforceHistoryParser` too.

**Comment by davjr96** [comment]
> Yes, @gtoph added the `filelog` `-s` switch to ignore "non-contributory integrations". That apparently kept it under your memory constraint.
 
That sounds very likely given the way our codebase was structured.
