### ISSUE TITLE
LdapFacade should log the search parameters on exception

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3128]
Lately I've been fighting LDAP server/pool going down because of failed search due to:
```
25-Apr-2020 11:00:59.153 SEVERE [http-nio-8080-exec-2419] opengrok.auth.plugin.ldap.LdapFacade.lookup An arbitrary LDAP error occurred on server ldaps://ldap.foo.com timeout: 3000 username: cn=FOOLDAP_CZ,l=a
mer,dc=foo,dc=com
        javax.naming.NamingException: [LDAP: error code 36 - Problem in dereferencing the base of the search.]; remaining name 'dc=foo,dc=com'
                at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3130)
                at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3100)
                at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2891)
                at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1846)
                at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1769)
                at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:392)
                at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:358)
                at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:341)
                at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:267)
                at opengrok.auth.plugin.ldap.LdapServer.search(LdapServer.java:227)
                at opengrok.auth.plugin.ldap.LdapServer.search(LdapServer.java:193)
                at opengrok.auth.plugin.ldap.LdapFacade.lookup(LdapFacade.java:343)
                at opengrok.auth.plugin.ldap.LdapFacade.lookup(LdapFacade.java:295)
                at opengrok.auth.plugin.ldap.LdapFacade.lookupLdapContent(LdapFacade.java:263)
                at opengrok.auth.plugin.LdapUserPlugin.fillSession(LdapUserPlugin.java:166)
                at opengrok.auth.plugin.AbstractLdapPlugin.ensureSessionExists(AbstractLdapPlugin.java:257)
                at opengrok.auth.plugin.AbstractLdapPlugin.isAllowed(AbstractLdapPlugin.java:298)
                at org.opengrok.indexer.authorization.AuthorizationFramework$1.decision(AuthorizationFramework.java:131)
                at org.opengrok.indexer.authorization.AuthorizationPlugin.isAllowed(AuthorizationPlugin.java:189)
                at org.opengrok.indexer.authorization.AuthorizationStack.processStack(AuthorizationStack.java:241)
                at org.opengrok.indexer.authorization.AuthorizationStack.isAllowed(AuthorizationStack.java:202)
                at org.opengrok.indexer.authorization.AuthorizationFramework.performCheck(AuthorizationFramework.java:563)
                at org.opengrok.indexer.authorization.AuthorizationFramework.checkAll(AuthorizationFramework.java:521)
                at org.opengrok.indexer.authorization.AuthorizationFramework.isAllowed(AuthorizationFramework.java:124)
                at org.opengrok.indexer.web.PageConfig.isAllowed(PageConfig.java:1581)
                at org.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:68)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:748)
```
For better debugging it would help if search parameters were also logged, perhaps separately with lower log level.

Also, this sort of failure makes me wonder if such kind of failures should be just reported without marking the server/pool as down. There might be other candidates on the list https://ldapwiki.com/wiki/LDAP%20Result%20Codes however getting the LDAP error code from the exception might not be easy (https://docs.oracle.com/javase/8/docs/api/javax/naming/NamingException.html).

**Comment by vladak** [comment]
Getting numeric LDAP error code from the `NamingException` does not seem to be possible -  `LdapCtx#mapErrorCode()` that constructs the exception does this:
```
        String message = LdapClient.getErrorMessage(errorCode, errorMessage);

        switch (errorCode) {

        case LdapClient.LDAP_ALIAS_DEREFERENCING_PROBLEM:
            e = new NamingException(message);
            break;

...

        return e;
```
and matching the string is not very robust.
