### ISSUE TITLE
Unsafe memory location error while accessing web page

### ISSUE THREAD

**Issue by Me4791** [oracle/opengrok#3163]
OpenGrok version: 1.3.3
Git Version: 2.17
Tomcat version 9

Description: We are getting "a fault occurred in a recent unsafe memory access operation in compiled java code" message when trying to access a file under a project/repo. This occurs very often. Could you please help in resolving this one. This error goes away from few hours to days or sometime need to redeploy the WebApplication

Indexing Process: We are indexing the source continuously in same directory (ABC) using as workspace 
dir ABC
Sub Dir: Data, Logs, src, etc

![UnsafeMemory](https://user-images.githubusercontent.com/52797307/83912352-bb916b00-a73b-11ea-879e-fbbbdc9ae67f.jpg)

**Comment by vladak** [comment]
When exactly this started happening ? Anything changed prior to that ? Anything else interesting in Tomcat logs ? What JVM do you use ?

`IntermalError` in native Java class does not look like something we can address.

**Comment by vladak** [comment]
For reference, here is the piece of code that triggers it: https://github.com/oracle/opengrok/blob/748d69c7ce0c716a7535e75a3134190445030208/opengrok-indexer/src/main/java/org/opengrok/indexer/search/DirectoryExtraReader.java#L79

**Comment by vladak** [comment]
What do you mean by the continuous indexing ?

**Comment by Me4791** [comment]
The logs shows nothing unusual, going through indexing stuff and writing the files which aren't found.
Previously, we were doing Indexing per project but that architecture doesn't fit to fulfill requirements. 
I will look into upgrading to Java 11.
Thanks a lot!

**Comment by idodeclare** [comment]
@Me4791, if you're willing, would you run the following to extract some log rows of interest (with paths anonymized) and paste in a gist somewhere:

```
egrep 'HistoryGuru.createCache:|FileHistoryCache.store:|FileHistoryCache.finishStore:|Statistics.report: Done historycache|IndexDatabase.update: Starting traversal|Statistics.report: Done traversal|Statistics.report: Done indexing' opengrok0.0.log | perl -nle 'BEGIN { undef $/ }
my @p = m`(?<=[\x20\t])(/\S*)`gx;
for my $p (@p) {
    next if $s{$p};
    ++$i;
    s`\Q$p\E`/src/path$i`gx;
    $s{$p} = 1;
}
print;'
```

That will output as shown in the following example (ellipses are mine):

```
2020-06-11 13:02:23.354-0500 INFO t289 HistoryGuru.createCache: Creating historycache for /src/path1 (GitRepository) without renamed file handling
2020-06-11 13:02:23.354-0500 INFO t291 HistoryGuru.createCache: Creating historycache for /src/path2 (GitRepository) without renamed file handling
2020-06-11 13:02:23.354-0500 INFO t293 HistoryGuru.createCache: Creating historycache for /src/path3 (GitRepository) without renamed file handling
...
2020-06-11 13:02:23.376-0500 INFO t294 Statistics.report: Done historycache for /src/path8 (took 21 ms)
...
2020-06-11 13:02:47.334-0500 INFO t378 IndexDatabase.update: Starting traversal of directory /src/path40
...
2020-06-11 13:02:47.870-0500 INFO t378 Statistics.report: Done traversal of directory /src/path40 (took 536 ms)
...
2020-06-11 13:02:48.381-0500 INFO t378 Statistics.report: Done indexing of directory /src/path40 (took 510 ms)
...
2020-06-11 13:05:49.884-0500 INFO t1 Statistics.report: Done indexing data of all repositories (took 0:03:03)
```

**Comment by Me4791** [comment]
Sure! Currently the indexing is in progress and  I will post the output as soon it will be done
Thanks!.

**Comment by Me4791** [comment]
Question:
I start to run 'repo sync' command to fetch source as soon as the indexing finishes, in the same src dir (in the same workspace). Does that causes any error? 
In other words, The indexing is done based off of the src folder synced.  
Now, if I am syncying the source again in the same src dir, it will get the deltas hence the files will be changed. that causes the memory   map to change as well. In this scenario if a user searches for a file that has been changed already in new source but the indexes are still pointing to the old source, hence won't be able to find the file at the same memory address. 
I am not sure if I am able to explain it well.

Alternatively, Does indexes depends upon the source code under src folder while doing serches?

Thanks!

**Comment by idodeclare** [comment]
No, OpenGrok wouldn’t keep your source files open for long. Each is read as quickly as possible for indexing or for displaying matching lines during search — and then closed.

The memory-mapped files are almost certainly Lucene index files under `data/`.

**Comment by Me4791** [comment]
@idodeclare, If I am understanding your point correctly then the search has nothing to do with the source code under src folder once indexed. Correct?
Thanks!

**Comment by idodeclare** [comment]
To complete a search, matching source files are quickly re-read to show matching lines. For example an index search result might indicate a particular search term matched at offset 437 in a source file. The source file is read, and the line containing offset 437 is presented to the user.

If your `repo sync` has updated a source file since indexing, then OpenGrok notices that the timestamp doesn't match the metadata in the index search result, and OpenGrok will attempt an ad-hoc re-analysis of a source file to find matching lines. Such re-analysis uses the older OpenGrok highlighting code and not the Lucene unified highlighter.

**Comment by kaychu2013** [comment]
hi @Me4791 I met the similar issue that 
"There was an error!
a fault occurred in a recent unsafe memory access operation in compiled Java code
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code",
Did you solve it by upgrading to Java11?

**Comment by Me4791** [comment]
Hello @kaychu2013, We still have that issue. This error may occur when someone is trying to access the files which have no reference in memory map. The source changes during fetching deltas while syncing from git, files changed but the indexes and memory map are still old. We are doing indexing during night time when there is no traffic followed by recycling tomcat once the index finishes. Upgrading to Java 11 may help but we didn't try.  We are trying to move OpenGrok to Kubernettes cluster. Thanks!

**Comment by sfuantos** [comment]
We ran into this issue as well in different presentations.

Tomcat version: 10.1.46
Opengrok version: 1.13.0
Java version:
java 17.0.15 2025-04-15 LTS
Java(TM) SE Runtime Environment (build 17.0.15+9-LTS-241)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.15+9-LTS-241, mixed mode, sharing)

```java
28-Oct-2025 05:02:34.126 SEVERE [https-jsse-nio-8444-exec-1] org.opengrok.indexer.search.context.Context.getContext2 ERROR highlightFieldsUnion(...)
        java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
                at org.apache.lucene.store.DataInput.readVInt(DataInput.java:137)
                at org.apache.lucene.codecs.lucene99.Lucene99PostingsReader$EverythingEnum.refillPositions(Lucene99PostingsReader.java:788)
                at org.apache.lucene.codecs.lucene99.Lucene99PostingsReader$EverythingEnum.nextPosition(Lucene99PostingsReader.java:1007)
                at org.apache.lucene.search.TermMatchesIterator.next(TermMatchesIterator.java:41)
                at org.apache.lucene.search.uhighlight.OffsetsEnum$OfMatchesIterator.nextPosition(OffsetsEnum.java:351)
                at org.apache.lucene.search.uhighlight.OffsetsEnum$OfMatchesIteratorWithSubs.nextPosition(OffsetsEnum.java:200)
                at org.apache.lucene.search.uhighlight.FieldHighlighter.highlightOffsetsEnums(FieldHighlighter.java:134)
                at org.apache.lucene.search.uhighlight.FieldHighlighter.highlightFieldForDoc(FieldHighlighter.java:83)
                at org.apache.lucene.search.uhighlight.UnifiedHighlighter.highlightFieldsAsObjects(UnifiedHighlighter.java:944)
                at org.opengrok.indexer.search.context.OGKUnifiedHighlighter.highlightFieldsUnionWork(OGKUnifiedHighlighter.java:163)
```

```java
26-Oct-2025 03:11:19.504 SEVERE [https-jsse-nio-8444-exec-10] org.opengrok.indexer.search.context.Context.getContext2 ERROR highlightFieldsUnion(...)
        java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
                at org.apache.lucene.search.uhighlight.FieldHighlighter.getSummaryPassagesNoHighlight(FieldHighlighter.java:109)
                at org.apache.lucene.search.uhighlight.FieldHighlighter.highlightFieldForDoc(FieldHighlighter.java:89)
                at org.apache.lucene.search.uhighlight.UnifiedHighlighter.highlightFieldsAsObjects(UnifiedHighlighter.java:944)
                at org.opengrok.indexer.search.context.OGKUnifiedHighlighter.highlightFieldsUnionWork(OGKUnifiedHighlighter.java:163)
                at org.opengrok.indexer.search.context.OGKUnifiedHighlighter.highlightFieldsUnion(OGKUnifiedHighlighter.java:135)
                at org.opengrok.indexer.search.context.Context.getContext2(Context.java:222)
                at org.opengrok.indexer.search.Results.printPlain(Results.java:280)
                at org.opengrok.indexer.search.Results.prettyPrint(Results.java:247)
                at org.apache.jsp.search_jsp._jspService(search_jsp.java:953)
                at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:64)
--
                at java.base/java.lang.Thread.run(Thread.java:842)
```

```java
25-Oct-2025 20:46:19.821 SEVERE [https-jsse-nio-8444-exec-8] org.opengrok.indexer.search.context.Context.getContext2 ERROR highlightFieldsUnion(...)
        java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
                at org.apache.lucene.search.uhighlight.FieldHighlighter.highlightOffsetsEnums(FieldHighlighter.java:168)
                at org.apache.lucene.search.uhighlight.FieldHighlighter.highlightFieldForDoc(FieldHighlighter.java:83)
                at org.apache.lucene.search.uhighlight.UnifiedHighlighter.highlightFieldsAsObjects(UnifiedHighlighter.java:944)
                at org.opengrok.indexer.search.context.OGKUnifiedHighlighter.highlightFieldsUnionWork(OGKUnifiedHighlighter.java:163)
                at org.opengrok.indexer.search.context.OGKUnifiedHighlighter.highlightFieldsUnion(OGKUnifiedHighlighter.java:135)
                at org.opengrok.indexer.search.context.Context.getContext2(Context.java:222)
                at org.opengrok.indexer.search.Results.printPlain(Results.java:280)
                at org.opengrok.indexer.search.Results.prettyPrint(Results.java:247)
                at org.apache.jsp.search_jsp._jspService(search_jsp.java:953)
                at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:64)
--
```


```java
26-Oct-2025 08:50:26.810 SEVERE [https-jsse-nio-8444-exec-6] org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse Error while closing the output stream in order to commit response.
        org.glassfish.jersey.server.ContainerException: java.util.concurrent.ExecutionException: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
                at org.glassfish.jersey.servlet.internal.ResponseWriter.getResponseContext(ResponseWriter.java:278)
                at org.glassfish.jersey.servlet.internal.ResponseWriter.writeResponseStatusAndHeaders(ResponseWriter.java:128)
                at org.glassfish.jersey.server.ServerRuntime$Responder$1.getOutputStream(ServerRuntime.java:667)
                at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:171)
                at org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:276)
                at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:232)
                at org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:247)
                at org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:865)
                at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:403)
                at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:749)
--
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
                at java.base/java.lang.Thread.run(Thread.java:842)
        Caused by: java.util.concurrent.ExecutionException: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
                at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
                at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
                at org.glassfish.jersey.servlet.internal.ResponseWriter.getResponseContext(ResponseWriter.java:276)
                ... 59 more
        Caused by: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
                at org.apache.lucene.codecs.lucene99.GroupVIntReader.readLong(GroupVIntReader.java:54)
                at org.apache.lucene.codecs.lucene99.GroupVIntReader.readValues(GroupVIntReader.java:35)
                at org.apache.lucene.codecs.lucene99.Lucene99PostingsReader.readVIntBlock(Lucene99PostingsReader.java:152)
                at org.apache.lucene.codecs.lucene99.Lucene99PostingsReader$BlockDocsEnum.refillDocs(Lucene99PostingsReader.java:478)
                at org.apache.lucene.codecs.lucene99.Lucene99PostingsReader$BlockDocsEnum.advance(Lucene99PostingsReader.java:544)
                at org.apache.lucene.index.SlowImpactsEnum.advance(SlowImpactsEnum.java:77)
                at org.apache.lucene.search.ImpactsDISI.advance(ImpactsDISI.java:104)
                at org.apache.lucene.search.ImpactsDISI.nextDoc(ImpactsDISI.java:109)
                at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:316)
                at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:233)
--
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
                ... 1 more
                Suppressed: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
                        at org.apache.lucene.codecs.lucene99.GroupVIntReader.readLong(GroupVIntReader.java:54)
                        at org.apache.lucene.codecs.lucene99.GroupVIntReader.readValues(GroupVIntReader.java:36)
                        ... 16 more
                Suppressed: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
                        at org.apache.lucene.codecs.lucene90.IndexedDISI$Method$1.advanceExactWithinBlock(IndexedDISI.java:573)
                        at org.apache.lucene.codecs.lucene90.IndexedDISI.advanceExact(IndexedDISI.java:461)
                        at org.apache.lucene.codecs.lucene90.Lucene90NormsProducer$SparseNormsIterator.advanceExact(Lucene90NormsProducer.java:206)
                        at org.apache.lucene.search.LeafSimScorer.getNormValue(LeafSimScorer.java:45)
                        at org.apache.lucene.search.LeafSimScorer.score(LeafSimScorer.java:60)
                        at org.apache.lucene.search.TermScorer.score(TermScorer.java:86)
                        at org.apache.lucene.search.ScoreCachingWrappingScorer.score(ScoreCachingWrappingScorer.java:61)
                        at org.apache.lucene.search.FieldComparator$RelevanceComparator.copy(FieldComparator.java:165)
                        at org.apache.lucene.search.TopFieldCollector$TopFieldLeafCollector.collectAnyHit(TopFieldCollector.java:125)
                        at org.apache.lucene.search.TopFieldCollector$SimpleFieldCollector$1.collect(TopFieldCollector.java:209)
--
```

```java
Exception in thread "OpenGrok-search-175" java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1610)
        at java.base/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
        at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)
```

```java
26-Oct-2025 08:50:26.810 SEVERE [https-jsse-nio-8444-exec-6] org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse Error while closing the output stream in order to commit response.
        org.glassfish.jersey.server.ContainerException: java.util.concurrent.ExecutionException: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
                at org.glassfish.jersey.servlet.internal.ResponseWriter.getResponseContext(ResponseWriter.java:278)
                at org.glassfish.jersey.servlet.internal.ResponseWriter.writeResponseStatusAndHeaders(ResponseWriter.java:128)
                at org.glassfish.jersey.server.ServerRuntime$Responder$1.getOutputStream(ServerRuntime.java:667)
                at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:171)
                at org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:276)
                at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:232)
                at org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:247)
                at org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:865)
                at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:403)
                at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:749)
--
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
                at java.base/java.lang.Thread.run(Thread.java:842)
```
```
Exception in thread "https-jsse-nio-8444-exec-12" java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
        at org.apache.jsp.search_jsp._jspService(search_jsp.java:1026)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:64)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:435)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:356)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:307)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
--
```
