### ISSUE TITLE
Suggester does not work on Java 14

### ISSUE THREAD

**Issue by stevenschlansker** [oracle/opengrok#3206]
**Describe the bug**
OpenGrok 1.4.1, Java 14.0.2

**To Reproduce**
Start up Suggester with recommended `--add-exports` modules.
It fails:
```
java.lang.AssertionError: java.lang.NoSuchMethodException: sun.nio.ch.FileChannelImpl.map0(int,long,long) at net.openhft.chronicle.core.Jvm.getMethod0(Jvm.java:365) at net.openhft.chronicle.core.Jvm.getMethod(Jvm.java:344) at net.openhft.chronicle.core.OS.lambda$static$0(OS.java:49) at net.openhft.chronicle.core.ClassLocal.computeValue(ClassLocal.java:53) at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:226) at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:208) at java.base/java.lang.ClassValue.get(ClassValue.java:114) at net.openhft.chronicle.core.OS.map0(OS.java:366) at net.openhft.chronicle.core.OS.map(OS.java:345) at net.openhft.chronicle.hash.impl.VanillaChronicleHash.map(VanillaChronicleHash.java:986) at net.openhft.chronicle.hash.impl.VanillaChronicleHash.createMappedStoreAndSegments(VanillaChronicleHash.java:489) at net.openhft.chronicle.map.ChronicleMapBuilder.createWithNewFile(ChronicleMapBuilder.java:1766) at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1670) at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1564) at net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1586) at net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1575) at net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1569) at org.opengrok.suggest.popular.impl.chronicle.ChronicleMapAdapter.<init>(ChronicleMapAdapter.java:55) at org.opengrok.suggest.SuggesterProjectData.initSearchCountMap(SuggesterProjectData.java:309) at org.opengrok.suggest.SuggesterProjectData.init(SuggesterProjectData.java:158) at org.opengrok.suggest.Suggester.lambda$getInitRunnable$1(Suggester.java:206) at
```
Indeed, `map0` is private API and has a now-changed signature of `(int,long,long,boolean)`.

**Expected behavior**
Suggester should work on vanilla current JVM.  Projects should not use internal JVM APIs without having a vanilla fallback :)

**Additional context**
Seems to be fixed in chronicle-core 2.20.20

**Comment by vladak** [comment]
should be fixed in 40dd27d913935d810cd12e9a09205331f7fb903c
