### ISSUE TITLE
New memory errors?

### ISSUE THREAD

**Issue by gtoph** [oracle/opengrok#3404]
Haven't dug into anything yet, but wanted to see if anyone else was seeing a memory error in HEAD as of 4 days?

Author:			Vladimir Kotal <vlada@devnull.cz>
Date:			4 days ago (12/11/2020 7:02:18 AM)
Committer:		GitHub <noreply@github.com>
Commit hash:	3db23db2ca3cbf347cd3e52c1c6580914c4c5e31

a fault occurred in a recent unsafe memory access operation in compiled Java code
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:685)
	at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:269)
	at org.apache.lucene.store.ByteBufferGuard.getByte(ByteBufferGuard.java:119)
......

or 
a fault occurred in a recent unsafe memory access operation in compiled Java code
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
	at org.apache.lucene.store.DataInput.readVLong(DataInput.java:214)
	at org.apache.lucene.store.DataInput.readVLong(DataInput.java:190)
	at org.apache.lucene.util.fst.FST.readUnpackedNodeTarget(FST.java:1035)
....

**Comment by vladak** [comment]
Haven't seen anything. The last Lucene update was a while back.

**Comment by gtoph** [comment]
ya i'm not sure what is going on yet... could just be me.  If I find anything significant, I'll let ya know.

**Comment by gtoph** [comment]
No idea what was going on, but cleaned the build, wiped out the repos and started from scratch.  Seems ok now.  I'll just monitor it for now.  Thanks!
