### ISSUE TITLE
Indexing failed

### ISSUE THREAD

**Issue by jeevavm** [oracle/opengrok#3481]
We have installed  Opengrok 1.6.4, OpenJDK 15.02 and apache tomcat 10.0.2

While indexing multiple projects in the source folder we are getting below errors and the indexing skipped for many of the files in some projects and those projects are not listed in Opengrok search.

Mar 15, 2021 3:00:05 PM org.opensolaris.opengrok.index.IndexDatabase addFile
INFO: Skipped file '/3rdparty/node-modules/trunk/node_modules/protractor/node_modules/webdriver-manager/built/lib/cli/logger.d.ts' because the analyzer didn't understand it.
Mar 15, 2021 3:00:05 PM org.opensolaris.opengrok.index.IndexDatabase indexDown
INFO: Progress: 25,441 (68.238%)
Mar 15, 2021 3:00:05 PM org.opensolaris.opengrok.index.IndexDatabase addFile
INFO: Skipped file '/business-services/business-services-common/trunk/UnitTests/Adg.AsyncProcessing.Test.Common/ResourceManager.cs' because the analyzer didn't understand it.
Mar 15, 2021 3:00:05 PM org.opensolaris.opengrok.index.IndexDatabase addFile
INFO: Skipped file '/business-services/business-services-common/trunk/UnitTests/Adg.AsyncProcessing.Test.Common/Scripts/CaseTestData.sql' because the analyzer didn't understand it.

**Comment by vladak** [comment]
I don't think skipped files lead to failure of the indexer as a whole. After all, these exceptions are swallowed: https://github.com/oracle/opengrok/blob/4271459588af01aec552b5c4cb65a11274783a3b/opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java#L776-L786

and the impact is on single document, not whole index.

Could you run the indexer with the `FINE` logging level ? This should shed more light on these errors.

**Comment by jeevavm** [comment]
We are getting below error now,

Mar 16, 2021 2:25:58 PM org.opensolaris.opengrok.index.IndexDatabase$1 run
SEVERE: Problem updating lucene index database:
org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource: ChecksumIndexInput(NIOFSIndexInput(path="/var/opengrok/data/index/tools/segments_a"))): 10 (needs to be between 0 and 1)
        at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:148)
        at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:329)
        at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:404)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:843)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:694)
        at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:400)
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:746)
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:330)
        at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:168)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by vladak** [comment]
Um, we dropped the `org.opensolaris.opengrok` prefix long time ago so you must be running some really old indexer. Definitely not 1.6.4.

**Comment by jeevavm** [comment]
Sorry, my bad my script pointing the old opengrok jar before. Now the indexing job getting struck after the below log, Can please help us with how to resolve this.

2021-03-21 14:07:34.745+0000 FINER t1 SystemPropertiesConfigurationModel.getProperties: System properties configuration provider not allowed
2021-03-21 14:07:34.746+0000 FINE t1 ClientExecutorProvidersConfigurator.lookupManagedScheduledExecutorService: null
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.glassfish.jersey.client.ClientExecutorProvidersConfigurator.lookupManagedScheduledExecutorService(ClientExecutorProvidersConfigurator.java:174)
        at org.glassfish.jersey.client.ClientExecutorProvidersConfigurator.init(ClientExecutorProvidersConfigurator.java:124)
        at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:452)
        at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
        at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:814)
        at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:176)
        at org.glassfish.jersey.client.ClientRequest.getInjectionManager(ClientRequest.java:567)
        at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:364)
        at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:192)
        at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:36)
        at org.opengrok.indexer.configuration.RuntimeEnvironment.writeConfiguration(RuntimeEnvironment.java:1422)
        at org.opengrok.indexer.index.Indexer.sendToConfigHost(Indexer.java:1149)
        at org.opengrok.indexer.index.Indexer.main(Indexer.java:378)
Caused by: javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or in an application resource file: java.naming.factory.initial
        at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:691)
        at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
        at java.naming/javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:342)
        at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
        ... 16 more

2021-03-21 14:07:34.746+0000 CONFIG t1 ExtendedLogger.config: Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
2021-03-21 14:07:34.747+0000 CONFIG t1 ExtendedLogger.config: Selected ScheduledExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientBackgroundSchedulerProvider] to be used for injection of scheduler qualified by [org.glassfish.jersey.client.ClientBackgroundScheduler] annotation.
2021-03-21 14:07:34.751+0000 CONFIG t1 HttpUrlConnector.<init>: Restricted headers are not enabled using [sun.net.http.allowRestrictedHeaders] system property (setting only takes effect on connections created after the property has been set/changed).
2021-03-21 14:07:34.753+0000 FINEST t1 HttpURLConnection.plainConnect0: ProxySelector Request for http://localhost:8080/source/api/v1/configuration?reindex=true
2021-03-21 14:07:34.754+0000 FINEST t1 HttpURLConnection.plainConnect0: Proxy used: DIRECT
2021-03-21 14:07:34.755+0000 FINE t1 HttpURLConnection.writeRequests: sun.net.www.MessageHeader@8dfe9217 pairs: {PUT /source/api/v1/configuration?reindex=true HTTP/1.1: null}{Content-Type: application/xml}{User-Agent: Jersey/3.0.1 (HttpUrlConnection 15.0.2)}{Host: localhost:8080}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}{Content-Length: 44036}

**Comment by vladak** [comment]
If the indexer is indeed stuck (i.e. the process is still present however not progressing), could you capture the stack traces of the threads using `jstack` and attach it ?

The `java.naming.factory.initial` exception is innocuous. The latter exception `IndexFormatTooOldException` says that you have too old index for the project called `ui.` You need to wipe it out and reindex from scratch.

In overall, it would be handful to know what is it you are trying to do. Upgrading from old OpenGrok version to new one ?

**Comment by jeevavm** [comment]
We have migrating opengrok from old version to new version. We have installed new version opengrok in new server and while coping the scripts files new server we have also copied the old lib files. Our scripts pointed the old jar fils instead of new opengrok jar file. We have fixed that issue now.

Please fins the stack traces of the threads below,

"ForkJoinPool-1-worker-55" #411 daemon prio=5 os_prio=0 cpu=575.98ms elapsed=80.55s tid=0x00007fa5a8043810 nid=0x1cc4 waiting on condition  [0x00007fa590ce7000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@15.0.2/Native Method)
        - parking to wait for  <0x000000008992e578> (a java.util.concurrent.ForkJoinPool)
        at java.util.concurrent.locks.LockSupport.park(java.base@15.0.2/LockSupport.java:211)
        at java.util.concurrent.ForkJoinPool.runWorker(java.base@15.0.2/ForkJoinPool.java:1633)
        at java.util.concurrent.ForkJoinWorkerThread.run(java.base@15.0.2/ForkJoinWorkerThread.java:183)

   Locked ownable synchronizers:
        - None

"ForkJoinPool-1-worker-41" #412 daemon prio=5 os_prio=0 cpu=638.78ms elapsed=80.55s tid=0x00007fa598012950 nid=0x1cc5 waiting on condition  [0x00007fa590be6000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@15.0.2/Native Method)
        - parking to wait for  <0x000000008992e578> (a java.util.concurrent.ForkJoinPool)
        at java.util.concurrent.locks.LockSupport.park(java.base@15.0.2/LockSupport.java:211)
        at java.util.concurrent.ForkJoinPool.runWorker(java.base@15.0.2/ForkJoinPool.java:1633)
        at java.util.concurrent.ForkJoinWorkerThread.run(java.base@15.0.2/ForkJoinWorkerThread.java:183)

   Locked ownable synchronizers:
        - None

"ForkJoinPool-1-worker-37" #413 daemon prio=5 os_prio=0 cpu=0.27ms elapsed=80.53s tid=0x00007fa5a800f390 nid=0x1cc6 waiting on condition  [0x00007fa590ae5000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@15.0.2/Native Method)
        - parking to wait for  <0x000000008992e578> (a java.util.concurrent.ForkJoinPool)
        at java.util.concurrent.locks.LockSupport.park(java.base@15.0.2/LockSupport.java:211)
        at java.util.concurrent.ForkJoinPool.runWorker(java.base@15.0.2/ForkJoinPool.java:1633)
        at java.util.concurrent.ForkJoinWorkerThread.run(java.base@15.0.2/ForkJoinWorkerThread.java:183)

   Locked ownable synchronizers:
        - None

"Lucene Merge Thread #0" #416 daemon prio=5 os_prio=0 cpu=55394.11ms elapsed=60.96s tid=0x00007fa5c80dcfe0 nid=0x1e15 runnable  [0x00007fa597ffe000]
   java.lang.Thread.State: RUNNABLE
        at org.apache.lucene.codecs.lucene80.Lucene80NormsProducer.getNorms(Lucene80NormsProducer.java:394)
        at org.apache.lucene.codecs.PushPostingsWriterBase.writeTerm(PushPostingsWriterBase.java:124)
        at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter$TermsWriter.write(BlockTreeTermsWriter.java:907)
        at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter.write(BlockTreeTermsWriter.java:318)
        at org.apache.lucene.codecs.FieldsConsumer.merge(FieldsConsumer.java:105)
        at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsWriter.merge(PerFieldPostingsFormat.java:197)
        at org.apache.lucene.index.SegmentMerger.mergeTerms(SegmentMerger.java:244)
        at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:139)
        at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4760)
        at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4364)
        at org.apache.lucene.index.IndexWriter$IndexWriterMergeSource.merge(IndexWriter.java:5924)
        at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:624)
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:682)

   Locked ownable synchronizers:
        - None

"Lucene Merge Thread #0" #417 daemon prio=5 os_prio=0 cpu=56419.91ms elapsed=60.88s tid=0x00007fa5bc16a5c0 nid=0x1e16 runnable  [0x00007fa597efd000]
   java.lang.Thread.State: RUNNABLE
        at org.apache.lucene.util.fst.BytesStore.writeByte(BytesStore.java:89)
        at org.apache.lucene.util.fst.FST.<init>(FST.java:404)
        at org.apache.lucene.util.fst.Builder.<init>(Builder.java:189)
        at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter$PendingBlock.compileIndex(BlockTreeTermsWriter.java:431)
        at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter$TermsWriter.writeBlocks(BlockTreeTermsWriter.java:637)
        at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter$TermsWriter.pushTerm(BlockTreeTermsWriter.java:947)
        at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter$TermsWriter.write(BlockTreeTermsWriter.java:912)
        at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter.write(BlockTreeTermsWriter.java:318)
        at org.apache.lucene.codecs.FieldsConsumer.merge(FieldsConsumer.java:105)
        at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsWriter.merge(PerFieldPostingsFormat.java:197)
        at org.apache.lucene.index.SegmentMerger.mergeTerms(SegmentMerger.java:244)
        at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:139)
        at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4760)
        at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4364)
        at org.apache.lucene.index.IndexWriter$IndexWriterMergeSource.merge(IndexWriter.java:5924)
        at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:624)
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:682)

   Locked ownable synchronizers:
        - None

"Attach Listener" #418 daemon prio=9 os_prio=0 cpu=0.56ms elapsed=0.10s tid=0x00007fa5b8002b30 nid=0x1e70 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"VM Thread" os_prio=0 cpu=208.98ms elapsed=154.84s tid=0x00007fa5f4143230 nid=0x1900 runnable

"GC Thread#0" os_prio=0 cpu=955.14ms elapsed=154.91s tid=0x00007fa5f4063710 nid=0x18fb runnable

"GC Thread#1" os_prio=0 cpu=901.09ms elapsed=154.08s tid=0x00007fa5bc000aa0 nid=0x190b runnable

"G1 Main Marker" os_prio=0 cpu=3.86ms elapsed=154.90s tid=0x00007fa5f4073f80 nid=0x18fc runnable

"G1 Conc#0" os_prio=0 cpu=776.44ms elapsed=154.89s tid=0x00007fa5f4075330 nid=0x18fd runnable

"G1 Refine#0" os_prio=0 cpu=3.62ms elapsed=154.88s tid=0x00007fa5f40cf990 nid=0x18fe runnable

"G1 Young RemSet Sampling" os_prio=0 cpu=13.10ms elapsed=154.87s tid=0x00007fa5f40d0cc0 nid=0x18ff runnable

"VM Periodic Task Thread" os_prio=0 cpu=43.18ms elapsed=154.67s tid=0x00007fa5f4182ca0 nid=0x1909 waiting on condition

JNI global refs: 24, weak refs: 0

**Comment by vladak** [comment]
I wonder if the indexer is really stuck - what makes you think it is stuck ? Does it perform any syscalls ? How do the memory/CPU metrics look like when it appears to be hung ?
