### ISSUE TITLE
Omitting the INDEXER_OPT environment variable for Docker throws a Python exception

### ISSUE THREAD

**Issue by jnovak-praetorian** [oracle/opengrok#3498]
**To Reproduce**
```
$ docker run --rm -v /path/to/local/src/:/opengrok/src -p 127.0.0.1:8081:8080 opengrok/docker:1.6.4
Unable to find image 'opengrok/docker:1.6.4' locally
1.6.4: Pulling from opengrok/docker
Digest: sha256:e05e4ddd9b61b05507ec5774955355918c506021f7058e4ee45fc253fbdcba56
Status: Downloaded newer image for opengrok/docker:1.6.4
synchronization period = 10 minutes
Deploying web application
Traceback (most recent call last):
  File "/scripts/start.py", line 428, in <module>
    main()
  File "/scripts/start.py", line 391, in main
    create_bare_config(logger, extra_indexer_options.split())
AttributeError: 'NoneType' object has no attribute 'split'
```

**Expected behavior**
The `extra_indexer_options` should be an empty string, not a None type.
```
$ docker run -e INDEXER_OPT= --rm -v /path/to/local/src/:/opengrok/src -p 127.0.0.1:8081:8080 opengrok/docker:latest
synchronization period = 10 minutes
Deploying web application
Creating bare configuration in /opengrok/etc/configuration.xml
...
```

**Comment by ahornace** [comment]
I think this was meant to be fixed by https://github.com/oracle/opengrok/pull/3489

**Comment by jnovak-praetorian** [comment]
Yep, that would do it. Is this a duplicate issue? It doesn't look like that pull request was merged.

**Comment by ahornace** [comment]
You can keep the issue open. The PR was unfortunately closed by the original author. If you want, you can create one :) I'll have some time later in my evening so I can fix it then.
