### ISSUE TITLE
GitRepository#rebuildTagList fails for linux-mainline

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3502]
Looks like the tag rebuild should be more resilient:
```
25-Mar-2021 11:43:47.671 WARNING [pool-114-thread-1] org.opengrok.indexer.history.GitRepository.rebuildTagList cannot get tags for "/ws-local/linux-mainline"
        org.eclipse.jgit.errors.IncorrectObjectTypeException: Object 5dc01c595e6c6ec9ccda4f6f69c131c0dd945f8c is not a commit.
                at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:829)
                at org.opengrok.indexer.history.GitRepository.getCommit(GitRepository.java:711)
                at org.opengrok.indexer.history.GitRepository.rebuildTagList(GitRepository.java:635)
                at org.opengrok.indexer.history.GitRepository.lambda$buildTagList$4(GitRepository.java:692)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base/java.lang.Thread.run(Thread.java:834)
```

This is repo cloned from https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

**Comment by vladak** [comment]
For reference:
```
$ git show 5dc01c595e6c6ec9ccda4f6f69c131c0dd945f8c
tag v2.6.11-tree

This is the 2.6.11 tree object.

NOTE! There's no commit for this, since it happened before I started with git.
Eventually we'll import some sort of history, and that should tie this tree
object up to a real commit. In the meantime, this acts as an anchor point for
doing diffs etc under git.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.2.4 (GNU/Linux)

iD8DBQBCeV/eF3YsRnbiHLsRAl+SAKCVp8lVXwpUhMEvy8N5jVBd16UCmACeOtP6
KLMHist5yj0sw1E4hDTyQa0=
=/bIK
-----END PGP SIGNATURE-----

tree 5dc01c595e6c6ec9ccda4f6f69c131c0dd945f8c

COPYING
CREDITS
Documentation/
MAINTAINERS
Makefile
README
REPORTING-BUGS
arch/
crypto/
drivers/
fs/
include/
init/
ipc/
kernel/
lib/
mm/
net/
scripts/
security/
sound/
usr/
```
There is quite a few of these "tags".
