### ISSUE TITLE
HTTPS Basic Authentication to Access /source/api/v1/configuration from External Host

### ISSUE THREAD

**Issue by bjrdeja** [oracle/opengrok#3506]
Hello,

Could really use some assistance! I am attempting to manage my OpenGrok configuration remotely using /source/api/v1/configuration, and I have precisely followed the steps outlined the HTTP Basic Authentication documentation. 

https://github.com/oracle/opengrok/wiki/Authorization-based-on-HTTP-Basic-Authentication

I have also implemented HTTPS in my Tomcat 10 instance. Authentication works perfectly when using search, etc. over HTTPS from an external host. However, when calling https://192.xxx.xxx.xxx:8443/source/api/v1/configuration with basic authentication, I get a "HTTP Status 401 – Unauthorized". I am only able to access it from https://localhost:8443/source/api/v1/configuration. 

I have tried to read through previous questions/issues about authentication, and I am stuck. 

Any help would be greatly appreciated!

**Comment by vladak** [comment]
To access privileged parts of the API you need to use Bearer token. See https://github.com/oracle/opengrok/wiki/Web-services#authenticationauthorization

**Comment by bjrdeja** [comment]
Thank you @vladak ! So to confirm, in order to use a bearer token, I would add the following to my readonly-configuration.xml file:

<void property="authenticationTokens">
   <void method="add">
    <string>the-token</string>
   </void>
  </void>

Then I would run the indexer. 

And finally I would submit use the token using the header below?

curl -H "Content-Type: application/xml" -H "Authorization: Bearer the-token" "https://192.xxx.xxx.xxx:8443/source/api/v1/configuration"

Is there anything else that needs to be configured to use bearer tokens? Currently my application is authenticating using Basic HTTP Authentication based on the "Authorization-based-on-HTTP-Basic-Authentication" tutorial.

**Comment by vladak** [comment]
yep, that should work.

**Comment by Leo-Adlakha** [comment]
Hi, I tried using this, but doesn't seem to work for me. I suppose this should return my configuration. 

I followed the exact thing from here. 

> Thank you @vladak ! Should anyone need the steps to implement a bearer token, you would add the following to the readonly-configuration.xml file:
> 
> ```
> <void property="authenticationTokens">
>    <void method="add">
>     <string>the-token</string>
>    </void>
>   </void>
> ```
> 
> Then run the indexer.
> 
> And finally you would submit a request with the token using the header below?
> 
> ```
> curl -H "Content-Type: application/xml" -H "Authorization: Bearer the-token" "https://192.xxx.xxx.xxx:8443/source/api/v1/configuration"
> ```

**Comment by Leo-Adlakha** [comment]
It return me nothing, 

`username@host:<path-to-cwd>$ curl -H "Content-Type: application/xml" -H "Authorization: Bearer the-token" "https://<DNS-entry>/api/v1/configuration"`

**Comment by Leo-Adlakha** [comment]
I want to use this primarily for uploading the new config after reindexing, as currently I get some warnings when I index my sources, like - 

```
02:25:41 WARNING: Could not notify the webapp that project xxxxxx:indexed=true,history=true was indexed: InboundJaxrsResponse{context=ClientResponse{method=PUT, uri=https://<DNS-entry>/api/v1/projects/xxxxx/indexed, status=401, reason=Unauthorized}}
02:25:43 SEVERE: Failed to send configuration to https://<DNS-etntry> (is web application server running with opengrok deployed?)
java.io.IOException: InboundJaxrsResponse{context=ClientResponse{method=PUT, uri=https://<DNS-entry>/api/v1/configuration?reindex=true, status=401, reason=Unauthorized}}
        at org.opengrok.indexer.configuration.RuntimeEnvironment.writeConfiguration(RuntimeEnvironment.java:1555)
        at org.opengrok.indexer.index.Indexer.sendToConfigHost(Indexer.java:1161)
        at org.opengrok.indexer.index.Indexer.main(Indexer.java:399)

```
