### ISSUE TITLE
report FileHistoryCache hits/misses

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3509]
When getting xref of FreeBSD source file, I was surprised to see the multi-second response time. Turned out that the file was out of sync with the index. So to retrieve the last commit ID the web app executed a `git log` command (`/usr/bin/git log --find-renames=8 --diff-filter=R --summary --abbrev=8 --name-status --oneline --follow -- ...`) which was the reason for the long delay. 

```
...
        at org.opengrok.indexer.history.GitHistoryParser$RenamedFilesParser.processStream(GitHistoryParser.java:306)
        at org.opengrok.indexer.util.Executor.exec(Executor.java:230)
        at org.opengrok.indexer.history.GitHistoryParser.parse(GitHistoryParser.java:224)
        at org.opengrok.indexer.history.GitRepository.getHistory(GitRepository.java:608)
        at org.opengrok.indexer.history.GitRepository.getHistory(GitRepository.java:601)
        at org.opengrok.indexer.history.FileHistoryCache.get(FileHistoryCache.java:599)
        at org.opengrok.indexer.history.HistoryGuru.getHistory(HistoryGuru.java:264)
        at org.opengrok.web.PageConfig.getLastRevFromHistory(PageConfig.java:1319)
        at org.opengrok.web.PageConfig.getLatestRevision(PageConfig.java:1311)
        at org.apache.jsp.list_jsp._jspService(list_jsp.java:249)
...
```

Also, renamed file handling was on for this repository which contributed to the long delay. Would be handy to see the number of hits/misses in `FileHistoryCache`: https://github.com/oracle/opengrok/blob/6364b315f29d027624086909d5c04965f0abf281/opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java#L568-L576

**Comment by vladak** [comment]
The times of `readCache()` might be interesting as well.
