### ISSUE TITLE
Suggester feature rebuilding its indexes causing high load on the system

### ISSUE THREAD

**Issue by viri** [oracle/opengrok#3522]
```
opengrok version: 1.3.16

universal ctags version:

Universal Ctags 5.9.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec 22 2020, 17:47:52
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +packcc


tomcat version:
Server version: Apache Tomcat/9.0.21
Server built:   Jun 4 2019 20:19:36 UTC
Server number:  9.0.21.0
OS Name:        Linux
OS Version:     2.6.32-754.35.1.el6.x86_64
Architecture:   amd64
JVM Version:    11.0.9.1+1-LTS
JVM Vendor:     Azul Systems, Inc.


java version:

openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)


```

A few users reported slowness in the code search and I looked into the problem. What I noticed is that the system was on high load with a load average going anywhere from 50 to 100+ on a 16 CPU system , with majority of it coming from the iowait. Here is a sample reading:

```

                          CPU  %usr     %nice   %sys   %iowait    %steal  %irq  %soft    %guest   %idle
01:10:02 AM       0      9.36      0.00      6.23     81.40      0.00      0.00      0.01      0.00      3.00
01:10:02 AM       1      8.09      0.00      5.73     83.10      0.00      0.00      0.00      0.00      3.08
01:10:02 AM       2      8.95      0.00      4.81     82.50      0.00      0.00      0.00      0.00      3.74
01:10:02 AM       3      8.99      0.00      3.96     83.07      0.00      0.00      0.00      0.00      3.97
01:10:02 AM       4     11.87      0.00      6.28     79.29      0.00      0.00      0.01      0.00      2.55
01:10:02 AM       5      9.74      0.00      6.01     80.95      0.00      0.00      0.83      0.00      2.47
01:10:02 AM       6     10.50      0.00      4.72     81.12      0.00      0.00      0.00      0.00      3.66
01:10:02 AM       7      9.29      0.00      4.19     81.85      0.00      0.00      0.00      0.00      4.67
01:10:02 AM       8     11.62      0.00      9.19     76.26      0.00      0.00      0.01      0.00      2.93
01:10:02 AM       9      2.13      0.00     12.85     65.27      0.00      0.00     18.24      0.00      1.50
01:10:02 AM      10      7.47      0.00      8.31     80.97      0.00      0.00      0.00      0.00      3.25
01:10:02 AM      11      6.49      0.00      6.77     83.19      0.00      0.00      0.00      0.00      3.55
01:10:02 AM      12      9.68      0.00      6.01     81.73      0.00      0.00      0.01      0.00      2.58
01:10:02 AM      13     11.00      0.00      5.34     80.44      0.00      0.00      0.01      0.00      3.21
01:10:02 AM      14     13.58      0.00      4.24     79.03      0.00      0.00      0.00      0.00      3.15
01:10:02 AM      15     13.78      0.00      3.55     78.67      0.00      0.00      0.00      0.00      3.99

````

This was coming from the tomcat container when I verified further with iotop.

Then I see that the threadwise split of the tomcat container would show  "ForkJoinPool*" threads being the most active ones at the time:

```
top - 08:10:47 up 12 days,  2:02,  1 user,  load average: 69.41, 69.31, 69.36
Tasks: 1753 total,   1 running, 1752 sleeping,   0 stopped,   0 zombie
Cpu(s):  7.9%us,  3.6%sy,  0.0%ni, 49.2%id, 38.8%wa,  0.0%hi,  0.6%si,  0.0%st
Mem:  65971924k total, 65704752k used,   267172k free,    92204k buffers
Swap:  4128764k total,  1447628k used,  2681136k free,  9147228k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                         
32088 oguser  20   0 1243g  48g 3.4g R 100.1 77.2  34:49.15 ForkJoinPool-39                                                                                
32278 oguser  20   0 1243g  48g 3.4g D  3.7 77.2  30:20.83 ForkJoinPool-13                                                                                 
31318 oguser  20   0 1243g  48g 3.4g D  3.7 77.2   4:41.26 ForkJoinPool-39                                                                                 
26470 oguser  20   0 1243g  48g 3.4g S  1.9 77.2   1:00.19 chronicle-weak-                                                                                 
31618 oguser  20   0 1243g  48g 3.4g D  1.9 77.2  28:46.63 ForkJoinPool-12                                                                                 
31623 oguser  20   0 1243g  48g 3.4g D  1.9 77.2  28:44.06 ForkJoinPool-12  

```

I then captured a thread dump on the tomcat container and matched the hex representation  of the thread 32088 that showed up to see what it is doing and it had a stack like this:

```
"ForkJoinPool-393-worker-27" #5866 daemon prio=5 os_prio=0 cpu=1844675.46ms elapsed=29198.74s tid=0x00007f2f60194000 nid=0x7d58 runnable  [0x00007f1b0dd55000]
   java.lang.Thread.State: RUNNABLE
	at org.apache.lucene.util.fst.FST$Arc.nodeFlags(FST.java:283)
	at org.apache.lucene.util.fst.FST.readArc(FST.java:1253)
	at org.apache.lucene.util.fst.FST.readNextRealArc(FST.java:1244)
	at org.apache.lucene.util.fst.FST.readFirstRealTargetArc(FST.java:1108)
	at org.apache.lucene.util.fst.NodeHash.nodesEqual(NodeHash.java:43)
	at org.apache.lucene.util.fst.NodeHash.add(NodeHash.java:149)
	at org.apache.lucene.util.fst.Builder.compileNode(Builder.java:253)
	at org.apache.lucene.util.fst.Builder.freezeTail(Builder.java:349)
	at org.apache.lucene.util.fst.Builder.add(Builder.java:453)
	at org.apache.lucene.search.suggest.fst.WFSTCompletionLookup.build(WFSTCompletionLookup.java:130)
	at org.opengrok.suggest.SuggesterProjectData.build(SuggesterProjectData.java:262)
	at org.opengrok.suggest.SuggesterProjectData.build(SuggesterProjectData.java:249)
	at org.opengrok.suggest.SuggesterProjectData.rebuild(SuggesterProjectData.java:234)
	at org.opengrok.suggest.Suggester.lambda$getRebuildRunnable$2(Suggester.java:311)
	at org.opengrok.suggest.Suggester$$Lambda$60041/0x00007f31589ad040.run(Unknown Source)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(java.base@11.0.9.1/ForkJoinTask.java:1407)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@11.0.9.1/ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@11.0.9.1/ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(java.base@11.0.9.1/ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@11.0.9.1/ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@11.0.9.1/ForkJoinWorkerThread.java:183)
```

Suspecting that this will be suggester feature, I went into logs to see what they contain and I see log entries like these, indicating an error resulted in a rebuild to be triggered:

```
01-Apr-2021 08:41:20.472 WARNING [http-nio-8080-exec-21] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:publishing in <<<snipped path for privacy>>>
01-Apr-2021 08:41:20.489 WARNING [http-nio-8080-exec-21] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:publishing in <<<snipped path for privacy>>>
01-Apr-2021 08:41:20.491 WARNING [http-nio-8080-exec-21] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:publishing in <<<snipped path for privacy>>>
01-Apr-2021 08:41:20.493 WARNING [http-nio-8080-exec-21] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:publishing in <<<snipped path for privacy>>> **rebuild in progress**
01-Apr-2021 08:41:20.500 WARNING [http-nio-8080-exec-21] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:publishing in <<<snipped path for privacy>>>
01-Apr-2021 08:41:20.523 WARNING [http-nio-8080-exec-25] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:publishing in <<<snipped path for privacy>>>
01-Apr-2021 08:41:20.571 WARNING [http-nio-8080-exec-25] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:failed in <<<snipped path for privacy>>>
01-Apr-2021 08:41:20.641 WARNING [http-nio-8080-exec-21] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:publishing in <<<snipped path for privacy>>> **rebuild in progress**
01-Apr-2021 08:41:20.692 WARNING [http-nio-8080-exec-21] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:failed in <<<snipped path for privacy>>>
01-Apr-2021 09:08:45.598 WARNING [http-nio-8080-exec-15] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:sa in <<<snipped path for privacy>>>
01-Apr-2021 09:08:45.770 WARNING [http-nio-8080-exec-15] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:sa in <<<snipped path for privacy>>>
01-Apr-2021 09:08:45.770 WARNING [http-nio-8080-exec-15] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:sa in <<<snipped path for privacy>>>
01-Apr-2021 09:51:33.668 WARNING [http-nio-8080-exec-1] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:exception_during_app_publish in <<<snipped path for privacy>>>  **rebuild in progress**

```

These messages seem to have started at the point below but I am not seeing any issue prior to the issue:

```
29-Mar-2021 07:57:54.015 INFO [Thread-234] org.opengrok.suggest.Suggester.shutdownAndAwaitTermination Suggester successfully initialized (took 13 minutes 27 seconds)
29-Mar-2021 07:57:54.097 INFO [Thread-234] org.opengrok.web.api.v1.suggester.provider.service.impl.SuggesterServiceImpl.scheduleRebuild Scheduling suggester rebuild in PT16H2M5.984435S
29-Mar-2021 07:57:56.267 INFO [Thread-749] org.opengrok.suggest.Suggester.shutdownAndAwaitTermination Suggester successfully initialized (took 7 minutes 2 seconds)
29-Mar-2021 07:57:56.363 INFO [Thread-749] org.opengrok.web.api.v1.suggester.provider.service.impl.SuggesterServiceImpl.scheduleRebuild Scheduling suggester rebuild in PT16H2M3.732299S
29-Mar-2021 07:58:01.906 INFO [Thread-607] org.opengrok.suggest.Suggester.shutdownAndAwaitTermination Suggester successfully initialized (took 8 minutes 51 seconds)
29-Mar-2021 07:58:02.011 INFO [Thread-607] org.opengrok.web.api.v1.suggester.provider.service.impl.SuggesterServiceImpl.scheduleRebuild Scheduling suggester rebuild in PT16H1M58.093249S
29-Mar-2021 07:58:02.174 INFO [Thread-636] org.opengrok.suggest.Suggester.shutdownAndAwaitTermination Suggester successfully initialized (took 8 minutes 47 seconds)
29-Mar-2021 07:58:02.281 INFO [Thread-636] org.opengrok.web.api.v1.suggester.provider.service.impl.SuggesterServiceImpl.scheduleRebuild Scheduling suggester rebuild in PT16H1M57.825257S
29-Mar-2021 07:58:02.908 INFO [Thread-618] org.opengrok.suggest.Suggester.shutdownAndAwaitTermination Suggester successfully initialized (took 8 minutes 50 seconds)
29-Mar-2021 07:58:03.041 INFO [Thread-618] org.opengrok.web.api.v1.suggester.provider.service.impl.SuggesterServiceImpl.scheduleRebuild Scheduling suggester rebuild in PT16H1M57.090531S
29-Mar-2021 08:02:27.000 INFO [Thread-355] org.opengrok.suggest.Suggester.shutdownAndAwaitTermination Suggester successfully initialized (took 17 minutes 19 seconds)
29-Mar-2021 08:02:27.079 INFO [Thread-355] org.opengrok.web.api.v1.suggester.provider.service.impl.SuggesterServiceImpl.scheduleRebuild Scheduling suggester rebuild in PT15H57M32.995632S
29-Mar-2021 08:02:33.992 INFO [Thread-260] org.opengrok.suggest.Suggester.shutdownAndAwaitTermination Suggester successfully initialized (took 17 minutes 54 seconds)
**29-Mar-2021 08:02:34.129 INFO [Thread-260] org.opengrok.web.api.v1.suggester.provider.service.impl.SuggesterServiceImpl.scheduleRebuild Scheduling suggester rebuild in PT15H57M26.001749S
29-Mar-2021 08:04:40.033 WARNING [http-nio-8080-exec-5] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:number_of_unstructured_objects_sent_for_profiling in <<<snipped path for privacy>>>**
29-Mar-2021 08:04:40.034 WARNING [http-nio-8080-exec-5] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:number_of_unstructured_objects_sent_for_profiling in <<<snipped path for privacy>>>
29-Mar-2021 08:04:40.034 WARNING [http-nio-8080-exec-5] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:number_of_unstructured_objects_sent_for_profiling in <<<snipped path for privacy>>>
29-Mar-2021 08:04:40.035 WARNING [http-nio-8080-exec-5] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:number_of_unstructured_objects_sent_for_profiling in <<<snipped path for privacy>>>
29-Mar-2021 08:04:40.035 WARNING [http-nio-8080-exec-5] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:number_of_unstructured_objects_sent_for_profiling in <<<snipped path for privacy>>>
29-Mar-2021 08:04:40.035 WARNING [http-nio-8080-exec-5] org.opengrok.suggest.SuggesterProjectData.incrementSearchCount Cannot increment search count for unknown term full:number_of_unstructured_objects_sent_for_profiling in <<<snipped path for privacy>>>

```

One major side effect of this seems to be that the "temp" folder in the tomcat container is getting filled up with indexes like these that took up around 650GB of space, which I had to remove:

![image](https://user-images.githubusercontent.com/2963954/113437370-5e863600-939b-11eb-9144-e40b5d98eca6.png)

Currently, I removed the Suggester feature for a few large codebases.  I am attaching the information I collected for your review.
[apr-1_incident.txt](https://github.com/oracle/opengrok/files/6250582/apr-1_incident.txt)
[ogtop.txt](https://github.com/oracle/opengrok/files/6250583/ogtop.txt)

Thanks!
Vinay Chilakamarri

**Comment by ahornace** [comment]
Hi,

thanks for the detailed information. The temp files issue is probably the same as https://github.com/oracle/opengrok/issues/2857 

I'll try to look into it and implement some suggester related improvements in the coming days.

**Comment by vladak** [comment]
Yep, suggester rebuild imposes high CPU and I/O load on the system. I usually lower the number of suggester rebuild threads on a production instance like this in read-only configuration:
```xml
  <void property="suggesterConfig">
     <!-- Suggester rebuild is both CPU and I/O intensive. This usually slows down the web app significantly so lower this. -->
     <void property="rebuildThreadPoolSizeInNcpuPercent">
       <int>30</int>
     </void>
  </void>
```
However if this is visible even with sequential rebuild that happens during incremental rebuild (at least until #3347 is implemented) this will not probably help.

In the past I tried to see if the suggester thread priority could be lowered however did not find anything.

**Comment by jwehler** [comment]
Is there a way to enable the read-only config while using the docker container? Would the -R /path/to/read-only.xml get added to the INDEXER_OPT passed into the container? I tried quickly and it didn't seem to work, but wasn't sure if it was the right thing and didn't spend much time experimenting. The download/merge with read-only/update configuration mechanism seems a bit trickier with the docker env as well, but again probably user error. There are other things I'd like to add in my read-only config, so that is more general question than just the suggester thread control item.

Is the suggester property configurable with a simple curl based access? Didn't seem to like it given it was a property in a property. I can dump the current values while in the container:
```
docker exec -it opengrok curl 'http://localhost:8080/api/v1/configuration/suggesterConfig'|python -m json.tool
{
    "allowComplexQueries": true,
    "allowMostPopular": true,
    "allowedFields": [
        "defs",
        "path",
        "hist",
        "refs",
        "type",
        "full"
    ],
    "allowedProjects": null,
    "buildTerminationTime": 1800,
    "enabled": true,
    "maxProjects": 32767,
    "maxResults": 10,
    "minChars": 0,
    "rebuildCronConfig": "0 0 * * *",
    "rebuildThreadPoolSizeInNcpuPercent": 80,
    "showProjects": true,
    "showScores": false,
    "showTime": false,
    "timeThreshold": 2000
}
```
but I'm not sure how to read or tweak just the rebuildThradPoolSizeInNcpuPercent value. The documentation indicates this method only works for primitive types. https://github.com/oracle/opengrok/wiki/Read-only-configuration#real-time-web-application-change
Thanks

**Comment by vladak** [comment]
The read-only configuration in Docker needs to be revisited - #3531.

**Comment by vladak** [comment]
A note about the temp file problem (#2857): we need help with reproducing the problem.

**Comment by viri** [comment]
Some of our codebases 233GB but then they include binaries like "dll","jar", "dat" etc. So I exclude them when indexing. Regardless they are large projects. The disk issue with the suggester came down to insignificant after I disabled the suggester feature on those projects. How do I share the reproducible sample? It has to be another open-source project though.

**Comment by vladak** [comment]
Ideally, I'd like to see a reproducible sequence of steps (with input data that are public) that results in the dangling temporary files.

**Comment by vladak** [comment]
As for reducing the priority of the suggester rebuild threads, this can be done with some (pretty big) caveats:
  - https://blogs.oracle.com/dave/java-thread-priority-revisited-in-jdk7
  - https://medium.com/@vikas.singh_67409/deep-dive-into-thread-priority-in-java-be1a5da30a34
  - https://github.com/apache/druid/pull/984

however my hunch is that this will not help. Even on a system where I reduced the `rebuildThreadPoolSizeInNcpuPercent` tunable to 10, the impact of suggester rebuild is still noticeable, likely because of the I/O load as also noticed above (the `iowait`).

**Comment by vladak** [comment]
Given the environment seems to be Docker container which uses per project workflow, the high load problem is essentially a dup of #3347.
