### ISSUE TITLE
cannot generate history for Git submodules

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3666]
Setup with Git submodule described in https://github.com/oracle/opengrok/issues/3351#issuecomment-880625163 leads to NPE in `GitRepository`:
```
14:03:18 WARNING: An error occurred while creating cache for /var/opengrok/src.gitsub/main_repo/submd_repo (GitRepository)
java.lang.NullPointerException
	at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache$Table.index(UnpackedObjectCache.java:115)
	at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache$Table.contains(UnpackedObjectCache.java:76)
	at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache.isUnpacked(UnpackedObjectCache.java:31)
	at org.eclipse.jgit.internal.storage.file.LooseObjects.hasCached(LooseObjects.java:82)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObjectWithoutRestoring(ObjectDirectory.java:339)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:330)
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:132)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:212)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:917)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:827)
	at org.opengrok.indexer.history.GitRepository.accept(GitRepository.java:476)
	at org.opengrok.indexer.history.BoundaryChangesets.getBoundaryChangesetIDs(BoundaryChangesets.java:88)
	at org.opengrok.indexer.history.RepositoryWithPerPartesHistory.doCreateCache(RepositoryWithPerPartesHistory.java:85)
	at org.opengrok.indexer.history.Repository.createCache(Repository.java:411)
	at org.opengrok.indexer.history.HistoryGuru.createCache(HistoryGuru.java:556)
	at org.opengrok.indexer.history.HistoryGuru.lambda$createCacheReal$3(HistoryGuru.java:603)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
This supposedly worked prior to the JGit changes (#1113).

**Comment by vladak** [comment]
The repository detection of the submodule seems to be missing some metadata. In the generated configuration:
```xml
  <void property="repositories">
   <void method="add">
    <object class="org.opengrok.indexer.history.RepositoryInfo">
     <void property="branch">
      <string>main</string>
     </void>
     <void property="currentVersion">
      <string>2021-07-15 13:04 +0200 ed705e0 deb added submodule</string>
     </void>
     <void property="directoryNameRelative">
      <string>/main_repo</string>
     </void>
     <void property="parent">
      <string>https://github.com/debjyoti-samanta/main_repo.git</string>
     </void>
     <void property="type">
      <string>git</string>
     </void>
    </object>
   </void>
   <void method="add">
    <object class="org.opengrok.indexer.history.RepositoryInfo">
     <void property="directoryNameRelative">
      <string>/main_repo/submd_repo</string>
     </void>
     <void property="type">
      <string>git</string>
     </void>
    </object>
   </void>
  </void>
```
This is a consequence of how the submodule is structured. The `.git` is not a directory but a file (at least in this case), pointing to the parent repository:
```
/var/opengrok/src.gitsub/main_repo/submd_repo ((c43f345...))$ cat .git 
gitdir: ../.git/modules/submd_repo
```
What the `git` command does is that it goes into the parent repository and gather information there (e.g. it opens `/var/opengrok/src.gitsub/main_repo/.git/modules/submd_repo/HEAD`). JGit (at least they way it is used now) assumes that the repository is full Git repository. That's why e.g. `GitRepository#determineParent()` returns `null` - the `.git/config` file is not present for the submodule.

**Comment by vladak** [comment]
While JGit provides the `SubmoduleWalk` class to support submodules, it is more geared towards handling the submodules from the perspective of the main repository. To get the reverse functionality (needed when the indexer is performing repository scan) a bit more work has to be done which involves path handling and direct `.git` file manipulation.

**Comment by debjyoti-samanta** [comment]
Thank you so much @vladak for fixing it quickly, validate the workflow.  Working as expected.
