### ISSUE TITLE
suggester is not working

### ISSUE THREAD

**Issue by debankanroy** [oracle/opengrok#3668]
It is expected that while a project is kept selected and some string is written on any of the searchbox (Full Search, Definition etc.) a dropdown with a list of suggestion comes. This is probably known as lucene search as I am aware of.

But in my case it is not happening. Am I missing something here? Any flag I need to enable?
![issue1](https://user-images.githubusercontent.com/58889640/126055160-373d6a01-f279-4728-9e2e-c60d2d2a6aa6.PNG)

For example: In the attached snapshot, I have an indexed and selected repository "sel4" . When I am typing some function "_assert_fail" it was expected to come some dropdown containing the symbol suggestions in Definition search box on the fly.

I am able to see a small waiting circle gif at the right of the search box while typing/clicking. But there is no suggestion coming.

Opengrok Version: 1.4.5
Tomcat 8.

**Comment by ahornace** [comment]
Did it ever work before? Does it work for other terms (or fields)?

Do you see anything suspicious in the webapp logs? Or perhaps some error in the browser console?

**Comment by debankanroy** [comment]
Did it ever work before? I have not tried this before. But got to learn that this usually works.
Does it work for other terms (or fields)? No it does not work for any fields either. Default is just shown "No Matches Found"
 
Thanks for pointing to look at certain logs. Yes, I was able to capture the browser log:
{time: 1, suggestions: [], identifier: "ixzqd", queryText: "ixzqd", partialResult: true}

identifier: "ixzqd"
partialResult: true
queryText: "ixzqd"
suggestions: []
time: 1

The query text looks suspicious. This looks to be some random value is being passed in query text!


webapps log: [localhost_access_log.2021-07-18.txt](https://github.com/oracle/opengrok/files/6836345/localhost_access_log.2021-07-18.txt). Not seeing much anomaly.

**Comment by vladak** [comment]
Um, the 192.168/16 IPv4 prefix is [reserved](https://en.wikipedia.org/wiki/Reserved_IP_addresses) and thus not routable on the internet.

**Comment by debankanroy** [comment]
Ya, sorry.. it seems not accessible from outer network. Do you want me to share any other log?

**Comment by vladak** [comment]
Could you check what is sent to the web app using the Developer console in Firefox ? For reference these are the requests performed when I type some letters (`Submodule`, one by one letter) to the Definitions field on http://demo.opengrok.org (running the current code):
![suggester-demo](https://user-images.githubusercontent.com/2934284/126133978-1d6870af-3aee-4c04-bb3b-e13a1a851beb.png)

**Comment by debankanroy** [comment]
Here, I have managed to get a .HAR file. This will have the traffic info. renamed it to .TXT file as Github is not letting me upload a file with HAR extension. This might be useful?

**Search procedure:**
1. Click on Definition with "sel4" project selected
2. write one by one characters of "_assert". The existing function name is "_assert_fail"

[192.168.0.104_Archive [21-07-19 15-22-28].txt](https://github.com/oracle/opengrok/files/6839816/192.168.0.104_Archive.21-07-19.15-22-28.txt)

**Comment by vladak** [comment]
Looks normal to me except there are no suggestions returned back. Could you look into both web app and indexer logs ?

Also, if you acually perform the search for `_assert_fail` , does it actually return any result ?

**Comment by debankanroy** [comment]
Yes, after hitting enter it shows results.
Can you please let me know which logging level the indexer log is required?

**Comment by debankanroy** [comment]
For your reference..
**web apps log:** 
[localhost_access_log.2021-07-19.txt](https://github.com/oracle/opengrok/files/6840737/localhost_access_log.2021-07-19.txt)

**Indexer log:**
[opengrok1.0.log](https://github.com/oracle/opengrok/files/6840740/opengrok1.0.log)
[opengrok2.0.log](https://github.com/oracle/opengrok/files/6840741/opengrok2.0.log)
[opengrok0.0.log](https://github.com/oracle/opengrok/files/6840742/opengrok0.0.log)

**Comment by vladak** [comment]
Indexer logs look okay. Need the logs from the web app application (`catalina.out` or such).

Also, could you try this with the latest OpenGrok version ?

**Comment by vladak** [comment]
Also, what are the contents of the `/opengrok/data/suggester/seL4` directory ?

**Comment by debankanroy** [comment]
I am not seeing any suggester  directory under /opengrok/data/ itself! Only historycache, index, timestamp, xref
Does that mean suggester is not enabled? Isn't it enabled by default?

**Catalina log:** 
[catalina.txt](https://github.com/oracle/opengrok/files/6841929/catalina.txt)

**Comment by debankanroy** [comment]
I have tried enabling the suggester following [this](https://github.com/oracle/opengrok/wiki/Read-only-configuration).

**indexing command:**

opengrok-indexer     -J=-Djava.util.logging.config.file=/opengrok/etc/logging.properties     -a /opengrok/dist/lib/opengrok.jar --     -c /snap/universal-ctags/current/bin/ctags     -s /opengrok/src -d /opengrok/data -H -P -S -G **-R /opengrok/etc/readonly.xml**    -W /opengrok/etc/configuration.xml -U http://localhost:8080/source

Still not able to see the suggester directory under /opengrok/data. Am I missing something?

[readonly.zip](https://github.com/oracle/opengrok/files/6842764/readonly.zip)

**Comment by ahornace** [comment]
You can see in the logs:
```
18-Jul-2021 05:40:39.713 SEVERE [ForkJoinPool-1-worker-2] org.opengrok.suggest.Suggester.lambda$getInitRunnable$1 Could not initialize suggester data for seL4
 java.io.IOException: Could not create suggester directory /opengrok/data/suggester/seL4
	at org.opengrok.suggest.SuggesterProjectData.createSuggesterDir(SuggesterProjectData.java:282)
	at org.opengrok.suggest.SuggesterProjectData.init(SuggesterProjectData.java:153)
	at org.opengrok.suggest.Suggester.lambda$getInitRunnable$1(Suggester.java:226)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

Very probably a permissions problem. We are calling https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/File.html#mkdirs()

**Comment by debankanroy** [comment]
Hi @vladak and @ahornace  thanks a lot for your prompt support. Really appreciate!!

@ahornace you were right. This was a permission issue. The indexer was being run as root. tomcat8 as a user did not have access to create suggester directory in data. I just changed the permission of data to 777, it is working fine! One can let tomcat8/ webapps own the data directory and resolve this as well.
 
Thanks again! :+1:

**Comment by vladak** [comment]
augmented https://github.com/oracle/opengrok/wiki/How-to-setup-OpenGrok#check-permisions

**Comment by stone-wind** [comment]
an other case, at debian 12.7 even /opengrok/data/suggester/ is 777, still log Could not create suggester directory
because the default tomcat10.service has the config:
![图片](https://github.com/user-attachments/assets/2e2caad3-49ac-47dd-b5e3-638201a82f34)

it can be fixed after add ReadWritePaths=/opengrok/data/suggester/   and restart tomcat10

**Comment by liweitianux** [comment]
> an other case, at debian 12.7 even /opengrok/data/suggester/ is 777, still log Could not create suggester directory because the default tomcat10.service has the config: ![图片](https://github.com/user-attachments/assets/2e2caad3-49ac-47dd-b5e3-638201a82f34)

I'm using Debian trixie (13.4) and I can confirm this.  The tomcat10 systemd service has the following protection:

```sh
# Security
User=tomcat
Group=tomcat
PrivateTmp=yes
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
CacheDirectory=tomcat10
CacheDirectoryMode=750
ProtectSystem=strict
ReadWritePaths=/etc/tomcat10/Catalina/
ReadWritePaths=/var/lib/tomcat10/webapps/
ReadWritePaths=/var/log/tomcat10/
```

So after `chown -R tomcat:tomcat /opt/opengrok/data/suggester`, I still saw error like:

```
java.io.IOException: Could not create suggester directory '/opt/opengrok/data/suggester/xxx'
                at org.opengrok.suggest.SuggesterProjectData.createSuggesterDir(SuggesterProjectData.java:301)
                at org.opengrok.suggest.SuggesterProjectData.init(SuggesterProjectData.java:159)
                at org.opengrok.suggest.Suggester.lambda$getInitRunnable$3(Suggester.java:303)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
                at java.base/java.lang.Thread.run(Thread.java:1583)
```

Even if I manually created the `suggester/xxx` directory, it still failed with another weird error like:

```
java.io.FileNotFoundException: /opt/opengrok/data/suggester/xxx/defs.wfst (Read-only file system)
                at java.base/java.io.FileOutputStream.open0(Native Method)
                at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289)
                at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230) 
                at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:179)
                at org.opengrok.suggest.SuggesterProjectData.store(SuggesterProjectData.java:292)
                at org.opengrok.suggest.SuggesterProjectData.build(SuggesterProjectData.java:269)
                at org.opengrok.suggest.SuggesterProjectData.init(SuggesterProjectData.java:160)
                at org.opengrok.suggest.Suggester.lambda$getInitRunnable$3(Suggester.java:303)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
                at java.base/java.lang.Thread.run(Thread.java:1583)
```

> it can be fixed after add ReadWritePaths=/opengrok/data/suggester/ and restart tomcat10

A better method to modify the systemd service is to run `sudo systemctl edit tomcat10.service` and then enter:

```sh
[Service]
ReadWritePaths=/opt/opengrok/data/suggester/
```

This avoids a later package upgrade overriding the custom changes.
