### ISSUE TITLE
Suggester Permission denied *.wfst

### ISSUE THREAD

**Issue by chkp-baselz** [oracle/opengrok#3680]
Catalina.log file is full with errors like this
`21-Jul-2021 12:26:45.264 SEVERE [ForkJoinPool-1-worker-21] org.opengrok.suggest.Suggester.lambda$getInitRunnable$1 Could not initialize suggester data for sof_bal_jumbo_hf
        java.io.FileNotFoundException: /opengrok/data/suggester/sof_bal_jumbo_hf/defs.wfst (Permission denied)
                at java.base/java.io.FileOutputStream.open0(Native Method)
                at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
                at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
                at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
                at org.opengrok.suggest.SuggesterProjectData.store(SuggesterProjectData.java:273)
                at org.opengrok.suggest.SuggesterProjectData.build(SuggesterProjectData.java:250)
                at org.opengrok.suggest.SuggesterProjectData.init(SuggesterProjectData.java:154)
                at org.opengrok.suggest.Suggester.lambda$getInitRunnable$1(Suggester.java:229)
                at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
                at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
                at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
                at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
                at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
                at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
`

**Comment by ahornace** [comment]
Check the permissions of the file (r+w) `/opengrok/data/suggester/sof_bal_jumbo_hf/defs.wfst` or (its parent directories) while logging as tomcat's user.

**Comment by ahornace** [comment]
https://github.com/oracle/opengrok/wiki/How-to-setup-OpenGrok#check-permisions

**Comment by chkp-baselz** [comment]
Thank you for your help @ahornace 
I can't access with tomcat user, but I can see permissions is 766 for suggester directory, which means tomcat should w+r

**Comment by ahornace** [comment]
> I can't access with tomcat user

Try to focus on this one, it should solve the problem.
