### ISSUE TITLE
enforce maximum time for xref processing of a single file

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3698]
Indexing "prepped" (tar balls downloaded, extracted and patches applied) https://github.com/oracle/solaris-userland/ repository reveals some inefficiencies in indexing. At the end of indexing (`Progress.logLoop` reporting 99%) the indexer is spinning on the CPU. 

Checking the thread stacks, this one comes out as the most probable culprit:
```
"ForkJoinPool-1-worker-39" #81 daemon prio=5 os_prio=64 cpu=980020.53ms elapsed=1438.60s tid=0x000000000217b800 nid=0xc4 runnable  [0x00007ffd039fd000]
   java.lang.Thread.State: RUNNABLE
        at org.opengrok.indexer.analysis.javascript.JavaScriptXref.yylex(JavaScriptXref.java:1612)
        at org.opengrok.indexer.analysis.JFlexXref.write(JFlexXref.java:489)
        at org.opengrok.indexer.analysis.TextAnalyzer.writeXref(TextAnalyzer.java:82)
        at org.opengrok.indexer.analysis.plain.PlainAnalyzer.analyze(PlainAnalyzer.java:152)
        at org.opengrok.indexer.analysis.AnalyzerGuru.populateDocument(AnalyzerGuru.java:639)
        at org.opengrok.indexer.index.IndexDatabase.addFile(IndexDatabase.java:821)
        at org.opengrok.indexer.index.IndexDatabase.lambda$indexParallel$4(IndexDatabase.java:1352)
        at org.opengrok.indexer.index.IndexDatabase$$Lambda$322/0x000000080031d040.apply(Unknown Source)
        at java.util.stream.Collectors.lambda$groupingByConcurrent$59(java.base@11.0.7-internal/Collectors.java:1297)
        at java.util.stream.Collectors$$Lambda$324/0x000000080031c840.accept(java.base@11.0.7-internal/Unknown Source)
        at java.util.stream.ReferencePipeline.lambda$collect$1(java.base@11.0.7-internal/ReferencePipeline.java:575)
        at java.util.stream.ReferencePipeline$$Lambda$325/0x000000080031cc40.accept(java.base@11.0.7-internal/Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(java.base@11.0.7-internal/ForEachOps.java:183)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(java.base@11.0.7-internal/ArrayList.java:1654)
        at java.util.stream.AbstractPipeline.copyInto(java.base@11.0.7-internal/AbstractPipeline.java:484)
        at java.util.stream.ForEachOps$ForEachTask.compute(java.base@11.0.7-internal/ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(java.base@11.0.7-internal/CountedCompleter.java:746)
        at java.util.concurrent.ForkJoinTask.doExec(java.base@11.0.7-internal/ForkJoinTask.java:290)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@11.0.7-internal/ForkJoinPool.java:1020)
        at java.util.concurrent.ForkJoinPool.scan(java.base@11.0.7-internal/ForkJoinPool.java:1656)
        at java.util.concurrent.ForkJoinPool.runWorker(java.base@11.0.7-internal/ForkJoinPool.java:1594)
        at java.util.concurrent.ForkJoinWorkerThread.run(java.base@11.0.7-internal/ForkJoinWorkerThread.java:177)
```

Checking the opened files by the indexer I see `/ws-local/solaris-userland/components/desktop/firefox/firefox-78.11.0/testing/modules/sinon-7.2.7.js`. The file contains some very long lines (with e.g. 118709 characters) so this is very similar to #3447.

I think this needs a fix in both the JS analyzer as well as a more generic approach. This issue tracks the latter. Similarly to the ctags processing, if a xref cannot be generated for given file in time, the processing should be terminated (thread canceled) and the file ignored.

**Comment by vladak** [comment]
For the record, in this particular case the processing of this file takes almost 1 hour (and this is a virtual CPU in OCI with the `VM.Standard.E3.Flex` shape which is based on recent AMD CPUs so nothing shabby):
```
2021-08-11 17:09:02.980+0000 FINE t40 DefaultIndexChangedListener.fileAdd: Add: /solaris-userland/components/desktop/firefox/firefox-78.11.0/testing/modules/sinon-7.2.7.js (JavaScriptAnalyzer)
2021-08-11 18:01:04.217+0000 FINER t40 DefaultIndexChangedListener.fileAdded: Added: /solaris-userland/components/desktop/firefox/firefox-78.11.0/testing/modules/sinon-7.2.7.js (JavaScriptAnalyzer)
```

**Comment by vladak** [comment]
The lexer is called via `populateDocument()` which is called from `IndexDatabase#addFile()`. The `addFile()` is called from a thread in `indexParallel()` like so: https://github.com/oracle/opengrok/blob/7f430e467c592672b420a552530c6e091e5b87f3/opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java#L1339-L1355

So this will be done in a thread thanks to the fork-join pool. Quick and dirty solution (possibly at the expense of creating another thread) would be to wrap the xref processing inside a time-out thread or use https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/CompletableFuture.html#orTimeout-long-java.util.concurrent.TimeUnit- as suggester on https://stackoverflow.com/a/47028509/11582827

**Comment by vladak** [comment]
There is a bit of a trouble with nesting - the `doCtags()` is called from `PlainAnalyzer#analyze()` so wrapping the `fa.analyze()` call in `populateDocument()` would wrap also the ctags processing. Perhaps moving the timeout wrap up to `populateDocument()` would make sense. Or wrap the `writeXref()` call inside `PlainAnalyzer#analyze()` which happens to be done after ctags processing: https://github.com/oracle/opengrok/blob/7f430e467c592672b420a552530c6e091e5b87f3/opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/plain/PlainAnalyzer.java#L152

This way there coulld be separate timeout tunable for xref processing.
