### ISSUE TITLE
opengrok.deploy ImportError: cannot import name 'util'

### ISSUE THREAD

**Issue by AvatarKory** [oracle/opengrok#3703]
I had OpenGrok 1.7.16 snap installed on Ubuntu 20.04 and everything was working fine. Sometime later, I had to upgrade my system to Python 3.9. Later on, I added more source code to be indexed, when I ran opengrok.indexer, I got the python error in the title. So I snap removed and snap installed OpenGrok again, and I still see this error:
```
$ sudo /snap/bin/opengrok.deploy
Traceback (most recent call last):
  File "/snap/opengrok/896/opengrok-tools/bin/opengrok-deploy", line 11, in <module>
    load_entry_point('opengrok-tools==1.7.16', 'console_scripts', 'opengrok-deploy')()
  File "/snap/opengrok/896/opengrok-tools/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/snap/opengrok/896/opengrok-tools/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/snap/opengrok/896/opengrok-tools/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/snap/opengrok/896/opengrok-tools/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/snap/opengrok/896/opengrok-tools/lib/python3.6/site-packages/opengrok_tools/deploy.py", line 32, in <module>
    from .utils.log import get_console_logger, get_class_basename, \
  File "/snap/opengrok/896/opengrok-tools/lib/python3.6/site-packages/opengrok_tools/utils/__init__.py", line 2, in <module>
    from . import commandsequence
  File "/snap/opengrok/896/opengrok-tools/lib/python3.6/site-packages/opengrok_tools/utils/commandsequence.py", line 29, in <module>
    from .utils import is_web_uri
  File "/snap/opengrok/896/opengrok-tools/lib/python3.6/site-packages/opengrok_tools/utils/utils.py", line 30, in <module>
    from distutils import util
ImportError: cannot import name 'util'
```
Any solution to this problem?

**Comment by AvatarKory** [comment]
I just tried run opengrok.indexer on another Linux machine running Ubuntu 18.04, and I am getting the same error. I was successfully running OpenGrok on this machine for over 2 years. What could have possibly changed?

**Comment by vladak** [comment]
[strtobool()](https://docs.python.org/3/distutils/apiref.html#distutils.util.strtobool) from distutils is needed in `tools/src/main/python/opengrok_tools/utils/utils.py ` to convert string to boolean value: https://github.com/oracle/opengrok/blob/a840d4e0a51644f01cec6d36d31156074cc8ec8d/tools/src/main/python/opengrok_tools/utils/utils.py#L113

The failure to import could mean the distutils **package** is not installed: https://askubuntu.com/a/1260519 because
> Debian has decided that distutils is not a core python package, so it is not included in the last versions of debian and debian-based OSes. You should be able to do sudo apt install python3-distutils and it should work.

So this seems primarily like a problem of the _snap_ environment (which is external to the OpenGrok project; in fact this is the first time I hear about OpenGrok being distributed as a snap package) that stems from the Debian packaging choice. Alternatively, we can avoid `distutils.util.strtobool` and use something else - either spin our own version or use one of the alternatives as described in some of the answers on https://stackoverflow.com/questions/715417/converting-from-a-string-to-boolean-in-python however that sounds like a bit of a stretch as we would have to worry about using anything else from distutils. Given distutils is considered by Python itself as core package, it cannot be installed via `pip`.
