### ISSUE TITLE
Indexing opengrok with peforce repo

### ISSUE THREAD

**Issue by sahoode** [oracle/opengrok#3708]
I have setup a new opengrok instance, with few perforce repository
I get the below error.
```
WARNING: Non-zero exit status 1 from command [p4 dirs $'*'] in directory /var/opengrok/src/margot/c2c-git/tools/apache-maven-3.0.5/lib: Perforce client error:
	Connect to server failed; check $P4PORT.
	TCP connect to perforce:1666 failed.
	connect: perforce:1666: Cannot assign requested address
```

and nothing is getting indexed.

Please help to solve this I uses index command as.
```
java -verbose -Djava.util.logging.config.file=/var/opengrok/logging.properties \
    -jar /var/opengrok/dist/opengrok.jar \
    -c /usr/bin/ctags \
    -s /var/opengrok/src/margot/ -d /var/opengrok/data/ -H -S -G -P \
    -i *.o -i *.a -i *.so -i *.d -i *.gz -i *.p -i *.cmd -i *.la -i *.lo -i *.html -i *.gif -i *.png -i *.pyc \
    -W /var/opengrok/etc/configuration.xml \
    -U http://localhost:8080/source
```

Tomcat has below error 
```
04-Sep-2021 18:56:37.462 WARNING [invalidate-repos-90] org.opengrok.indexer.history.SubversionRepository.determineCurrentVersion cannot get current version info for /var/opengrok/src/margot/FCS8.3.X.0/cmn/protobuf-c-0.15/scripts
04-Sep-2021 18:56:37.543 SEVERE [invalidate-repos-89] org.opengrok.indexer.util.Executor.exec Failed to read from process: svn
	java.io.IOException: An error occurred while parsing the xml output
		at org.opengrok.indexer.history.SubversionHistoryParser.processStream(SubversionHistoryParser.java:227)
		at org.opengrok.indexer.util.Executor.exec(Executor.java:226)
		at org.opengrok.indexer.history.SubversionHistoryParser.parse(SubversionHistoryParser.java:198)
		at org.opengrok.indexer.history.SubversionRepository.getHistory(SubversionRepository.java:289)
		at org.opengrok.indexer.history.SubversionRepository.determineCurrentVersion(SubversionRepository.java:409)
		at org.opengrok.indexer.history.RepositoryFactory.getRepository(RepositoryFactory.java:238)
		at org.opengrok.indexer.history.RepositoryFactory.getRepository(RepositoryFactory.java:155)
		at org.opengrok.indexer.history.RepositoryFactory.getRepository(RepositoryFactory.java:278)
		at org.opengrok.indexer.history.HistoryGuru.lambda$invalidateRepositories$5(HistoryGuru.java:830)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:834)
	Caused by: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 1; XML document structures must start and end within the same entity.
		at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
```

**Comment by oacnhpkqxjhufwumkkqnshvlmheokqv** [comment]
Hey, do you set the environment variable P4PORT=[Your perforce server address] anywhere?

**Comment by sahoode** [comment]
Yes P4PORT is is labeled.
It seems to work after removing the complete data folder and configuration file then reindexing.
