### ISSUE TITLE
setting new configuration should be asynchronous

### ISSUE THREAD

**Issue by ChristopheBordieu** [oracle/opengrok#3771]
Hi team,

Looking at:
https://github.com/oracle/opengrok/blob/0e4c55544f8ea0a68e8bae37b0e502097e008ec1/opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java#L1433
it seems that at the end of the indexing process, when new configuration file is ready and has been written, it is sent to webapp without being compressed.

If I am right, would it be possible the PUT request compresses the file (as much as possible) when sending it?
I guess that could be done updating the request header with the directive: _Content-Encoding: gzip_. 

My current configuration file is ~20M and the configuration sending request takes long time. This could help decrease this time (and so limit the risk of a timeout or a connection loss).

Regards,
Christophe

**Comment by ahornace** [comment]
> My current configuration file is ~20M and the configuration sending request takes long time. This could help decrease this time (and so limit the risk of a timeout or a connection loss).

I think in generic use-cases the indexer and the webapp are mostly on the same hosts or the configuration does not get so big. Just curious, why is it taking a long time for you? Do you have indexer and webapp in different DCs?

**Comment by vladak** [comment]
> My current configuration file is ~20M and the configuration sending request takes long time.

How long does it take exactly ? Are you sure that it's the network transfer that constitutes most of the time ? How do the network parameters look like ? (bandwidth, latency, pkt loss etc.)

**Comment by ChristopheBordieu** [comment]
Hi @ahornace  and @vladak 

> I think in generic use-cases the indexer and the webapp are mostly on the same hosts...

Yes, indexer and webapp are running on same VM. Configuration file is sent to localhost:8080.

>Just curious, why is it taking a long time for you?
>How long does it take exactly ?

No idea,. It takes around 29 minutes.

> Are you sure that it's the network transfer that constitutes most of the time ? 

No, I am not sure. That's why I have opened this ticket :-)
Maybe this is the update of the webapp itself, once the new configuration file has been received, that takes long time.
But i don't know how to check that. Any advices or commands to run?

Log of the nightly run:

```
01:06:48 INFO: Writing configuration to /srv/opengrok-var/etc/configuration.xml
01:06:59 INFO: Done...
01:06:59 INFO: Sending configuration to: http://localhost:8080
01:07:05 FINEST: Loading next object: org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory
01:07:05 FINER: Created ServiceLocator ServiceLocatorImpl(__HK2_Generated_1990,1990,1249721273)
01:07:05 FINE: Clearing Jersey HK2 caches. Service cache size: 3, reflection cache size: 20.
01:07:05 FINEST: Loading next class: org.glassfish.jersey.logging.LoggingFeatureAutoDiscoverable
01:07:05 FINEST: Loading next class: org.glassfish.jersey.internal.config.ExternalPropertiesAutoDiscoverable
01:07:05 FINEST: Loading next class: org.glassfish.jersey.server.filter.internal.ServerFiltersAutoDiscoverable
01:07:05 FINEST: Loading next class: org.glassfish.jersey.jackson.internal.JacksonAutoDiscoverable
01:07:05 FINEST: Loading next class: org.glassfish.jersey.server.validation.internal.ValidationAutoDiscoverable
01:07:05 FINEST: Loading next class: org.glassfish.jersey.server.wadl.internal.WadlAutoDiscoverable
01:07:05 FINEST: Loading next class: org.glassfish.jersey.server.internal.monitoring.MonitoringAutodiscoverable
01:07:05 FINER: System properties configuration provider not allowed
01:07:05 FINE: null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.client.ClientExecutorProvidersConfigurator.lookupManagedScheduledExecutorService(ClientExecutorProvidersConfigurator.java:172)
	at org.glassfish.jersey.client.ClientExecutorProvidersConfigurator.init(ClientExecutorProvidersConfigurator.java:122)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:457)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:819)
	at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:176)
	at org.glassfish.jersey.client.ClientRequest.getInjectionManager(ClientRequest.java:567)
	at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:199)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38)
	at org.opengrok.indexer.configuration.RuntimeEnvironment.writeConfiguration(RuntimeEnvironment.java:1450)
	at org.opengrok.indexer.index.Indexer.sendToConfigHost(Indexer.java:1161)
	at org.opengrok.indexer.index.Indexer.main(Indexer.java:387)
Caused by: javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or in an application resource file: java.naming.factory.initial
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:691)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at java.naming/javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:342)
	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
	... 16 more

01:07:05 CONFIG: Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
01:07:05 CONFIG: Selected ScheduledExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientBackgroundSchedulerProvider] to be used for injection of scheduler qualified by [org.glassfish.jersey.client.ClientBackgroundScheduler] annotation.
01:07:05 CONFIG: Restricted headers are not enabled using [sun.net.http.allowRestrictedHeaders] system property (setting only takes effect on connections created after the property has been set/changed).
01:07:05 FINEST: ProxySelector Request for http://localhost:8080/api/v1/configuration?reindex=true
01:07:05 FINEST: Proxy used: DIRECT
01:07:05 FINE: sun.net.www.MessageHeader@3bfa9e447 pairs: {PUT /api/v1/configuration?reindex=true HTTP/1.1: null}{Content-Type: application/xml}{User-Agent: Jersey/3.0.2 (HttpUrlConnection 11.0.9)}{Host: localhost:8080}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}{Content-Length: 22587378}
01:36:07 FINE: sun.net.www.MessageHeader@494e18e14 pairs: {null: HTTP/1.1 204}{Date: Mon, 22 Nov 2021 01:36:07 GMT}{Keep-Alive: timeout=20}{Connection: keep-alive}
01:36:07 INFO: Configuration update routine done, check log output for errors.
01:36:07 FINE: Destroying ctags command
...
```

**Comment by vladak** [comment]
29 minutes is hardly spent on transferring 20 MiB over loopback. What is likely happening is that the web application is rebuilding new configuration and given that this particular API call is synchronous, it returns only after the new configuration is set in place. See the web app logs, there might be some details there.

**Comment by ChristopheBordieu** [comment]
From Tomcat log:
```
22-Nov-2021 01:12:07.000 INFO [http-nio-8080-exec-44] org.opengrok.indexer.configuration.RuntimeEnvironment.applyConfig Configuration updated
22-Nov-2021 01:36:07.402 INFO [http-nio-8080-exec-44] org.opengrok.indexer.configuration.WatchDogService.stop Watchdog stopped
```
So, after 5 minutes, configuration seems to be updated. 
What is the second line?
Should I set Tomcat to a finer logging level?

**Comment by vladak** [comment]
Raising the log level would tell more I believe. The `WatchDogService` is only relevant in certain configurations with authorization plugins.

**Comment by ChristopheBordieu** [comment]
Any package? Or only org.opengrok ones?

**Comment by vladak** [comment]
`org.opengrok` should be fine, https://github.com/oracle/opengrok/wiki/Debugging#web-application confirms.

**Comment by ChristopheBordieu** [comment]
OK. That's done (added org.opengrok.level = ALL into Catalina logging properties file) and webapp has been restarted.
After repo invalidation step, there is an index check. Maybe it is this one that takes time on our case. Let's wait for next night run...

**Comment by vladak** [comment]
> My current configuration file is ~20M and the configuration sending request takes long time. This could help decrease this time (and so limit the risk of a timeout or a connection loss).

One way of addressing this would be to make the API call asynchronous (similar to e.g. #3686)

**Comment by ChristopheBordieu** [comment]
Hello,

Nothing special in the Tomcat log during this night indexing.

Indexer log:
```
00:37:23 INFO: Done...
00:37:23 INFO: Sending configuration to: http://localhost:8080
00:37:29 FINEST: Loading next object: org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory
00:37:29 FINER: Created ServiceLocator ServiceLocatorImpl(__HK2_Generated_1991,1991,135120667)
00:37:29 FINE: Clearing Jersey HK2 caches. Service cache size: 3, reflection cache size: 20.
00:37:29 FINEST: Loading next class: org.glassfish.jersey.logging.LoggingFeatureAutoDiscoverable
00:37:29 FINEST: Loading next class: org.glassfish.jersey.internal.config.ExternalPropertiesAutoDiscoverable
00:37:29 FINEST: Loading next class: org.glassfish.jersey.server.filter.internal.ServerFiltersAutoDiscoverable
00:37:29 FINEST: Loading next class: org.glassfish.jersey.jackson.internal.JacksonAutoDiscoverable
00:37:29 FINEST: Loading next class: org.glassfish.jersey.server.validation.internal.ValidationAutoDiscoverable
00:37:29 FINEST: Loading next class: org.glassfish.jersey.server.wadl.internal.WadlAutoDiscoverable
00:37:29 FINEST: Loading next class: org.glassfish.jersey.server.internal.monitoring.MonitoringAutodiscoverable
00:37:29 FINER: System properties configuration provider not allowed
00:37:29 FINE: null
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.jersey.client.ClientExecutorProvidersConfigurator.lookupManagedScheduledExecutorService(ClientExecutorProvidersConfigurator.java:172)
        at org.glassfish.jersey.client.ClientExecutorProvidersConfigurator.init(ClientExecutorProvidersConfigurator.java:122)
        at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:457)
        at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
        at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:819)
        at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:176)
        at org.glassfish.jersey.client.ClientRequest.getInjectionManager(ClientRequest.java:567)
        at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371)
        at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:199)
        at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38)
        at org.opengrok.indexer.configuration.RuntimeEnvironment.writeConfiguration(RuntimeEnvironment.java:1450)
        at org.opengrok.indexer.index.Indexer.sendToConfigHost(Indexer.java:1161)
        at org.opengrok.indexer.index.Indexer.main(Indexer.java:387)
Caused by: javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or in an application resource file: java.naming.factory.initial
        at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:691)
        at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
        at java.naming/javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:342)
        at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
        ... 16 more

00:37:29 CONFIG: Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
00:37:29 CONFIG: Selected ScheduledExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientBackgroundSchedulerProvider] to be used for injection of scheduler qualified by [org.glassfish.jersey.client.ClientBackgroundScheduler] annotation.
00:37:29 CONFIG: Restricted headers are not enabled using [sun.net.http.allowRestrictedHeaders] system property (setting only takes effect on connections created after the property has been set/changed).
00:37:30 FINEST: ProxySelector Request for http://localhost:8080/api/v1/configuration?reindex=true
00:37:30 FINEST: Proxy used: DIRECT
00:37:30 FINE: sun.net.www.MessageHeader@28be164b7 pairs: {PUT /api/v1/configuration?reindex=true HTTP/1.1: null}{Content-Type: application/xml}{User-Agent: Jersey/3.0.2 (HttpUrlConnection 11.0.9)}{Host: localhost:8080}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}{Content-Length: 22608564}
01:07:10 FINE: sun.net.www.MessageHeader@3fe31c534 pairs: {null: HTTP/1.1 204}{Date: Tue, 23 Nov 2021 01:07:09 GMT}{Keep-Alive: timeout=20}{Connection: keep-alive}
01:07:10 INFO: Configuration update routine done, check log output for errors.
01:07:10 FINE: Destroying ctags command
```
Tomcat log:
```
23-Nov-2021 00:37:34.673 FINE [http-nio-8080-exec-27] org.opengrok.indexer.history.HistoryGuru.invalidateRepositories invalidating 32,451 repositories
[Logs regarding hg repositories. Will open a ticket dedicated to these messages I am surprised to see.]
23-Nov-2021 00:42:08.114 INFO [http-nio-8080-exec-27] org.opengrok.indexer.util.Statistics.logIt done invalidating 32451 repositories (took 0:04:33)
23-Nov-2021 00:42:22.010 INFO [http-nio-8080-exec-27] org.opengrok.indexer.configuration.RuntimeEnvironment.applyConfig Configuration updated
23-Nov-2021 01:07:10.285 INFO [http-nio-8080-exec-27] org.opengrok.indexer.configuration.WatchDogService.stop Watchdog stopped
23-Nov-2021 01:07:10.296 WARNING [http-nio-8080-exec-27] org.opengrok.indexer.framework.PluginFramework.reload Plugin directory not found or not readable: /srv/opengrok-var/../plugins. All requests allowed.
23-Nov-2021 01:07:10.296 FINE [http-nio-8080-exec-27] org.opengrok.web.api.v1.suggester.provider.service.impl.SuggesterServiceImpl.refresh Refreshing suggester for new configuration org.opengrok.indexer.configuration.SuggesterConfig@f2ac8400
23-Nov-2021 01:07:10.297 INFO [http-nio-8080-exec-27] org.opengrok.web.api.v1.suggester.provider.service.impl.SuggesterServiceImpl.initSuggester Suggester disabled
```

**Comment by vladak** [comment]
The API endpoint to set new configuration is just 2 calls: https://github.com/oracle/opengrok/blob/25e5d9bb7222938228ecb6e57eb56cabc9932f2f/opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ConfigurationController.java#L62-L63

I believe the latter is asynchronous since `SuggesterServiceImpl#initSuggester()` merely spawns a thread and returns.

Now, from the logs we know that `applyConfig()` took some 4 and half minutes: https://github.com/oracle/opengrok/blob/25e5d9bb7222938228ecb6e57eb56cabc9932f2f/opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java#L1705-L1707

The repository invalidation itself took 4:33 minutes (not bad considering the number of repositories). That is way too long for API call so by itself it warrants the conversion to asynchronous handling.

According to the logs, the `reindex` request parameter is set to true so this block will run then: https://github.com/oracle/opengrok/blob/25e5d9bb7222938228ecb6e57eb56cabc9932f2f/opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java#L1709-L1717 and it is possible that this is taking the rest of the time, specifically the call to `maybeRefreshIndexSearchers()` that calls into Lucene's `SearcherManager#maybeRefresh()`. Other than that the rest of `applyConfig()` does not include anything that could run for a long time, I think.

**Comment by ChristopheBordieu** [comment]
Should I increase Tomcat log for Lucene too (org.apache.lucene)? Or even org.apache for Lucene and Tomcat?

**Comment by vladak** [comment]
> Should I increase Tomcat log for Lucene too (org.apache.lucene)? Or even org.apache for Lucene and Tomcat?

I don't think this will do anything as this area of code in Lucene does not log at all. I've just submitted PR #3786 to log the time needed to refresh the search managers so it would be good to run with that.
