### ISSUE TITLE
suggester rebuild still blocks webapp redeploy

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3783]
Deploying on 1.7.23 to web app running 1.7.19 I ran into #3395 even though it should be fixed. It seems #3396 did not help.

**Comment by vladak** [comment]
The main trouble seems that the `Suggester#close()` is called only after all the outstanding suggester rebuilds are done so the `terminating` flag is still set to false.

**Comment by vladak** [comment]
The `firstReader` field of the `writerLock` is: `Thread[ForkJoinPool.commonPool-worker-7,5,main]` which is a thread that does the rebuild:
```
"ForkJoinPool.commonPool-worker-7@9829" daemon prio=5 tid=0xc4 nid=NA waiting
  java.lang.Thread.State: WAITING
	 blocks ForkJoinPool.commonPool-worker-3@9691
	 blocks ForkJoinPool.commonPool-worker-5@9804
	 blocks ForkJoinPool.commonPool-worker-9@9831
	 blocks ForkJoinPool.commonPool-worker-11@9833
	 blocks ForkJoinPool.commonPool-worker-13@9835
	 blocks ForkJoinPool.commonPool-worker-15@9836
	  at java.lang.Object.wait(Object.java:-1)
	  at java.util.concurrent.ForkJoinPool.awaitTermination(ForkJoinPool.java:2954)
	  at org.opengrok.suggest.Suggester.shutdownAndAwaitTermination(Suggester.java:265)
	  at org.opengrok.suggest.Suggester.rebuild(Suggester.java:310)
	  - locked <0x64c3> (a java.lang.Object)
	  at org.opengrok.web.api.v1.suggester.provider.service.impl.SuggesterServiceImpl.rebuild(SuggesterServiceImpl.java:210)
	  at org.opengrok.web.api.v1.controller.ProjectsController.lambda$markIndexed$3(ProjectsController.java:289)
	  at org.opengrok.web.api.v1.controller.ProjectsController$$Lambda$4847.2098864767.run(Unknown Source:-1)
```
and therefore owns the read lock and is waiting for the job to complete while holding the RW lock (#3347). It seems that the thread scheduler prefers readers, because the writer gets the lock only after the rebuilds are done.
