### ISSUE TITLE
Is clicable URL available into Messages?

### ISSUE THREAD

**Issue by ChristopheBordieu** [oracle/opengrok#3914]
Hi team

When using REST API _/api/v1/messages_ to create messages, is it possible to include into the text an URL that could be clickable when rendered by the app?

**Comment by vladak** [comment]
This is a two part question really. First, how to display a link. Second, how to actually click on the link :-)

Let's go with the first part first:

The way it works currently is that Messages are converted to JSON and stored in a `span` element, for example https://github.com/oracle/opengrok/blob/741f2ca748bced36c85914d3fd2f83e63165879e/opengrok-web/src/main/webapp/mast.jsp#L114-L115

then the JS code interprets these and displays using https://github.com/oracle/opengrok/blob/741f2ca748bced36c85914d3fd2f83e63165879e/opengrok-web/src/main/webapp/js/utils-0.0.45.js#L1117

The [html()](https://api.jquery.com/html/#html2) consumes the HTML content just fine and I have just verified it works, at least for messages with the `main` tag (that makes the message to appear on the index page). For project-level message this does not work (the exclamation mark is printed next to the project however no hover action) which I guess is a bug.

Now, for the second part, the message is displayed in a floating window which may disappear once the mouse is out. I don't know how to successfully chase the window every time, maybe there is some browser trick ?

**Comment by vladak** [comment]
The hover action for a project with message text that has HTML inside leads to an error on the Web developer console in FF:
```
Uncaught TypeError: f.messages is undefined
    update http://localhost:8080/source/js/utils-0.0.44.min.js:43
    fire http://localhost:8080/source/js/utils-0.0.44.min.js:22
    update http://localhost:8080/source/js/utils-0.0.44.min.js:26
    onInitialized http://localhost:8080/source/js/utils-0.0.44.min.js:55
    jQuery 3
        handle
        dispatch
        handle
```

I think the reason is that the `window-header` and `window-body` `<div>` elements underneath the `messages_win` `<div>` element are empty when a message text contains HTML elements.

**Comment by vladak** [comment]
For the record, the JSON file used for the API call looks like this:
```json
{
  "tags": [
    "Hello"
  ],
  "messageLevel": "info",
  "text": "<a href=\"http://localhost:8080\">test message</a>",
  "duration": "PT10M"
}
```

**Comment by vladak** [comment]
Looking inside the HTML the message in  the `data-messages` attribute appears like so:
```json
[{"tag":"Hello","messages":[{"expired":false,"created":"2022 Mar 31 11:55:53 CEST","text":"<a href="http://localhost:8080">test message</a>","tags":["Hello"],"messageLevel":"info","expiration":"2022 Mar 31 12:05:53 CEST"}]}]
```
Looks like the double quote escapes got lost along the way and possibly this is causing the problem.

**Comment by ChristopheBordieu** [comment]
Hi @vladak 

Thanks for looking at this.
I have not tried to set link at main level. I am only trying a project level (to allow users to easily jump to our Git project servers).

When I put the mouse over the icon, I have this in Chrome:
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Object.update (utils-0.0.43.min.js:43:193)
    at h.fire (utils-0.0.43.min.js:22:306)
    at S.fn.init.g.update (utils-0.0.43.min.js:26:277)
    at HTMLSpanElement.<anonymous> (utils-0.0.43.min.js:62:358)
    at HTMLSpanElement.handle (jquery.min.js:2:46499)
    at HTMLSpanElement.dispatch (jquery.min.js:2:43064)
    at HTMLSpanElement.v.handle (jquery.min.js:2:41048)
Maybe it helps.

**Comment by ChristopheBordieu** [comment]
> I think that's basically the same error I am seeing in FF.

Sure.

FYI. 
With Chrome, using Debugger, editing the `data-messages` attribute, I was able  to format correctly the link so that the Messages Window was displayed OK and link clickable easily. I was not able to reproduce this edit successfully just after! I don't know why...
I also tried to set message with link at main scope and it failed too.
