### ISSUE TITLE
org.opensolaris.opengrok.index.IndexDatabase indexDown WARNING: Failed to add file /jdk/com/sun/jndi/dns/ListTests/ListInteriorNotFound.dns

### ISSUE THREAD

**Issue by maestropandy** [oracle/opengrok#3973]
Running on opengrok-1.0-v3, while running indexer hitting below error 

`Jun 20, 2022 5:02:05 AM org.opensolaris.opengrok.index.DefaultIndexChangedListener fileAdd
INFO: Add: //test/jdk/com/sun/jndi/dns/ListTests/ListInteriorNotFound.dns (PlainAnalyzer)
Jun 20, 2022 5:02:15 AM org.opensolaris.opengrok.index.IndexDatabase indexDown
WARNING: Failed to add file /opengrok/home/source//test/jdk/com/sun/jndi/dns/ListTests/ListInteriorNotFound.dns
org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
        at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:747)
        at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:761)
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1565)
        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1314)
        at org.opensolaris.opengrok.index.IndexDatabase.addFile(IndexDatabase.java:635)
        at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:883)
        at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
        at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
        at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
        at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
        at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
        at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
        at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
        at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:397)
        at org.opensolaris.opengrok.index.IndexDatabase$2.run(IndexDatabase.java:184)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.NoSuchFileException: /opengrok/home/data/index/jdk/_2a.fdx
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.Files.size(Files.java:2332)
        at org.apache.lucene.store.FSDirectory.fileLength(FSDirectory.java:243)
        at org.apache.lucene.index.SegmentCommitInfo.sizeInBytes(SegmentCommitInfo.java:209)
        at org.apache.lucene.index.DocumentsWriterPerThread.sealFlushedSegment(DocumentsWriterPerThread.java:521)
        at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:481)
        at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:539)
        at org.apache.lucene.index.DocumentsWriter.postUpdate(DocumentsWriter.java:396)
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:499)
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1569)`

**Comment by vladak** [comment]
As discussed on internal Slack, there is very little change of getting support for old and older releases. Closing as dup of #2122.
