### ISSUE TITLE
IndexNotFoundException exception with empty data directory on webapp startup

### ISSUE THREAD

**Issue by mishka81** [oracle/opengrok#3980]
I have Cp1252 encoded Java files, but because the indexer is assuming files are UTF-8, I want to set the character encoding of the JVM running the indexer with -Dfile.encoding=Cp1252

To achieve that I use   INDEXER_OPT="-J=-Dfile.encoding=Cp1252" as environment variable in my docker-compose.yml.
Running with a  fresh and cleaned data folder, I have the following error at startup :

```
opengrok  | Running version 1.7.32
opengrok  | synchronization period = 1440 minutes
opengrok  | Deploying web application
opengrok  | extra indexer options: "-J=-Dfile.encoding=Cp1252"
opengrok  | Creating bare configuration in /opengrok/etc/configuration.xml
opengrok  | Jul 01, 2022 5:29:54 PM org.opengrok.indexer.index.Indexer parseOptions
opengrok  | INFO: Indexer options: [-s, /opengrok/src, -d, /opengrok/data, -c, /usr/local/bin/ctags, --remote, on, -H, -S, -W, /opengrok/etc/configuration.xml, --noIndex, "-J=-Dfile.encoding=Cp1252", -P]
opengrok  | Jul 01, 2022 5:29:54 PM org.opengrok.indexer.index.Indexer main
opengrok  | WARNING: The collection of entries to process is non empty ([/"-J=-Dfile.encoding=Cp1252", /-P]), seems like the intention is to perform per project reindex, however the -W option is used. This will likely not work.
opengrok  | Jul 01, 2022 5:29:54 PM org.opengrok.indexer.index.Indexer main
opengrok  | INFO: Indexer version 1.7.32 (1a2ed5cf92e80419ef690aef909685020d04e0e7) running on Java 11.0.15
opengrok  | Jul 01, 2022 5:29:54 PM org.opengrok.indexer.util.CtagsUtil validate
opengrok  | INFO: Using ctags: Universal Ctags 5.9.0(227c65e7), Copyright (C) 2015-2022 Universal Ctags Team
opengrok  | Universal Ctags is derived from Exuberant Ctags.
opengrok  | Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
opengrok  |   Compiled: Jun  8 2022, 19:21:28
opengrok  |   URL: https://ctags.io/
opengrok  |   Optional compiled features: +wildcards, +regex, +gnulib_regex, +iconv, +option-directory, +packcc, +optscript
opengrok  | Jul 01, 2022 5:29:54 PM org.opengrok.indexer.index.Indexer prepareIndexer
opengrok  | INFO: Scanning for repositories in [/opengrok/src/A.git, /opengrok/src/B.git] (down to 2 levels below source root)
opengrok  | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
opengrok  | SLF4J: Defaulting to no-operation (NOP) logger implementation
opengrok  | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
opengrok  | Jul 01, 2022 5:29:54 PM org.opengrok.indexer.util.Statistics logIt
opengrok  | INFO: Done scanning for repositories, found 2 repositories (took 271 ms)
opengrok  | Jul 01, 2022 5:29:54 PM org.opengrok.indexer.index.Indexer writeConfigToFile
opengrok  | INFO: Writing configuration to /opengrok/etc/configuration.xml
opengrok  | Jul 01, 2022 5:29:54 PM org.opengrok.indexer.index.Indexer writeConfigToFile
opengrok  | INFO: Done writing configuration to /opengrok/etc/configuration.xml
opengrok  | Jul 01, 2022 5:29:54 PM org.opengrok.indexer.util.Statistics logIt
opengrok  | INFO: Indexer finished (took 707 ms)
opengrok  | Number of sync workers: 4
opengrok  | Checking mirror configuration in '/opengrok/etc/mirror.yml'
opengrok  | Waiting for Tomcat to start
opengrok  | Starting REST app on port 5000
opengrok  | Sleeping for 86400 seconds
opengrok  | Starting Tomcat
opengrok  | NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
opengrok  | 01-Jul-2022 17:29:55.323 WARNING [main] org.apache.tomcat.util.digester.Digester.endElement No rules found matching [Server/Service/Engine/Host/Disabled]
opengrok  | 01-Jul-2022 17:29:55.328 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/10.0.21
opengrok  | 01-Jul-2022 17:29:55.328 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          May 10 2022 21:53:12 UTC
opengrok  | 01-Jul-2022 17:29:55.328 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 10.0.21.0
opengrok  | 01-Jul-2022 17:29:55.328 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
opengrok  | 01-Jul-2022 17:29:55.328 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.18.0-372.9.1.el8.x86_64
opengrok  | 01-Jul-2022 17:29:55.329 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
opengrok  | 01-Jul-2022 17:29:55.329 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-11
opengrok  | 01-Jul-2022 17:29:55.329 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.15+10
opengrok  | 01-Jul-2022 17:29:55.329 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
opengrok  | 01-Jul-2022 17:29:55.329 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
opengrok  | 01-Jul-2022 17:29:55.329 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
opengrok  | 01-Jul-2022 17:29:55.341 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
opengrok  | 01-Jul-2022 17:29:55.341 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
opengrok  | 01-Jul-2022 17:29:55.341 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
opengrok  | 01-Jul-2022 17:29:55.341 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
opengrok  | 01-Jul-2022 17:29:55.341 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
opengrok  | 01-Jul-2022 17:29:55.341 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
opengrok  | 01-Jul-2022 17:29:55.341 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
opengrok  | 01-Jul-2022 17:29:55.341 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
opengrok  | 01-Jul-2022 17:29:55.342 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
opengrok  | 01-Jul-2022 17:29:55.342 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
opengrok  | 01-Jul-2022 17:29:55.342 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
opengrok  | 01-Jul-2022 17:29:55.342 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
opengrok  | 01-Jul-2022 17:29:55.342 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
opengrok  | 01-Jul-2022 17:29:55.342 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
opengrok  | 01-Jul-2022 17:29:55.346 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.33] using APR version [1.7.0].
opengrok  | 01-Jul-2022 17:29:55.346 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [true].
opengrok  | 01-Jul-2022 17:29:55.349 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1n  15 Mar 2022]
opengrok  | 01-Jul-2022 17:29:55.679 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
opengrok  | 01-Jul-2022 17:29:55.700 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [546] milliseconds
opengrok  | 01-Jul-2022 17:29:55.749 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
opengrok  | 01-Jul-2022 17:29:55.749 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/10.0.21]
opengrok  | 01-Jul-2022 17:29:55.773 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/opengrok.war]
opengrok  | 01-Jul-2022 17:29:55.785 WARNING [main] org.apache.tomcat.util.digester.SetPropertiesRule.begin Match [Context] failed to set property [antiJARLocking] to [true]
opengrok  | 01-Jul-2022 17:29:59.204 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
opengrok  | 01-Jul-2022 17:29:59.339 INFO [main] org.opengrok.indexer.Metrics.<clinit> configuring PrometheusRegistry
opengrok  | 01-Jul-2022 17:29:59.436 INFO [main] org.opengrok.web.WebappListener.contextInitialized Starting webapp with version 1.7.32 (1a2ed5cf92e80419ef690aef909685020d04e0e7)
opengrok  | 01-Jul-2022 17:29:59.437 INFO [main] org.opengrok.indexer.configuration.Configuration.read Reading configuration from /opengrok/etc/configuration.xml
opengrok  | 01-Jul-2022 17:29:59.477 WARNING [main] org.opengrok.indexer.framework.PluginFramework.reload Plugin directory not found or not readable: /opengrok/data/../plugins. All requests allowed.
opengrok  | 01-Jul-2022 17:29:59.498 SEVERE [main] org.opengrok.web.WebappListener.checkIndex index check failed
opengrok  |     org.apache.lucene.index.IndexNotFoundException: no segments* file found in MMapDirectory@/opengrok/data/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@5bda90af: files: []
opengrok  |             at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:715)
opengrok  |             at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:672)
opengrok  |             at org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:463)
opengrok  |             at org.opengrok.indexer.index.IndexCheck.checkDir(IndexCheck.java:138)
opengrok  |             at org.opengrok.web.WebappListener.checkIndex(WebappListener.java:151)
opengrok  |             at org.opengrok.web.WebappListener.contextInitialized(WebappListener.java:111)
opengrok  |             at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4717)
opengrok  |             at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5179)
opengrok  |             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
opengrok  |             at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
opengrok  |             at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698)
opengrok  |             at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:747)
opengrok  |             at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1027)
opengrok  |             at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2001)
opengrok  |             at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
opengrok  |             at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
opengrok  |             at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
opengrok  |             at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
opengrok  |             at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:828)
opengrok  |             at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:478)
opengrok  |             at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1708)
opengrok  |             at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:320)
opengrok  |             at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
opengrok  |             at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
opengrok  |             at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
opengrok  |             at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)
opengrok  |             at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:886)
opengrok  |             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
opengrok  |             at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
opengrok  |             at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
opengrok  |             at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
opengrok  |             at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
opengrok  |             at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
opengrok  |             at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
opengrok  |             at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
opengrok  |             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
opengrok  |             at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
opengrok  |             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
opengrok  |             at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
opengrok  |             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
opengrok  |             at org.apache.catalina.startup.Catalina.start(Catalina.java:795)
opengrok  |             at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
opengrok  |             at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
opengrok  |             at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
opengrok  |             at java.base/java.lang.reflect.Method.invoke(Method.java:566)
opengrok  |             at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
opengrok  |             at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
opengrok  | 01-Jul-2022 17:29:59.927 INFO [Thread-2] org.opengrok.suggest.Suggester.init Initializing suggester
opengrok  | 01-Jul-2022 17:29:59.948 INFO [Thread-2] org.opengrok.suggest.Suggester.shutdownAndAwaitTermination Suggester successfully initialized (took 0 seconds)
opengrok  | 01-Jul-2022 17:29:59.965 INFO [Thread-2] org.opengrok.web.api.v1.suggester.provider.service.impl.SuggesterServiceImpl.scheduleRebuild Scheduling suggester rebuild in PT6H30M0.051474S
opengrok  | 01-Jul-2022 17:30:00.765 INFO [main] org.hibernate.validator.internal.util.Version.<clinit> HV000001: Hibernate Validator 7.0.0.Final
opengrok  | 01-Jul-2022 17:30:03.181 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/opengrok.war] has finished in [7,408] ms
opengrok  | 01-Jul-2022 17:30:03.182 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/source]
opengrok  | 01-Jul-2022 17:30:03.195 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/source] has finished in [13] ms
opengrok  | 01-Jul-2022 17:30:03.200 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
opengrok  | 01-Jul-2022 17:30:03.220 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [7519] milliseconds
opengrok  | Tomcat is ready
opengrok  | Waiting for reindex to be triggered
```

Where am I wrong ?

**Comment by vladak** [comment]
If you mean the `IndexNotFoundException`, then this is caused by running `IndexCheck#checkDir()` on a directory that does not have index files inside.

**Comment by mishka81** [comment]
@vladak indeed my data folder was empty, that's what I said in my first comment.
Looking forward the next version to try this
