### ISSUE TITLE
WARNING: Non-zero exit status 129 from "git" command 

### ISSUE THREAD

**Issue by maestropandy** [oracle/opengrok#3987]
The History error ( warning and exits indexer process) occurred in particular projects, It showed the following message in the logs while exits as below

`Jul 06, 2022 12:03:49 PM org.opensolaris.opengrok.util.Executor exec
WARNING: Non-zero exit status 129 from command [git, log, --abbrev-commit, --abbrev=8, --name-only, --pretty=fuller, --date=rfc, --follow, --, src/hotspot/share/services/writeableFlags.hpp] in directory opengrok/home/source/jdk11u-cpu-git/jdk11u-cpu-open
Jul 06, 2022 12:03:49 PM org.opensolaris.opengrok.history.FileHistoryCache$1 run
WARNING: doFileHistory() got exception
org.opensolaris.opengrok.history.HistoryException: Failed to get history for: "opengrok/home/source/jdk11u-cpu-git/jdk11u-cpu-open/src/hotspot/share/services/writeableFlags.hpp" Exit code: 129
        at org.opensolaris.opengrok.history.GitHistoryParser.parse(GitHistoryParser.java:165)
        at org.opensolaris.opengrok.history.GitRepository.getHistory(GitRepository.java:513)
        at org.opensolaris.opengrok.history.GitRepository.getHistory(GitRepository.java:506)
        at org.opensolaris.opengrok.history.FileHistoryCache.doFileHistory(FileHistoryCache.java:105)
        at org.opensolaris.opengrok.history.FileHistoryCache.access$000(FileHistoryCache.java:62)
        at org.opensolaris.opengrok.history.FileHistoryCache$1.run(FileHistoryCache.java:491)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

I've gone through [1963](https://github.com/oracle/opengrok/issues/1963)  & [1884](https://github.com/oracle/opengrok/issues/1884) and other reported issues, based on that installed newer git version in different location (/usr/local/git/bin/git )  and mapped that in indexing using "_-Dorg.opengrok.indexer.history.git_" as below

`/bin/java -d64 -server -Xms2g -Xmx6g -Dorg.opengrok.indexer.history.git=/usr/local/git/bin/git -Dorg.opensolaris.opengrok.history.ScanToSpecifiedDepth=true -Dorg.opensolaris.opengrok.history.RenamedHandlingEnabled=true -cp $CURRENT/bin/opengrok.jar -jar $CURRENT/bin/opengrok.jar -W $HOME/configuration.xml -c /usr/bin/ctags -P -S -H -v -s $SOURCE -d $DATA` 

Even bumped log level and increased java heap memory doesn't help

Opengrok version: opengrok-1.0-v3
java version "1.8.0_221"
git version 1.8.3.1

**Comment by maestropandy** [comment]
Anyone looking into ?

**Comment by vladak** [comment]
Not really. This is such an old version that it's not worth it, especially given that the recent versions switched to JGit so they would not exhibit this problem.
