### ISSUE TITLE
Docker container fails to start (v1.7.35)

### ISSUE THREAD

**Issue by brmuire** [oracle/opengrok#4022]
**Describe the bug**

Docker container fails to start for image version: 1.7.35. We were previously using image version 1.7.26 without issue.

Error:
```
Running version 1.7.35
synchronization period = 60 minutes
Deploying web application
extra indexer options: -S -G -T 6
Checking if index matches current version
Traceback (most recent call last):
  File "/scripts/start.py", line 608, in <module>
    main()
  File "/scripts/start.py", line 519, in main
    check_index_and_wipe_out(logger)
  File "/scripts/start.py", line 423, in check_index_and_wipe_out
    indexer.execute()
  File "/usr/local/lib/python3.10/dist-packages/opengrok_tools/utils/command.py", line 228, in execute
    output_thread = OutputThread(output_event, self.logger,
  File "/usr/local/lib/python3.10/dist-packages/opengrok_tools/utils/command.py", line 172, in __init__
    self.start()
  File "/usr/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

docker-compose.yml (we create two containers, a primary and secondary):
```
version: "3.0"
services:
    primary:
        image: opengrok/docker:1.7.26
        ports:
            - 8080
        volumes:
            - /export/opengrok/source:/opengrok/src:ro
            - primary-config:/opengrok/etc
            - primary-index:/opengrok/data
            - ./opengrok/primary_footer:/opengrok/data/footer_include
            - ./opengrok/style.css:/opengrok/data/http_header_include
        restart: unless-stopped
        networks:
            webproxy:
                aliases:
                    - opengrok-primary
            prometheus:
                aliases:
                    - opengrok-primary
        environment:
            SYNC_PERIOD_MINUTES: 60
            CHECK_INDEX: "yes"
            AVOID_PROJECTS: "yes"
            NOMIRROR: "yes"
            INDEXER_OPT: "-S -G -T 6"
    secondary:
        image: opengrok/docker:1.7.26
        ports:
            - 8080
        volumes:
            - /export/opengrok/source:/opengrok/src:ro
            - secondary-config:/opengrok/etc
            - secondary-index:/opengrok/data
            - ./opengrok/secondary_footer:/opengrok/data/footer_include
            - ./opengrok/style.css:/opengrok/data/http_header_include
        restart: unless-stopped
        networks:
            webproxy:
                aliases:
                    - opengrok-secondary
            prometheus:
                aliases:
                    - opengrok-secondary
        environment:
            SYNC_PERIOD_MINUTES: 60
            CHECK_INDEX: "yes"
            AVOID_PROJECTS: "yes"
            NOMIRROR: "yes"
            INDEXER_OPT: "-S -G -T 6"
volumes:
    primary-index:
    primary-config:
    secondary-index:
    secondary-config:
```

**To Reproduce**
`docker-compose up`
or 
`docker exec -it opengrok_secondary_1 /scripts/start.py`

**Expected behavior**

Container starts

**Screenshots**

**Additional context**

**Comment by vladak** [comment]
https://stackoverflow.com/questions/70087344/python-in-docker-runtimeerror-cant-start-new-thread suggests this might be problem with Docker environment. What is your Docker version ?

**Comment by vladak** [comment]
For the record, I have just tried Docker image for OpenGrok 1.7.35 with Docker 20.10.12 (output from `docker version` bellow) and it starts fine.

```
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        20.10.12-0ubuntu2~20.04.1
 Built:             Wed Apr  6 02:14:38 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.2
  Git commit:       20.10.12-0ubuntu2~20.04.1
  Built:            Thu Feb 10 15:03:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu1~20.04.4
  GitCommit:        
 runc:
  Version:          1.1.0-0ubuntu1~20.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        
```
