### ISSUE TITLE
Startup Tomcat10 Warning "java.io.IOException: java.lang.reflect.InvocationTargetException"

### ISSUE THREAD

**Issue by JustSong** [oracle/opengrok#4042]
- JDK: Java11.0.16.1
- Web server: Tomcat10.0.23
- Ctags: Universal Ctags 5.9.0(aaf5fa4f)
- Opengrok: 1.7.35

After I start the tomcat and I can see a lot of "java.io.IOException: java.lang.reflect.InvocationTargetException" warning. but we can still open the website.
```
22-Sep-2022 11:09:58.011 WARNING [main] org.apache.tomcat.util.scan.StandardJarScanner.processURLs Failed to scan [file:/var/lib/tomcat10/webapps/source/WEB-INF/lib/jakarta.xml.bind-api-3.0.1.jar] from classloader hierarchy
        java.io.IOException: java.lang.reflect.InvocationTargetException
                at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:209)
                at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:65)
                at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:49)
```

Qestion: Should we do anything to fix this warning ?

Thanks

**Comment by vladak** [comment]
This is harmless, closing as dup of #3390.
