### ISSUE TITLE
testPhraseAfter() et al fail occasionally

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#4108]
When working on #4075, I noticed that some tests from `SuggesterControllerTest` fail occasionally, namely these:
  - `testPhraseAfter`
  - `testPhraseBefore`
  - `testPhraseMiddle`

And also the `testSloppyPhrase`, however that one I have seen in Github Action failed builds before I think, unlike these 3, although they might share common root cause.

Interestingly, these can be stepped through in a debugger and they would still sometimes fail. The failures look like this:
```

java.lang.AssertionError: 
Expected: iterable containing ["file"]
     but: no item was "file"

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.opengrok.web.api.v1.controller.SuggesterControllerTest.testPhraseAfter(SuggesterControllerTest.java:335)
```

In this case the API call got empty result.

When tracing the failed tests, it was always caused by `interrupted` being set to `true` in `SuggesterSearcher`, e.g. https://github.com/oracle/opengrok/blob/c10182859ee0b2d541135b28e90df09aca1a13d7/suggester/src/main/java/org/opengrok/suggest/SuggesterSearcher.java#L140-L143 however also in different locations where `Thread.currentThread().isInterrupted()` or the `interrupted` field is checked.

The thread being interrupted comes from https://github.com/oracle/opengrok/blob/c10182859ee0b2d541135b28e90df09aca1a13d7/suggester/src/main/java/org/opengrok/suggest/Suggester.java#L107-L115

I tried commenting out the https://github.com/oracle/opengrok/blob/c10182859ee0b2d541135b28e90df09aca1a13d7/suggester/src/main/java/org/opengrok/suggest/Suggester.java#L620 and significantly bumping the timeout in https://github.com/oracle/opengrok/blob/c10182859ee0b2d541135b28e90df09aca1a13d7/suggester/src/main/java/org/opengrok/suggest/Suggester.java#L466 however neither helped.

**Comment by vladak** [comment]
As suggested (sic!) on SO in https://stackoverflow.com/a/2476246/11582827, I put a breakpoint to `Thread.interrupt()` and got this:
```
interrupt:980, Thread (java.lang), Thread.java
cancel:173, FutureTask (java.util.concurrent), FutureTask.java
cancelAll:308, AbstractExecutorService (java.util.concurrent), AbstractExecutorService.java
invokeAll:297, AbstractExecutorService (java.util.concurrent), AbstractExecutorService.java
complexLookup:466, Suggester (org.opengrok.suggest), Suggester.java
search:413, Suggester (org.opengrok.suggest), Suggester.java
getSuggestions:117, SuggesterServiceImpl (org.opengrok.web.api.v1.suggester.provider.service.impl), SuggesterServiceImpl.java
getSuggestions:123, SuggesterController (org.opengrok.web.api.v1.controller), SuggesterController.java
invoke0:-1, NativeMethodAccessorImpl (jdk.internal.reflect), NativeMethodAccessorImpl.java
invoke:62, NativeMethodAccessorImpl (jdk.internal.reflect), NativeMethodAccessorImpl.java
invoke:43, DelegatingMethodAccessorImpl (jdk.internal.reflect), DelegatingMethodAccessorImpl.java
invoke:566, Method (java.lang.reflect), Method.java
lambda$static$0:52, ResourceMethodInvocationHandlerFactory (org.glassfish.jersey.server.model.internal), ResourceMethodInvocationHandlerFactory.java
invoke:-1, 668152723 (org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$$Lambda$1794), Unknown Source
run:134, AbstractJavaResourceMethodDispatcher$1 (org.glassfish.jersey.server.model.internal), AbstractJavaResourceMethodDispatcher.java
invoke:177, AbstractJavaResourceMethodDispatcher (org.glassfish.jersey.server.model.internal), AbstractJavaResourceMethodDispatcher.java
doDispatch:219, JavaResourceMethodDispatcherProvider$TypeOutInvoker (org.glassfish.jersey.server.model.internal), JavaResourceMethodDispatcherProvider.java
dispatch:81, AbstractJavaResourceMethodDispatcher (org.glassfish.jersey.server.model.internal), AbstractJavaResourceMethodDispatcher.java
invoke:478, ResourceMethodInvoker (org.glassfish.jersey.server.model), ResourceMethodInvoker.java
apply:400, ResourceMethodInvoker (org.glassfish.jersey.server.model), ResourceMethodInvoker.java
apply:81, ResourceMethodInvoker (org.glassfish.jersey.server.model), ResourceMethodInvoker.java
run:261, ServerRuntime$1 (org.glassfish.jersey.server), ServerRuntime.java
call:248, Errors$1 (org.glassfish.jersey.internal), Errors.java
call:244, Errors$1 (org.glassfish.jersey.internal), Errors.java
process:292, Errors (org.glassfish.jersey.internal), Errors.java
process:274, Errors (org.glassfish.jersey.internal), Errors.java
process:244, Errors (org.glassfish.jersey.internal), Errors.java
runInScope:265, RequestScope (org.glassfish.jersey.process.internal), RequestScope.java
process:240, ServerRuntime (org.glassfish.jersey.server), ServerRuntime.java
handle:697, ApplicationHandler (org.glassfish.jersey.server), ApplicationHandler.java
serviceImpl:394, WebComponent (org.glassfish.jersey.servlet), WebComponent.java
service:346, WebComponent (org.glassfish.jersey.servlet), WebComponent.java
service:357, ServletContainer (org.glassfish.jersey.servlet), ServletContainer.java
service:311, ServletContainer (org.glassfish.jersey.servlet), ServletContainer.java
service:205, ServletContainer (org.glassfish.jersey.servlet), ServletContainer.java
doFilter:115, FilterChainImpl (org.glassfish.grizzly.servlet), FilterChainImpl.java
invokeFilterChain:78, FilterChainImpl (org.glassfish.grizzly.servlet), FilterChainImpl.java
doServletService:196, ServletHandler (org.glassfish.grizzly.servlet), ServletHandler.java
service:144, ServletHandler (org.glassfish.grizzly.servlet), ServletHandler.java
run:190, HttpHandler$1 (org.glassfish.grizzly.http.server), HttpHandler.java
doWork:535, AbstractThreadPool$Worker (org.glassfish.grizzly.threadpool), AbstractThreadPool.java
run:515, AbstractThreadPool$Worker (org.glassfish.grizzly.threadpool), AbstractThreadPool.java
run:829, Thread (java.lang), Thread.java
```
so this seems to be indeed caused by the `invokeAll()` with timeout. However this might be just an artifact of running the test in debugger and single stepping.

**Comment by vladak** [comment]
Even if I change the time unit to seconds:
```patch
diff --git a/suggester/src/main/java/org/opengrok/suggest/Suggester.java b/suggester/src/main/java/org/opengrok/suggest/Suggester.java
index a88cc1c20..04e5c0d2e 100644
--- a/suggester/src/main/java/org/opengrok/suggest/Suggester.java
+++ b/suggester/src/main/java/org/opengrok/suggest/Suggester.java
@@ -463,7 +463,7 @@ public final class Suggester implements Closeable {
 
         List<Future<Void>> futures;
         try {
-            futures = executorService.invokeAll(searchTasks, timeThreshold, TimeUnit.MILLISECONDS);
+            futures = executorService.invokeAll(searchTasks, timeThreshold, TimeUnit.SECONDS);
         } catch (InterruptedException e) {
             LOGGER.log(Level.WARNING, "Interrupted while invoking suggester search", e);
             Thread.currentThread().interrupt();
```
then the test occasionally fails (with complete run time still under 2 seconds), so there has to be another reason for the thread cancellation.

**Comment by vladak** [comment]
When comparing the difference between failed and passing `testPhraseAfter()`, the failing case has a number of hits for this line: https://github.com/oracle/opengrok/blob/df54bd1155878595f7d2f9c51569d53eaf9f2966/suggester/src/main/java/org/opengrok/suggest/SuggesterSearcher.java#L294 while the passing case has none.

**Comment by vladak** [comment]
Given that https://github.com/oracle/opengrok/blob/df54bd1155878595f7d2f9c51569d53eaf9f2966/suggester/src/main/java/org/opengrok/suggest/query/customized/CustomExactPhraseScorer.java#L216 returns `null` for the failed cases and not for the passing cases, there is something wrong about how `CustomExactPhraseScorer#documentToPositionsMap` was initialized.

**Comment by vladak** [comment]
Getting the values of the `docBase`, `docID` in `SuggesterSearcher#getPhraseScore()`: https://github.com/oracle/opengrok/blob/df54bd1155878595f7d2f9c51569d53eaf9f2966/suggester/src/main/java/org/opengrok/suggest/SuggesterSearcher.java#L290-L293
and the contents of the `CustomExactPhraseScorer#documentToPositionsMap`, the contents of the map matches the `docBase`, `docID` values for the pass cases, however they do not match for the fail cases. Here are some snapshots of the values:

`documentToPositionsMap` | `docBase` | `docID` | result
--- | --- | --- | ---
`{1={12}}` | 1 | 1 | fail
`{0={12}}` | 6 | 0 | fail
`{0={12}}` | 3 | 0 | fail
`{0={12}}` | 0 | 0 | pass

The passing test seems to always have the 0, 0 values.

So maybe the problem is in the `docBase`, `docID` values provided by `SuggesterSearcher` (which extends Lucene's `IndexSearcher`) as the `docBase` comes from internal values of `IndexSearcher`. Or, some discrepancy between the Lucene document views in `SuggesterSearcher` and `CustomExactPhraseScorer`.
