### ISSUE TITLE
jgit unable to resolve ambiguous commit reference in large repositories

### ISSUE THREAD

**Issue by mmmarq** [oracle/opengrok#4146]
**Describe the bug**
One of our projects have a huge git repository with a large number of commits/blogs/etc what makes default jgit SHA1 abreviation unable to resolve all SHA1 references.
This raises a WARNING while creating History Cache and a "*Error reading file*" when opengrok tries to show a file content.
```
Opengrok 1.7.35
JDK openjdk12.0.2-x64
Tomcat apache-tomcat-10.0.12
OS Ubuntu 18.04.6 LTS
Git version 2.39.0
```
**To Reproduce**
Index a very large git project like https://android.googlesource.com/platform/frameworks/base/

Error message while generating history cache:
```
Jan 05, 2023 5:17:44 AM org.opengrok.indexer.history.HistoryGuru createCache
WARNING: An error occurred while creating cache for /localrepo/frameworks/base (GitRepository)
org.opengrok.indexer.history.HistoryException: org.eclipse.jgit.errors.AmbiguousObjectException: Object abbreviation 24a7eaee is ambiguous
	at org.opengrok.indexer.history.GitRepository.accept(GitRepository.java:464)
	at org.opengrok.indexer.history.BoundaryChangesets.getBoundaryChangesetIDs(BoundaryChangesets.java:88)
	at org.opengrok.indexer.history.RepositoryWithHistoryTraversal.doCreateCache(RepositoryWithHistoryTraversal.java:160)
	at org.opengrok.indexer.history.Repository.createCache(Repository.java:403)
	at org.opengrok.indexer.history.HistoryGuru.createCache(HistoryGuru.java:707)
	at org.opengrok.indexer.history.HistoryGuru.lambda$createCacheReal$3(HistoryGuru.java:759)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: org.eclipse.jgit.errors.AmbiguousObjectException: Object abbreviation 24a7eaee is ambiguous
	at org.eclipse.jgit.lib.Repository.resolveAbbreviation(Repository.java:920)
	at org.eclipse.jgit.lib.Repository.resolveSimple(Repository.java:848)
	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:813)
	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:472)
	at org.opengrok.indexer.history.GitRepository.accept(GitRepository.java:455)
	... 10 more
```
Error message while showing file content:
```
05-Jan-2023 07:45:10.385 SEVERE [ajp-nio-100.64.38.11-8009-exec-874] org.opengrok.indexer.history.GitRepository.getHistoryGet Failed to get original r[11/99984$localrepo/frameworks/base/services/core/java/com/android/server/audio/FocusRequester.java (revision bfc8df5a)
        org.eclipse.jgit.errors.AmbiguousObjectException: Object abbreviation bfc8df5a is ambiguous
                at org.eclipse.jgit.lib.Repository.resolveAbbreviation(Repository.java:920)
                at org.eclipse.jgit.lib.Repository.resolveSimple(Repository.java:848)
                at org.eclipse.jgit.lib.Repository.resolve(Repository.java:813)
                at org.eclipse.jgit.lib.Repository.resolve(Repository.java:472)
                at org.opengrok.indexer.history.GitRepository.findOriginalName(GitRepository.java:266)
                at org.opengrok.indexer.history.GitRepository.getHistoryGet(GitRepository.java:204)
                at org.opengrok.indexer.history.Repository.getHistoryGet(Repository.java:235)
                at org.opengrok.indexer.history.HistoryGuru.getRevision(HistoryGuru.java:414)
                at org.apache.jsp.list_jsp._jspService(list_jsp.java:964)
                at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
                at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:777)
                at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
                at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:380)
                at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:328)
                at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:777)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.opengrok.web.CookieFilter.doFilter(CookieFilter.java:50)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:95)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:67)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:660)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353)
                at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:439)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:872)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1695)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:835)
```
**Expected behavior**
OpenGrok able to create history cache and show file content

**Comment by mmmarq** [comment]
Additional information:

We have some internal changes that are not available into public repository link posted into original message but I can see both ambiguous objects by:
```
frameworks/base]$ git rev-parse --disambiguate=bfc8df5a
bfc8df5a2f5b4bd48c0735021b4a6134fc448789
bfc8df5aa46f5d9ea9b3ec6db6b85ab38b2d26d3
```

Thanks in advance

**Comment by mmmarq** [comment]
**Read file error screenshot**:
![ambiguous_sha1_read_file_error](https://user-images.githubusercontent.com/7229895/210834703-870465fd-de98-4ca5-a7cc-9a09e07beb2f.png)

**Browser URL**:

https://<servername>/source/xref/frameworks/base/services/core/java/com/android/server/audio/FocusRequester.java?r=bfc8df5a

**Index command**:

```
/opengrok/opengrok-tools/bin/opengrok-indexer --java /tools/jre/bin/java --java_opts=-server --java_opts=-Xmx24g --java_opts=-Dorg.opengrok.indexer.history.git=/bin/git --jar /opengrok/lib/opengrok.jar -- --ctags /tools/ctags/ctags --dataRoot /data -i 'd:'\''.repo'\''' -i 'd:'\''*.git'\''' -i 'd:'\''.git'\''' -H --projects --depth 50 --economical --search --source /localrepo -R /etc/read-only.xml --writeConfig /etc/configuration.xml
```

**Read-only config file content**:
```
cat /etc/read-only.xml
<?xml version='1.0' encoding='UTF-8'?>
<java version="12.0.2" class="java.beans.XMLDecoder">
 <object class="org.opengrok.indexer.configuration.Configuration">
  <void property="webappCtags">
    <boolean>true</boolean>
  </void>
  <void property="suggesterConfig">
   <void property="enabled">
    <boolean>false</boolean>
   </void>
  </void>
  <void property="xrefTimeout">
   <long>240</long>
  </void>
 </object>
</java>
```

**Comment by mmmarq** [comment]
Maybe increasing GIT_ABBREV_LEN at:

https://github.com/oracle/opengrok/blob/master/opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java#L101

Or making it a command line option (where 8 is the default) would help. but I'm not sure if there are other side effects.

Thanks

**Comment by vladak** [comment]
Thanks for the comments. There are definitely side effects. Stuff like history revision being stored in the index (which is then used e.g. to determine whether history cache entry is fresh/stale) or being part of the xref URLs. Basically reindex from scratch will be needed, I think. Possibly the abbrev length can be made a [per project tunable](https://github.com/oracle/opengrok/wiki/Per-project-configuration).

**Comment by harrisric** [comment]
I've also experienced this same problem @vladak.
I think from having had a look through the code it seems that the main reason for the abbreviation of the commit hash might have been to present something user-friendly for the UI. That would suggest that the system could (should) keep the entire commit hash for the purposes of commit identification but simply present a more compact version in the UI (perhaps even retaining the full hash if needed for URL links). That might avoid the need for any per-project configuration.

A re-index would be required as you note but it might be possible to provide some short-cuts e.g. if a commit hash is not ambiguous then it could just be re-written as the full-hash. Unsure if that would be practical.

**Comment by mmmarq** [comment]
As an workaround I did a local build of 1.7.41 changing both:

https://github.com/oracle/opengrok/blob/master/opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java#L101

and

https://github.com/oracle/opengrok/blob/master/opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java#L843

SHA1 abbreviation to 10 and it is working fine now. I have tried to make this value a parameter but I had no time to a deep investigation about how to do that yet.

Thanks

**Comment by vladak** [comment]
> I've also experienced this same problem @vladak. I think from having had a look through the code it seems that the main reason for the abbreviation of the commit hash might have been to present something user-friendly for the UI. That would suggest that the system could (should) keep the entire commit hash for the purposes of commit identification but simply present a more compact version in the UI (perhaps even retaining the full hash if needed for URL links). That might avoid the need for any per-project configuration.
> 
> A re-index would be required as you note but it might be possible to provide some short-cuts e.g. if a commit hash is not ambiguous then it could just be re-written as the full-hash. Unsure if that would be practical.

Storing the full commit hash in the index and history cache (and annotation cache) and making the UI configurable should not be a big deal. I wonder whether there is a way how to tell which hash length is enough for given repository so that the UI can be auto-tuning.

**Comment by vladak** [comment]
Fixed by PR #4171.

**Comment by gnustavo** [comment]
> I wonder whether there is a way how to tell which hash length is enough for given repository so that the UI can be auto-tuning.

The two answers for [this StackOverflow question](https://stackoverflow.com/q/32405922) are interesting. Running the second script in the Git clone on my notebook takes about 0,6s.

**Comment by vladak** [comment]
> > I wonder whether there is a way how to tell which hash length is enough for given repository so that the UI can be auto-tuning.
> 
> The two answers for [this StackOverflow question](https://stackoverflow.com/q/32405922) are interesting. Running the second script in the Git clone on my notebook takes about 0,6s.

Thanks for the link. The answer is basically to traverse the list of changesets and let `git` do the abbreviation, take the longest hash. For OpenGrok this is not really feasible (assuming JGit allows for this functionality) as it would require recreating the annotation cache from scratch. Also, the complete traversal would slow it down in some places. Or, use the longest in-the-wild observed hash length (11 as of now it looks like) and use that as universal number, however I don't like that either.
