### ISSUE TITLE
NPE in LdapFilterPlugin#checkEntity

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#4310]
When testing directory listing API on OpenGrok instance with authorization stacks (using http://localhost:8080/source/api/v1/list?path=/on-test) the following NPE was reported in the logs:
```
20-Apr-2023 09:38:34.372 FINER [http-nio-8080-exec-138] org.opengrok.indexer.authorization.AuthorizationStack.isAllowed Authorization for "on-test" in "default stack" [required]
20-Apr-2023 09:38:34.372 FINEST [http-nio-8080-exec-138] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "opengrok.auth.plugin.UserPlugin" [optional] testing a name "on-test"
20-Apr-2023 09:38:34.372 WARNING [http-nio-8080-exec-138] opengrok.auth.plugin.decoders.MellonHeaderDecoder.fromRequest Can not construct User object: header 'MELLON_email' not found in request headers: host,user-agent,accept
20-Apr-2023 09:38:34.372 FINEST [http-nio-8080-exec-138] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "opengrok.auth.plugin.UserPlugin" [optional] testing a name "on-test" => false
20-Apr-2023 09:38:34.372 FINEST [http-nio-8080-exec-138] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "opengrok.auth.plugin.LdapUserPlugin" [optional] testing a name "on-test"
20-Apr-2023 09:38:34.373 FINEST [http-nio-8080-exec-138] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "opengrok.auth.plugin.LdapUserPlugin" [optional] testing a name "on-test" => false
20-Apr-2023 09:38:34.373 FINEST [http-nio-8080-exec-138] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "substack for foo code" [required] testing a name "on-test"
20-Apr-2023 09:38:34.373 FINER [http-nio-8080-exec-138] org.opengrok.indexer.authorization.AuthorizationStack.isAllowed Authorization for "on-test" in "substack for foo code" [required]
20-Apr-2023 09:38:34.373 FINEST [http-nio-8080-exec-138] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "opengrok.auth.plugin.UserWhiteListPlugin" [sufficient] testing a name "on-test"
20-Apr-2023 09:38:34.373 WARNING [http-nio-8080-exec-138] opengrok.auth.plugin.UserWhiteListPlugin.checkWhitelist cannot get opengrok-user-plugin-user attribute
20-Apr-2023 09:38:34.373 FINEST [http-nio-8080-exec-138] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "opengrok.auth.plugin.UserWhiteListPlugin" [sufficient] testing a name "on-test" => false
20-Apr-2023 09:38:34.373 FINEST [http-nio-8080-exec-138] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "opengrok.auth.plugin.LdapFilterPlugin" [required] testing a name "on-test"
20-Apr-2023 09:38:34.373 WARNING [http-nio-8080-exec-138] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "opengrok.auth.plugin.LdapFilterPlugin" has failed the testing of "on-test" with an exception.
        java.lang.NullPointerException
                at opengrok.auth.plugin.LdapFilterPlugin.checkEntity(LdapFilterPlugin.java:199)
                at opengrok.auth.plugin.AbstractLdapPlugin.isAllowed(AbstractLdapPlugin.java:300)
                at org.opengrok.indexer.authorization.AuthorizationFramework$1.decision(AuthorizationFramework.java:160)
                at org.opengrok.indexer.authorization.AuthorizationPlugin.isAllowed(AuthorizationPlugin.java:186)
                at org.opengrok.indexer.authorization.AuthorizationStack.processStack(AuthorizationStack.java:242)
                at org.opengrok.indexer.authorization.AuthorizationStack.isAllowed(AuthorizationStack.java:200)
                at org.opengrok.indexer.authorization.AuthorizationStack.processStack(AuthorizationStack.java:242)
                at org.opengrok.indexer.authorization.AuthorizationStack.isAllowed(AuthorizationStack.java:200)
                at org.opengrok.indexer.authorization.AuthorizationFramework.performCheck(AuthorizationFramework.java:570)
                at org.opengrok.indexer.authorization.AuthorizationFramework.checkAll(AuthorizationFramework.java:534)
                at org.opengrok.indexer.authorization.AuthorizationFramework.isAllowed(AuthorizationFramework.java:153)
                at org.opengrok.web.api.v1.filter.PathAuthorizationFilter.isPathAuthorized(PathAuthorizationFilter.java:61)
                at org.opengrok.web.api.v1.filter.PathAuthorizationFilter.filter(PathAuthorizationFilter.java:84)
                at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:108)
                at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:44)
                at org.glassfish.jersey.process.internal.Stages.process(Stages.java:173)
                at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
                at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
                at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
                at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
                at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
                at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
                at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
                at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240)
                at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697)
                at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
                at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
                at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:357)
                at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
                at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.apache.catalina.filters.RequestDumperFilter.doFilter(RequestDumperFilter.java:198)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.opengrok.web.CookieFilter.doFilter(CookieFilter.java:50)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:68)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:67)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:864)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1655)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:834)
```

It is more likely that the attribute was not present (rather than the `request` parameter being `null`).

**Comment by vladak** [comment]
`AbstractLdapPlugin#isAllowed()` makes sure that the session is non null, therefore my hypothesis above about the attribute being null is plausible. Also, considering this is localhost to localhost request, there are no authentication headers passed to the webapp which makes this even more probable.

**Comment by vladak** [comment]
The reason why the attribute is null is that `AbstractLdapPlugin#ensureSessionExists()` bails before calling `LdapFilterPlugin#fillSession()` because `UserPlugin.REQUEST_ATTR` attribute is not present.
