### ISSUE TITLE
java.io.IOException: 83 failures (0.0%) while renaming pending files for project HM207A_new:indexed=true,history=false

### ISSUE THREAD

**Issue by yanggithuv** [oracle/opengrok#4319]
**Describe the bug**
A clear and concise description of what the bug is. Make sure you have done a search of the existing issues to prevent creating duplicates.

If you provide the exact version of OpenGrok, JDK used, OS(and its version) used and Tomcat(or your webapp server) used it can help figuring out an environment issue.
For performance problem OS and JDK tunables might be needed. For SCM problems also version of SCM is helpfull (e.g. some mercurial versions have issues, some not).

**To Reproduce**
Steps to reproduce the behavior: when create the index the opengrok  reported the errors times，and Itried 4 times the same issue happend
java.io.IOException: 83 failures (0.0%) while renaming pending files for project HM207A_new:indexed=true,history=false
	at org.opengrok.indexer.index.PendingFileCompleter.completeRenamings(PendingFileCompleter.java:254)
	at org.opengrok.indexer.index.PendingFileCompleter.completeInner(PendingFileCompleter.java:192)
	at org.opengrok.indexer.index.PendingFileCompleter.complete(PendingFileCompleter.java:176)
	at org.opengrok.indexer.index.IndexDatabase.finishWriting(IndexDatabase.java:2139)
	at org.opengrok.indexer.index.IndexDatabase.update(IndexDatabase.java:727)
	at org.opengrok.indexer.index.IndexDatabase.lambda$updateAll$1(IndexDatabase.java:279)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.NoSuchFileException: D:\tools\opengrok\opengrok-1.11.1\data\xref\HM207A_new\source\external\iptables\extensions\libxt_TOS.man.gz.org_opengrok
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:326)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:288)
	at java.base/java.nio.file.Files.move(Files.java:1421)
	at org.opengrok.indexer.index.PendingFileCompleter.doRename(PendingFileCompleter.java:379)
	at org.opengrok.indexer.index.PendingFileCompleter.lambda$completeRenamings$2(PendingFileCompleter.java:236)
	at java.base/java.util.stream.Collectors.lambda$groupingByConcurrent$59(Collectors.java:1297)
	at java.base/java.util.stream.ReferencePipeline.lambda$collect$1(ReferencePipeline.java:575)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

2023-04-26 13:52:48.888+0800 严重 t22 IndexDatabase.lambda$updateAll$1: Problem updating index database in directory D:\tools\opengrok\opengrok-1.11.1\data\index\HM207A_new: 
java.io.IOException: 83 failures (0.0%) while renaming pending files for project HM207A_new:indexed=true,history=false
	at org.opengrok.indexer.index.PendingFileCompleter.completeRenamings(PendingFileCompleter.java:254)
	at org.opengrok.indexer.index.PendingFileCompleter.completeInner(PendingFileCompleter.java:192)
	at org.opengrok.indexer.index.PendingFileCompleter.complete(PendingFileCompleter.java:176)
	at org.opengrok.indexer.index.IndexDatabase.finishWriting(IndexDatabase.java:2139)
	at org.opengrok.indexer.index.IndexDatabase.update(IndexDatabase.java:727)
	at org.opengrok.indexer.index.IndexDatabase.lambda$updateAll$1(IndexDatabase.java:279)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.NoSuchFileException: D:\tools\opengrok\opengrok-1.11.1\data\xref\HM207A_new\source\external\iptables\extensions\libxt_TOS.man.gz.org_opengrok
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:326)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:288)
	at java.base/java.nio.file.Files.move(Files.java:1421)
	at org.opengrok.indexer.index.PendingFileCompleter.doRename(PendingFileCompleter.java:379)
	at org.opengrok.indexer.index.PendingFileCompleter.lambda$completeRenamings$2(PendingFileCompleter.java:236)
	at java.base/java.util.stream.Collectors.lambda$groupingByConcurrent$59(Collectors.java:1297)
	at java.base/java.util.stream.ReferencePipeline.lambda$collect$1(ReferencePipeline.java:575)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

the environment is：

opengrok-1.11.1
apache-tomcat-10.1.7
ctags-p6.0.20230326.0-x64
 wins 10 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yanggithuv** [comment]
and when I create the index with a small project ，this issue not happened

it happens at a big android source project with svn and git
