### ISSUE TITLE
FileHistoryCacheTest.testFillLastHistoryEntriesAllOrNothing sometimes fails

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#4333]
Github Actions on Windows report this failure:
```
Failures: 
Error:    FileHistoryCacheTest.testFillLastHistoryEntriesAllOrNothing:1079 expected: <0> but was: <3>
```
which is this check:
```java
        assertEquals(0, (int) directoryEntries.stream().filter(e -> e.getDate() != null).count());
```

**Comment by vladak** [comment]
When running the test individually on a Windows, it passes, so I assume this is caused by  unfinished cleanup from some previous test. When running all the tests in `FileHistoryCacheTest` class without Mercurial/SCCS/Subversion installed, the test also passes.

**Comment by vladak** [comment]
Installed Subversion (SilkSVN - had to add it to system `PATH` because the test class executes `svn` and `svnadmin` commands directly, i.e. setting `-Dorg.opengrok.indexer.history.Subversion=...` helps only to enable Subversion run for the tests) and rerun the tests in IDEA, the test still passes.

**Comment by vladak** [comment]
For the record, I am testing this on Windows Server 2022.

**Comment by vladak** [comment]
I saw this failing on both Linux and macOS, so this is not exclusively a Windows environment problem.

**Comment by vladak** [comment]
Running this in IDEA, I accidentally reproduced it, the output was:
```
Oct 09, 2023 2:20:33 PM org.opengrok.indexer.Metrics <clinit>
INFO: configuring PrometheusRegistry
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Oct 09, 2023 2:20:34 PM org.opengrok.indexer.history.PerforceRepository isP4Working
WARNING: Command 'p4' does not work. Some operations with Perforce repositories will fail as a result.
Oct 09, 2023 2:20:34 PM org.opengrok.indexer.history.RepositoryFactory getRepository
WARNING: BazaarRepository not working (missing binaries?): /tmp/source14868807895232430816/bazaar
Oct 09, 2023 2:20:34 PM org.opengrok.indexer.history.RepositoryFactory getRepository
WARNING: Failed to get parent for /tmp/source14868807895232430816/bazaar: java.io.IOException
Oct 09, 2023 2:20:34 PM org.opengrok.indexer.history.RepositoryFactory getRepository
WARNING: BitKeeperRepository not working (missing binaries?): /tmp/source14868807895232430816/bitkeeper
Oct 09, 2023 2:20:34 PM org.opengrok.indexer.history.RepositoryFactory getRepository
WARNING: Failed to get parent for /tmp/source14868807895232430816/bitkeeper: java.io.IOException
Oct 09, 2023 2:20:34 PM org.opengrok.indexer.history.RepositoryFactory getRepository
WARNING: RCSRepository not working (missing binaries?): /tmp/source14868807895232430816/rcs_test
Oct 09, 2023 2:20:34 PM org.opengrok.indexer.history.MercurialRepository isHgWorking
WARNING: Command 'blame' does not work. Some operations with Mercurial repositories will fail as a result.
Oct 09, 2023 2:20:34 PM org.opengrok.indexer.history.RepositoryFactory getRepository
WARNING: MercurialRepository not working (missing binaries?): /tmp/source14868807895232430816/mercurial
Oct 09, 2023 2:20:34 PM org.opengrok.indexer.history.RepositoryFactory getRepository
WARNING: Failed to get parent for /tmp/source14868807895232430816/mercurial: java.io.IOException
Oct 09, 2023 2:20:34 PM org.opengrok.indexer.history.RepositoryFactory getRepository
WARNING: Failed to get branch for /tmp/source14868807895232430816/mercurial: java.io.IOException
Oct 09, 2023 2:20:34 PM org.opengrok.indexer.history.RepositoryFactory getRepository
WARNING: Failed to determineCurrentVersion for /tmp/source14868807895232430816/mercurial: java.io.IOException
Oct 09, 2023 2:20:35 PM org.opengrok.indexer.history.FileHistoryCache clear
WARNING: failed to delete '/tmp/data4815162271327254530/historycache/git/OpenGroklatestRev'
java.nio.file.NoSuchFileException: /tmp/data4815162271327254530/historycache/git/OpenGroklatestRev
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:249)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
	at java.base/java.nio.file.Files.delete(Files.java:1142)
	at org.opengrok.indexer.history.FileHistoryCache.clear(FileHistoryCache.java:834)
	at org.opengrok.indexer.history.FileHistoryCache$MockitoMock$943005677.clear$accessor$lNAjBeJv(Unknown Source)
	at org.opengrok.indexer.history.FileHistoryCache$MockitoMock$943005677$auxiliary$QEYh7kPH.call(Unknown Source)
	at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
	at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
	at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:142)
	at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:45)
	at org.mockito.Answers.answer(Answers.java:99)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:110)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:56)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:145)
	at org.opengrok.indexer.history.FileHistoryCache$MockitoMock$943005677.clear(Unknown Source)
	at org.opengrok.indexer.history.FileHistoryCacheTest.testFillLastHistoryEntriesAllOrNothing(FileHistoryCacheTest.java:1068)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:218)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:214)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:139)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:198)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:169)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:93)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:58)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:141)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:57)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:103)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
	at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:63)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)

Oct 09, 2023 2:20:35 PM org.opengrok.indexer.history.CacheUtil clearCacheDir
WARNING: directory /tmp/data4815162271327254530/historycache/git does not exist

org.opentest4j.AssertionFailedError: 
Expected :0
Actual   :1


	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:527)
	at org.opengrok.indexer.history.FileHistoryCacheTest.testFillLastHistoryEntriesAllOrNothing(FileHistoryCacheTest.java:1079)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
```
