### ISSUE TITLE
NPE when displaying a diff

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#4468]
When displaying a diff between two revisions in the latest master I am getting a NPE:
```
java.lang.NullPointerException
	at org.apache.jsp.diff_jsp._jspService(diff_jsp.java:722)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:770)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:467)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
...
```
Looking at the `diff_jsp.java` file in the Tomcat's `work` directory I see it happens here:
```java
} else if (data.getRevision().size() == 0) { 
```

**Comment by vladak** [comment]
This corresponds to https://github.com/oracle/opengrok/blob/b996a179711b7d79a14107e75c51014eb82cbe8f/opengrok-web/src/main/webapp/diff.jsp#L137

In the debugger I see the `revision` field being `null` indeed.

**Comment by vladak** [comment]
Tracing the execution, this branch is taken:
https://github.com/oracle/opengrok/blob/b996a179711b7d79a14107e75c51014eb82cbe8f/opengrok-web/src/main/java/org/opengrok/web/PageConfig.java#L351-L353
so the revisions are not filled.

**Comment by vladak** [comment]
After flipping the condition, the diff starts working.

**Comment by vladak** [comment]
Introduced in https://github.com/oracle/opengrok/commit/667c06e97558ade3d4fe429fdb915c0eb6f426f0
