### ISSUE TITLE
limit addFile() processing time

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#4550]
When indexing bunch of projects, the indexer had a trailing worker thread that was spinning on the CPU for inordinate amount of time (minutes) while all the other files were finished. The stack trace looked like this:
```
"OpenGrok-index-worker-48" #48 prio=5 os_prio=0 cpu=773733,68ms elapsed=1140,14s tid=0x00007f3648023000 nid=0x2134a7 runnable  [0x00007f364e5fd000]
   java.lang.Thread.State: RUNNABLE
	at org.opengrok.indexer.analysis.javascript.JavaScriptSymbolTokenizer.yylex(JavaScriptSymbolTokenizer.java:1645)
	at org.opengrok.indexer.analysis.JFlexTokenizer.incrementToken(JFlexTokenizer.java:106)
	at org.apache.lucene.index.IndexingChain$PerField.invertTokenStream(IndexingChain.java:1167)
	at org.apache.lucene.index.IndexingChain$PerField.invert(IndexingChain.java:1145)
	at org.apache.lucene.index.IndexingChain.processField(IndexingChain.java:697)
	at org.apache.lucene.index.IndexingChain.processDocument(IndexingChain.java:576)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocuments(DocumentsWriterPerThread.java:243)
	at org.apache.lucene.index.DocumentsWriter.updateDocuments(DocumentsWriter.java:421)
	at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1551)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1836)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1476)
	at org.opengrok.indexer.index.IndexDatabase.addFile(IndexDatabase.java:1278)
	at org.opengrok.indexer.index.IndexDatabase.lambda$indexParallel$9(IndexDatabase.java:1920)
	at org.opengrok.indexer.index.IndexDatabase$$Lambda$370/0x00000008401e7c40.call(Unknown Source)
```
Specifically, the file in question came from the https://hg.mozilla.org/mozilla-central , it was `testing/modules/sinon-7.2.7.js` which contains long lists of numbers. Such files are known to cause problems.

There should be some time limit for `addFile()` processing.

**Comment by vladak** [comment]
Rather than trying to terminate and cleanup the `writer.addDocument()` call it would be easier to check the term count in certain fields and skip the document altogether if the count is above given threshold.

**Comment by VKspyder2003** [comment]
Hi @vladak,

I'd like to work on this issue.

After tracing the indexing flow (IndexDatabase → AnalyzerGuru → PlainAnalyzer → JFlexTokenizer), my understanding is that the expensive path is the symbol tokenization used for the REFS field. Instead of introducing a timeout around writer.addDocument(), I'm planning to add a defensive upper bound on emitted REFS terms in JFlexTokenizer and apply it from PlainAnalyzer, so pathological inputs terminate symbol tokenization early while preserving the rest of the document indexing.

Let me know if I shall move ahead with the current plan and submit a PR.
