### ISSUE TITLE
deadlock in indexer when publishing metrics

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#4645]
Routine run of the indexer with 1.13.18 and the statsd metrics enabled lead to the following deadlock (`jstack` is kind to report this in JDK11):
```
Found one Java-level deadlock:
=============================
"main":
  waiting to lock monitor 0x0000000001be6700 (object 0x00007ff7f700ed20, a java.lang.Object),
  which is held by "Service Thread"
"Service Thread":
  waiting for ownable synchronizer 0x00007ff78071a5b0, (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync),
  which is held by "main"

Java stack information for the threads listed above:
===================================================
"main": 
        at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:609)
        - waiting to lock <0x00007ff7f700ed20> (a java.lang.Object)
        at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:577)
        at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:323)
        at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:444)
        at org.opengrok.indexer.util.Statistics.report(Statistics.java:111)
        at org.opengrok.indexer.util.Statistics.report(Statistics.java:88)
        at org.opengrok.indexer.util.Executor.exec(Executor.java:235)
        at org.opengrok.indexer.util.Executor.exec(Executor.java:150)
        at org.opengrok.indexer.util.CtagsUtil.getLanguages(CtagsUtil.java:158)
        at org.opengrok.indexer.configuration.RuntimeEnvironment.validateUniversalCtags(RuntimeEnvironment.java:715)
        at org.opengrok.indexer.index.Indexer.prepareIndexer(Indexer.java:1095)
        at org.opengrok.indexer.index.Indexer.main(Indexer.java:396)
"Service Thread":
        at jdk.internal.misc.Unsafe.park(java.base@11.0.7-internal/Native Method)
        - parking to wait for  <0x00007ff78071a5b0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.7-internal/LockSupport.java:194)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.7-internal/AbstractQueuedSynchronizer.java:885)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(java.base@11.0.7-internal/AbstractQueuedSynchronizer.java:1009)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(java.base@11.0.7-internal/AbstractQueuedSynchronizer.java:1324)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(java.base@11.0.7-internal/ReentrantReadWriteLock.java:738)
        at org.opengrok.indexer.util.CloseableReentrantReadWriteLock.readLockAsResource(CloseableReentrantReadWriteLock.java:51)
        at org.opengrok.indexer.configuration.RuntimeEnvironment.syncReadConfiguration(RuntimeEnvironment.java:2149)
        at org.opengrok.indexer.configuration.RuntimeEnvironment.getStatsdConfig(RuntimeEnvironment.java:2133)
        at org.opengrok.indexer.Metrics$1.flavor(Metrics.java:64)
        at io.micrometer.statsd.StatsdMeterRegistry.lambda$lineBuilder$17(StatsdMeterRegistry.java:344)
        at io.micrometer.statsd.StatsdMeterRegistry$$Lambda$410/0x00007fff89b25cb0.apply(Unknown Source)
        at io.micrometer.statsd.StatsdMeterRegistry.lineBuilder(StatsdMeterRegistry.java:357)
        at io.micrometer.statsd.StatsdMeterRegistry.newTimer(StatsdMeterRegistry.java:396)
        at io.micrometer.core.instrument.MeterRegistry.lambda$timer$2(MeterRegistry.java:325)
        at io.micrometer.core.instrument.MeterRegistry$$Lambda$500/0x00007fff87857508.apply(Unknown Source)
        at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:625)
        - locked <0x00007ff7f700ed20> (a java.lang.Object)
        at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:577)
        at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:323)
        at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:444)
        at io.micrometer.core.instrument.binder.jvm.JvmGcMetrics$GcMetricsNotificationListener.handleNotification(JvmGcMetrics.java:211)
        at sun.management.NotificationEmitterSupport.sendNotification(java.management@11.0.7-internal/NotificationEmitterSupport.java:155)
        at com.sun.management.internal.GarbageCollectorExtImpl.createGCNotification(jdk.management@11.0.7-internal/GarbageCollectorExtImpl.java:115)

Found 1 deadlock.
```

The ctags thread wants to report metrics related to the ctags run while the GC thread wants to report GC related metrics.

**Comment by vladak** [comment]
This is because `validateUniversalCtags()` holds the configuration RW lock exclusively https://github.com/oracle/opengrok/blob/ced8af1d5d9a145836a1ea4a0a7e9cbc07efa6ab/opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java#L708-L719 which is needed by the `Metrics` for read access: https://github.com/oracle/opengrok/blob/ced8af1d5d9a145836a1ea4a0a7e9cbc07efa6ab/opengrok-indexer/src/main/java/org/opengrok/indexer/Metrics.java#L64
