### ISSUE TITLE
Create index has interrupt always when I put a large project (about 300G)

### ISSUE THREAD

**Issue by Shio583** [oracle/opengrok#4649]
**Describe the bug**
I try to use opengrok to index my Android code(Android 14)
But when I try to create index with command 
java -jar /var/opengrok-1.13.20/lib/opengrok.jar -P -S -v -s /var/opengrok-1.13.20/src -d /var/opengrok-1.13.20/data -W /var/opengrok-1.13.20/etc/configuration.xml
It will run about 3hours and broken, here was the logs

org.opengrok.indexer.index.IndexDatabase addFile
 File '/XXXXX/prebuilts/go/darwin-x86/src/debug/elf/file_test.go' interrupted--ctags timeout
org.opengrok.indexer.analysis.Ctags readTags
CTags parsing problem: 
java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:176)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:342)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:295)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:337)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:179)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at org.opengrok.indexer.analysis.Ctags.readTags(Ctags.java:590)
	at org.opengrok.indexer.analysis.Ctags.lambda$doCtags$2(Ctags.java:497)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Can I know how can I avoid this issue, or if there has something other method can continue generate index

**Comment by Shio583** [comment]
I try add java mem size but still failed
java -Xmx4g -jar /var/opengrok-1.13.20/lib/opengrok.jar -P -S -v -s /var/opengrok-1.13.20/src -d /var/opengrok-1.13.20/data -W /var/opengrok-1.13.20/etc/configuration.xml -m 512
