### ISSUE TITLE
error: `Could not initialize class org.opensolaris.opengrok.search.SearchEngine`

### ISSUE THREAD

**Issue by cnst** [oracle/opengrok#693]
I've upgraded my OpenGrok dev installation from about master around 2013-04-14 to master around 2013-11-21, re-ran the indexer, but the web-interface doesn't appear to want to work, giving out the following error.  Is this expected?

<pre>
There was an error!

Could not initialize class org.opensolaris.opengrok.search.SearchEngine

java.lang.NoClassDefFoundError: Could not initialize class org.opensolaris.opengrok.search.SearchEngine
    at org.opensolaris.opengrok.search.CustomQueryParser.<init>(CustomQueryParser.java:43)
    at org.opensolaris.opengrok.search.QueryBuilder.buildQuery(QueryBuilder.java:313)
    at org.opensolaris.opengrok.search.QueryBuilder.build(QueryBuilder.java:220)
    at org.opensolaris.opengrok.web.SearchHelper.prepareExec(SearchHelper.java:250)
    at org.apache.jsp.search_jsp._jspService(search_jsp.java:165)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1001)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
</pre>

**Comment by tulinkry** [comment]
No reaction for years. A candidate for closing.
