### ISSUE TITLE
problem with upgrade from 0.11.1 to 0.12-rc5

### ISSUE THREAD

**Issue by psumbera** [oracle/opengrok#733]
After upgrade whenever I tried to list directory content I got following error:

There was an error!

org.opensolaris.opengrok.web.DirectoryListing.listTo(Ljava/io/File;Ljava/io/Writer;Ljava/lang/String;Ljava/util/List;)Ljava/util/List;

java.lang.NoSuchMethodError: org.opensolaris.opengrok.web.DirectoryListing.listTo(Ljava/io/File;Ljava/io/Writer;Ljava/lang/String;Ljava/util/List;)Ljava/util/List;
    at org.apache.jsp.list_jsp._jspService(list_jsp.java:438)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:388)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Thread.java:744)

Finally I was able to resolve it by removing everything from tomcat work directory (plus subsequent ctrl+F5).

**Comment by tulinkry** [comment]
No reaction for years. A candidate for closing.
