### ISSUE TITLE
Genre.XREFABLE does not mean there will be a xref created

### ISSUE THREAD

**Issue by tarzanek** [oracle/opengrok#858]
Sep 10, 2014 7:49:53 PM org.opensolaris.opengrok.search.Results getTags
WARNING: An error reading tags from /opengrok-0.12/data/xref/userland-default-prepped/components/openssl/openssl-1.0.1-fips-140/openssl-1.0.1i.tar.gz.gz
java.io.FileNotFoundException: /opengrok-0.12/data/xref/userland-default-prepped/components/openssl/openssl-1.0.1-fips-140/openssl-1.0.1i.tar.gz.gz (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
- we add one more .gz - some logic is broken here

**Comment by oacnhpkqxjhufwumkkqnshvlmheokqv** [comment]
I've see the same noise in my logs too.

**Comment by vladak** [comment]
> I see the same noise in my logs too.

This is old bug. What version are you running ?

**Comment by vladak** [comment]
Actually, I can reproduce this on 1.5.8 (full text search for a compressed tarball, e.g. https://foo/source/search?project=userland-default-prepped&full=openssl&defs=&refs=&path=tar&hist=&type=&xrd=&nn=1&si=path&si=path):
```
19-Nov-2020 09:45:38.088 WARNING [http-nio-8080-exec-50] org.opengrok.indexer.search.Results.getTags An error reading tags from /opengrok/data/xref/userland-default-prepped/components/libssh2/libssh2-1.9.0.tar.g
z.gz
        java.io.FileNotFoundException: /opengrok/data/xref/userland-default-prepped/components/libssh2/libssh2-1.9.0.tar.gz.gz (No such file or directory)
                at java.base/java.io.FileInputStream.open0(Native Method)
                at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
                at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
                at org.opengrok.indexer.search.Results.getXrefReader(Results.java:137)
                at org.opengrok.indexer.search.Results.getTags(Results.java:115)
                at org.opengrok.indexer.search.Results.prettyPrint(Results.java:233)
                at org.apache.jsp.search_jsp._jspService(search_jsp.java:904)
                at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
                at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
                at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
                at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.filters.RequestDumperFilter.doFilter(RequestDumperFilter.java:202)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.opengrok.web.CookieFilter.doFilter(CookieFilter.java:49)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:92)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:71)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by vladak** [comment]
I think the double `.gz` suffix is just a red herring. The file in question is a compressed tarball and the code in `Result` is looking for related xref file. These files are not generally xref-able. If the file was, there would be indeed a file called `foo.tar.gz.gz` under the `xref` directory.

The problem here is that the genre is detected as xref-able:
https://github.com/oracle/opengrok/blob/186da878ab38f1ad46f9cdc2b9a785f3cb979856/opengrok-indexer/src/main/java/org/opengrok/indexer/search/Results.java#L230-L243

The handling of such file should not take any of these if branches.

**Comment by vladak** [comment]
I think the problem may be that the GZIPAnalyzer (which is usually the analyzer for the `.tar.gz` files - as verified in the indexer logs for the `libssh2-1.9.0.tar.gz` mentioned above) stores the genre of the document as `XREFABLE` (because the uncompressed data was detected as xref-able or plain text) however there is no xref actually created.

https://github.com/oracle/opengrok/blob/186da878ab38f1ad46f9cdc2b9a785f3cb979856/opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/archive/GZIPAnalyzer.java#L105-L118

This is also the case for BZip2Analyzer.

**Comment by vladak** [comment]
Also, it seems that `Results#getTags()` / `Results#getXrefReader()` do not take the economy mode into account. The latter tries to access the file directly.

**Comment by vladak** [comment]
The reason there is no xref written for these files is that `IndexDatabase#newXrefWriter()` returns `null`. This then bubbles across `populateDocument()` to `TarAnalyzer#analyze()`. This is because `isXrefWriter()` returns false for `GZIPAnalyzer` because its native genre is `DATA`.

**Comment by vladak** [comment]
It seems to me that the original intent was to create xrefs even for compressed files. If that's the case, the `IndexDatabase#isXrefWriter()` is called prematurely or rather it poses a bit of a chicken-egg problem because before the analyzers are actually run (given the dynamic nature of the genre) it is not clear whether to create xref or not.

**Comment by vladak** [comment]
Removing the call to `isXrefWriter()` from `newXrefWriter()` leads to the `.gz.gz` files to be actually produced in the `xref` directory. The UI no longer says 'Failed to get xref' error message for these files and displays the contents of the xrefs (listing of archive entries in case of tarballs).

The only other place where `isXrefWriter()` is used is `IndexDatabase#checkSettings()`.
