### ISSUE TITLE
Failure to write history cache - NULL File ptr when indexing Perforce repo

### ISSUE THREAD

**Issue by JVizzoni** [oracle/opengrok#878]
When generating the history cache FileHistoryCache fails to write to file due to a NULL ptr.

`2015-01-16 16:42:10.869-0800 FINE t22 Executor.exec: Finished command [p4, changes, -t, ...] in directory /local2/mnt/workspace/sandbox/src`

`2015-01-16 16:42:10.912-0800 FINE t22 FileHistoryCache.store: Storing history for repo /local2/mnt/workspace/sandbox/src`

`2015-01-16 16:42:10.913-0800 WARNING t22 FileHistoryCache.storeLatestCachedRevision: cannot write latest cached revision to file: null`

`2015-01-16 16:42:10.914-0800 WARNING t22 HistoryGuru.createCache: An error occured while creating cache for /local2/mnt/workspace/sandbox/src (PerforceRepository)
java.lang.NullPointerException
    at org.opensolaris.opengrok.history.FileHistoryCache.storeLatestCachedRevision(FileHistoryCache.java:595)
    at org.opensolaris.opengrok.history.FileHistoryCache.finishStore(FileHistoryCache.java:306)
    at org.opensolaris.opengrok.history.FileHistoryCache.store(FileHistoryCache.java:403)
    at org.opensolaris.opengrok.history.Repository.createCache(Repository.java:328)
    at org.opensolaris.opengrok.history.HistoryGuru.createCache(HistoryGuru.java:495)
    at org.opensolaris.opengrok.history.HistoryGuru.ensureHistoryCacheExists(HistoryGuru.java:692)
    at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:349)
    at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:168)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source
`

I've confirmed that the user has read/write permissions to the OPENGROK_INSTANCE_BASE where the cache is stored. Also, the cmd `p4 changes -t ...` returns a valid value when executed manually in the root of the src directory.

Any ideas to what may be going on? If any further information is required please reply and I'll be happy to post. Thanks!

Indexing cmd:
OPENGROK_TAG=1 OPENGROK_VERBOSE=1 OPENGROK_TOMCAT_CASE=/usr/share/tomcat7 OPENGROK_INSTANCE_BASE=/local2/mnt/workspace/opengrok ./OpenGrok index /local2/mnt/workspace/sandbox/src/

**Comment by vladak** [comment]
What OpenGrok version are you running exactly ? Was this initial index of the P4 repo ?

**Comment by vladak** [comment]
This is surely related to isseu #729 and the changes for cset cd3a12bbb218269c922cf4f35ebcdeea606e586f and possibly related follow-up changes.

**Comment by vladak** [comment]
I think you may be missing the fix of 0dbb0e366b3798ac18d1bfc010a1985bce75f071

**Comment by vladak** [comment]
I guess we should be testing with Perforce more, i.e. there is no test repo under https://github.com/OpenGrok/OpenGrok/tree/master/testdata/repositories

**Comment by JVizzoni** [comment]
Hi Vladimir, sorry for the late reply. Was away this weekend after opening the ticket.

I'm using OpenGrok version 12.1.1 - I checked the source for this version and it appears the fix 0dbb0e3 is not present. This is the latest binary distribution that I could find. I'll try compiling the latest stable release (12.1.3) to see if this fixes the issue and leave a comment after testing...

**Comment by vladak** [comment]
Maybe we should've done a respin of 0.12 with the fix.

I've just cherry picked the changeset into the stable branch. In couple of days I will release another version of the stable branch.

**Comment by vladak** [comment]
It would be nice if you could trace storeLatestCachedRevision() / getRepositoryCachedRevPath() so that it can be seen what went wrong. Also, could you look into the indexer logs and see if there is some warning ?

**Comment by JVizzoni** [comment]
What is your recommended way for tracing storeLatestCachedRevision() / getRepositoryCachedRevPath() ? I have to admit I'm not familiar with Java but probably could add some debug messages or step through the code...

**Comment by JVizzoni** [comment]
from logs/opengrok0.0.log I do not see any serious warnings/errors besides the previously mentioned error. From the log we have:

```
2015-01-19 19:00:03.655-0800 FINE t1 Executor.registerErrorHandler: Installing default uncaught exception handler
2015-01-19 19:00:03.778-0800 FINE t1 Executor.exec: Executing command [/usr/bin/ctags-exuberant, --version] in directory /usr2/avssvc/opengrok-0.12.1.1/bin
2015-01-19 19:00:03.785-0800 FINE t1 Executor.exec: Finished command [/usr/bin/ctags-exuberant, --version] in directory /usr2/avssvc/opengrok-0.12.1.1/bin
2015-01-19 19:00:03.785-0800 INFO t1 Indexer.prepareIndexer: Scanning for repositories...
2015-01-19 19:00:03.786-0800 FINE t1 Executor.exec: Executing command [accurev, info] in directory /usr2/avssvc/opengrok-0.12.1.1/bin
2015-01-19 19:00:03.786-0800 FINE t1 Executor.exec: Executing command [cleartool, -version] in directory /usr2/avssvc/opengrok-0.12.1.1/bin
2015-01-19 19:00:03.787-0800 FINE t1 Executor.exec: Executing command [/pkg/qct/software/p4/p4, help] in directory /usr2/avssvc/opengrok-0.12.1.1/bin
2015-01-19 19:00:03.815-0800 FINE t1 Executor.exec: Finished command [/pkg/qct/software/p4/p4, help] in directory /usr2/avssvc/opengrok-0.12.1.1/bin
2015-01-19 19:00:03.816-0800 FINE t1 Executor.exec: Executing command [/pkg/qct/software/p4/p4, dirs, *] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:03.852-0800 FINE t1 Executor.exec: Finished command [/pkg/qct/software/p4/p4, dirs, *] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:03.853-0800 FINE t1 Executor.exec: Executing command [/pkg/qct/software/p4/p4, help] in directory /usr2/avssvc/opengrok-0.12.1.1/bin
2015-01-19 19:00:03.863-0800 FINE t1 Executor.exec: Finished command [/pkg/qct/software/p4/p4, help] in directory /usr2/avssvc/opengrok-0.12.1.1/bin
2015-01-19 19:00:03.863-0800 CONFIG t1 HistoryGuru.addRepositories: Adding <org.opensolaris.opengrok.history.PerforceRepository> repository: </local2/mnt/workspace/opengrok/src>
2015-01-19 19:00:03.864-0800 FINE t1 Executor.exec: Executing command [/pkg/qct/software/p4/p4, dirs, *] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:03.914-0800 FINE t1 Executor.exec: Finished command [/pkg/qct/software/p4/p4, dirs, *] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:03.915-0800 FINE t1 Executor.exec: Executing command [/pkg/qct/software/p4/p4, help] in directory /usr2/avssvc/opengrok-0.12.1.1/bin
2015-01-19 19:00:03.926-0800 FINE t1 Executor.exec: Finished command [/pkg/qct/software/p4/p4, help] in directory /usr2/avssvc/opengrok-0.12.1.1/bin
2015-01-19 19:00:03.928-0800 INFO t1 Indexer.prepareIndexer: Done scanning for repositories (0s)
2015-01-19 19:00:03.931-0800 INFO t1 Indexer.prepareIndexer: Writing configuration to /local2/mnt/workspace/opengrok/etc/configuration.xml
2015-01-19 19:00:04.068-0800 INFO t1 Indexer.prepareIndexer: Done...
2015-01-19 19:00:04.068-0800 INFO t1 Indexer.prepareIndexer: Generating history cache for all repositories ...
2015-01-19 19:00:04.069-0800 INFO t1 HistoryGuru.createCacheReal: Creating historycache for 1 repositories
2015-01-19 19:00:04.071-0800 INFO t22 HistoryGuru.createCache: Creating historycache for /local2/mnt/workspace/opengrok/src (PerforceRepository)
2015-01-19 19:00:04.071-0800 WARNING t22 Repository.getHistory: Incremental history retrieval is not implemented for PerforceRepository.
2015-01-19 19:00:04.072-0800 WARNING t22 Repository.getHistory: Falling back to slower full history retrieval.
2015-01-19 19:00:04.073-0800 FINE t22 Executor.exec: Executing command [/pkg/qct/software/p4/p4, dirs, *] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:04.109-0800 FINE t22 Executor.exec: Finished command [/pkg/qct/software/p4/p4, dirs, *] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:04.110-0800 FINE t22 Executor.exec: Executing command [p4, changes, -t, ...] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:10.535-0800 FINE t22 Executor.exec: Finished command [p4, changes, -t, ...] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:10.647-0800 FINE t22 FileHistoryCache.store: Storing history for repo /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:10.648-0800 FINE t22 FileHistoryCache.finishStore: Done storing history for repo /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:10.650-0800 INFO t22 Statistics.report: Done historycache for /local2/mnt/workspace/opengrok/src (took 6.577 seconds)
2015-01-19 19:00:10.651-0800 INFO t1 Statistics.report: Done historycache for all repositories (took 6.583 seconds)
2015-01-19 19:00:10.651-0800 INFO t1 Indexer.prepareIndexer: Done...
2015-01-19 19:00:10.652-0800 INFO t1 Indexer.doIndexerExecution: Starting indexing
2015-01-19 19:00:10.868-0800 INFO t31 HistoryGuru.createCache: Creating historycache for /local2/mnt/workspace/opengrok/src (PerforceRepository)
2015-01-19 19:00:10.868-0800 INFO t29 HistoryGuru.createCache: Creating historycache for /local2/mnt/workspace/opengrok/src (PerforceRepository)
2015-01-19 19:00:10.868-0800 INFO t28 HistoryGuru.createCache: Creating historycache for /local2/mnt/workspace/opengrok/src (PerforceRepository)
2015-01-19 19:00:10.868-0800 INFO t27 HistoryGuru.createCache: Creating historycache for /local2/mnt/workspace/opengrok/src (PerforceRepository)
2015-01-19 19:00:10.868-0800 INFO t30 HistoryGuru.createCache: Creating historycache for /local2/mnt/workspace/opengrok/src (PerforceRepository)
2015-01-19 19:00:10.869-0800 WARNING t27 Repository.getHistory: Incremental history retrieval is not implemented for PerforceRepository.
2015-01-19 19:00:10.869-0800 WARNING t28 Repository.getHistory: Incremental history retrieval is not implemented for PerforceRepository.
2015-01-19 19:00:10.869-0800 WARNING t29 Repository.getHistory: Incremental history retrieval is not implemented for PerforceRepository.
2015-01-19 19:00:10.868-0800 WARNING t31 Repository.getHistory: Incremental history retrieval is not implemented for PerforceRepository.
2015-01-19 19:00:10.869-0800 WARNING t29 Repository.getHistory: Falling back to slower full history retrieval.
2015-01-19 19:00:10.869-0800 WARNING t28 Repository.getHistory: Falling back to slower full history retrieval.
2015-01-19 19:00:10.869-0800 WARNING t27 Repository.getHistory: Falling back to slower full history retrieval.
2015-01-19 19:00:10.869-0800 WARNING t30 Repository.getHistory: Incremental history retrieval is not implemented for PerforceRepository.
2015-01-19 19:00:10.870-0800 FINE t28 Executor.exec: Executing command [/pkg/qct/software/p4/p4, dirs, *] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:10.870-0800 FINE t29 Executor.exec: Executing command [/pkg/qct/software/p4/p4, dirs, *] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:10.870-0800 WARNING t31 Repository.getHistory: Falling back to slower full history retrieval.
2015-01-19 19:00:10.870-0800 WARNING t30 Repository.getHistory: Falling back to slower full history retrieval.
2015-01-19 19:00:10.870-0800 FINE t27 Executor.exec: Executing command [/pkg/qct/software/p4/p4, dirs, *] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:10.871-0800 FINE t31 Executor.exec: Executing command [/pkg/qct/software/p4/p4, dirs, *] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:10.871-0800 FINE t30 Executor.exec: Executing command [/pkg/qct/software/p4/p4, dirs, *] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:11.009-0800 FINE t31 Executor.exec: Finished command [/pkg/qct/software/p4/p4, dirs, *] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:11.009-0800 FINE t27 Executor.exec: Finished command [/pkg/qct/software/p4/p4, dirs, *] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:11.010-0800 FINE t31 Executor.exec: Executing command [p4, changes, -t, ...] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:11.011-0800 FINE t27 Executor.exec: Executing command [p4, changes, -t, ...] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:11.012-0800 FINE t29 Executor.exec: Finished command [/pkg/qct/software/p4/p4, dirs, *] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:11.013-0800 FINE t29 Executor.exec: Executing command [p4, changes, -t, ...] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:11.014-0800 FINE t28 Executor.exec: Finished command [/pkg/qct/software/p4/p4, dirs, *] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:11.015-0800 FINE t28 Executor.exec: Executing command [p4, changes, -t, ...] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:11.016-0800 FINE t30 Executor.exec: Finished command [/pkg/qct/software/p4/p4, dirs, *] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:11.017-0800 FINE t30 Executor.exec: Executing command [p4, changes, -t, ...] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:17.572-0800 FINE t27 Executor.exec: Finished command [p4, changes, -t, ...] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:17.579-0800 FINE t29 Executor.exec: Finished command [p4, changes, -t, ...] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:17.584-0800 FINE t30 Executor.exec: Finished command [p4, changes, -t, ...] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:17.636-0800 FINE t31 Executor.exec: Finished command [p4, changes, -t, ...] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:17.642-0800 FINE t28 Executor.exec: Finished command [p4, changes, -t, ...] in directory /local2/mnt/workspace/opengrok/src
2015-01-19 19:00:17.664-0800 INFO t27 Statistics.report: Done historycache for /local2/mnt/workspace/opengrok/src (took 6.796 seconds)
2015-01-19 19:00:17.664-0800 INFO t29 Statistics.report: Done historycache for /local2/mnt/workspace/opengrok/src (took 6.796 seconds)
2015-01-19 19:00:17.669-0800 INFO t30 Statistics.report: Done historycache for /local2/mnt/workspace/opengrok/src (took 6.801 seconds)
2015-01-19 19:00:17.684-0800 INFO t31 Statistics.report: Done historycache for /local2/mnt/workspace/opengrok/src (took 6.816 seconds)
2015-01-19 19:00:17.692-0800 INFO t28 Statistics.report: Done historycache for /local2/mnt/workspace/opengrok/src (took 6.824 seconds
```

**Comment by JVizzoni** [comment]
I built the tip and see that the crash with the NULL ptr is avoided, however, the history cache is not generated with valid links (attempting to access the history via the GUI gives 404 error file not found).

```
2015-01-20 15:52:32.282-0800 FINE t25 Executor.exec: Finished command [p4, changes, -t, ...] in directory /local2/mnt/workspace/opengrok/src
2015-01-20 15:52:32.393-0800 FINE t23 FileHistoryCache.store: Storing history for repo /local2/mnt/workspace/opengrok/src
2015-01-20 15:52:32.396-0800 WARNING t23 FileHistoryCache.storeLatestCachedRevision: cannot write latest cached revision to file: null
2015-01-20 15:52:32.396-0800 FINE t23 FileHistoryCache.finishStore: Done storing history for repo /local2/mnt/workspace/opengrok/src
2015-01-20 15:52:32.398-0800 INFO t23 Statistics.report: Done historycache for /local2/mnt/workspace/opengrok/src (took 6.798 seconds)
2015-01-20 15:52:32.410-0800 INFO t23 DefaultIndexChangedListener.fileAdd: Add: /AVS.ADSP.2.6/AVS.ADSP.2.5.plf (PlainAnalyzer)
2015-01-20 15:52:32.414-0800 FINE t23 Executor.exec: Executing command [/pkg/qct/software/p4/p4, files, AVS.ADSP.2.5.plf] in directory /local2/mnt/workspace/opengrok/src/AVS.ADSP.2.6
2015-01-20 15:52:32.428-0800 FINE t26 FileHistoryCache.store: Storing history for repo /local2/mnt/workspace/opengrok/src
2015-01-20 15:52:32.428-0800 FINE t25 FileHistoryCache.store: Storing history for repo /local2/mnt/workspace/opengrok/src
2015-01-20 15:52:32.429-0800 FINE t22 FileHistoryCache.store: Storing history for repo /local2/mnt/workspace/opengrok/src
2015-01-20 15:52:32.432-0800 WARNING t26 FileHistoryCache.storeLatestCachedRevision: cannot write latest cached revision to file: null
2015-01-20 15:52:32.432-0800 WARNING t25 FileHistoryCache.storeLatestCachedRevision: cannot write latest cached revision to file: null
2015-01-20 15:52:32.432-0800 FINE t26 FileHistoryCache.finishStore: Done storing history for repo /local2/mnt/workspace/opengrok/src
2015-01-20 15:52:32.432-0800 FINE t25 FileHistoryCache.finishStore: Done storing history for repo /local2/mnt/workspace/opengrok/src
2015-01-20 15:52:32.433-0800 WARNING t22 FileHistoryCache.storeLatestCachedRevision: cannot write latest cached revision to file: null
2015-01-20 15:52:32.433-0800 INFO t25 Statistics.report: Done historycache for /local2/mnt/workspace/opengrok/src (took 6.812 seconds)
2015-01-20 15:52:32.433-0800 INFO t26 Statistics.report: Done historycache for /local2/mnt/workspace/opengrok/src (took 6.811 seconds)
2015-01-20 15:52:32.433-0800 FINE t22 FileHistoryCache.finishStore: Done storing history for repo /local2/mnt/workspace/opengrok/src
2015-01-20 15:52:32.433-0800 INFO t22 Statistics.report: Done historycache for /local2/mnt/workspace/opengrok/src (took 6.795 seconds
```

**Comment by vladak** [comment]
First thing is to check whether the history was indeed generated. Assuming you're using file based history cache, take a look in the `history` directory under the `data` directory to see if there are any files there. Normally, each project has a directory structure which matches the one of the source tree. In the directory structure there are gzip'ed XML files (they can be displayed with `gzcat` command or the like).

For Perforce the incremental history index has not been implemented yet, hence the warnings. It might be that something got broken with that change.

**Comment by vladak** [comment]
As for the debugging, there is some description of the setup on https://github.com/OpenGrok/OpenGrok/wiki/Developer-intro. Once the project in Netbeans is setup it is very easy to insert breakpoints, observe values of variables etc.

**Comment by JVizzoni** [comment]
Yes, I do see that the gz files are there and match the source tree exactly. I'm wondering why the web interface is not finding them...

Thank you for the link. I'll take a look to why the `writer` is NULL to begin with. That may offer some insights (hopefully, it's just a configuration issue on my part).

**Comment by inqueue** [comment]
JVizzoni, have you had any luck with this? I am having the same issue with a Perforce repo. and would like to know why the web interface does not find the generated history cache.

**Comment by JVizzoni** [comment]
@inqueue I'm still debugging this issue. (actually working on it as we speak). I have the same exact symptom where the the web interface does not find the generated history cache. I confirmed that the .gz files are in data/historycache.

If I make any headway I'll post what I've found. Please do the same.

**Comment by quickwind** [comment]
I have exactly the same issue in my env with 0.12.1.2, @JVizzoni, how did you get around with the null PTR exception? I am stuck with that and has no history file generated at all...Hope this issue would be fixed very soon...

**Comment by JVizzoni** [comment]
@quickwind I have not found a solution to the issue yet. I'll post the solution once found.

**Comment by JVizzoni** [comment]
@quickwind and @inqueue it appears that there are two separate issues here. This ticket originally was opened due to the NULL ptr exception. This is resolved per vladak's comments (update to the latest version of OpenGrok which has the NULL ptr check). You'll notice that on the second index the history cache is generated and written to a file called OpenGrokLatestRev located in /data/historycache/<project_name>

The issue with the history/annotate links greyed out in the web UI is separate. I believe it is a configuration issue with OpenGrok/Tomcat (or your web server). I'm going to close this ticket since the original issue is resolved.

**Comment by littlechu** [comment]
I run into this issue if I I use symlink in /var/opengrok/src to references to the git checkout (this seem to be the recommend configure from multiple online ho to)

As soon as I move the source into /var/opengrok/src instead of using symbolic link, the issue gone.

Also, I notice with symbolic link in /var/opengrok/src, the xref to the file will be incorrect in history modified view.

**Comment by tarzanek** [comment]
don't use symlink
actually NEVER use symlink to src

properly use the src root param to opengrok script ...

**Comment by littlechu** [comment]
I am just pointing out the symbol link in src may have something to do with the NULL Write error. I suspect some people who report this issue is doing that.

Also, if you google "setup opengrok ubuntu" The first few how to all use symbol link.

**Comment by tarzanek** [comment]
they are all wrong

**Comment by uvwild** [comment]
Hello  tarzanek 

"don't use symlink
actually NEVER use symlink to src
properly use the src root param to opengrok script ...
"

I am doing exactly that on a linuxmint/debian system indexing folder of git repos 
which seems too work so far ....

But I had a larger setup indexing more repositories where I had the NULL write error which I however contributed to encoding issues.... The reduced code base now works fine.

Would you mind to elaborate on the possible issues?
Thanks

**Comment by tarzanek** [comment]
@uvwild there is some code that filters out symlinks not local to source root
afaik no one improved it to be smart enough to support use case of symlinking out the whole src_root
so I fear some stuff will just not work, because of this filtering ...
I'd actually would be happy if we could support symlinks, but because of loops we're not able to, try to find that code, review it, improve it ... people will be only happy!

**Comment by robp85** [comment]
Any word on this? I show the historycache is being generated and I've even looked at the gzipped files to confirm the history is there. The web site can't seem to show the files, though. I really need some direction on how to fix this issue. Thank you.

**Comment by JVizzoni** [comment]
@robp85 I had the same problem and found that it was an issue with tomcat user permissions and not opengrok. As part of the automation I had one user syncing and triggering the opengrok index; the other user had rwx permissions on my tomcat installation. After performing a chmod on the tomcat installation to change ownership to the user indexing/syncing code I could view the history.

**Comment by JVizzoni** [comment]
@vladak I think we can close this issue or at least mark it as a duplicate.

@inqueue please see the above comment - I suspect that you are having the same permissions issue if the history cache is generated but not viewable in the browser.

**Comment by robp85** [comment]
@JVizzoni Thanks for the suggestion! Unfortunately, the owner of tomcat installation/process is the same account running the sync and indexing jobs and owns the folders for the index files and the files from the different repos being synced from Git and Perforce. Everything is running under the same user. Did you find you needed specific permissions on those files?

**Comment by JVizzoni** [comment]
@robp85 just checked my setup and the same account has rwx permissions on the tomcat installation, opengrok installation and opengrok source dir (containing data, etc, source code, etc). It also is the same user that spawned the tomcat daemon.

The fact that you can see the gzip files with the history information is suspicious. I'd double check your permissions and restart the server. Only other thing I can suggest is to relaunch the daemon without root privileges 

`ps -ef |grep tomcat`

is showing two jsvc processes under the same user.

**Comment by jamesweb1** [comment]
I see the tutorial online and using the symbolic link to src, and I get the issue in this thread. After removing all symbolic link, all the warrning  is gone. :D
