### ISSUE TITLE
Perforce history cache not being written

### ISSUE THREAD

**Issue by robp85** [oracle/opengrok#981]
I have an environment that has both Git and Perforce repositories being sync'd and index'd. The history cache for the Git repo is working fine but none of the Perforce repos are not writing the history cache. Is there something that I'm missing from the default configuration to cause that to happen?

Some information on my system: CentOS 6.5, Tomcat 7, OpenGrok 0.12.1

There really isn't any special configurations made. The install is pretty vanilla. I'm confused as to why history cache isn't being written.

Thank you.

**Comment by vladak** [comment]
Anything interesting in the indexer logs ? (e.g. exceptions)

**Comment by robp85** [comment]
The only exceptions I see in the index logs are from files that end in .class that aren't Java files (there are only a few of those) and there are a few git repos that were added that have nothing in them yet. No errors in regards to historycache in there.

**Comment by robp85** [comment]
I'm sorry. I've done some changes (updated to 0.12.1.5, checked my .p4config files, etc) and now I'm seeing some errors specific to history cache and Perforce. Below is an example of the error. In addition, I'm seeing this final error after all is said and done:

09:14:56 WARNING: An error occured while creating cache for /data/src/main (PerforceRepository)
java.lang.NullPointerException
	at org.opensolaris.opengrok.history.FileHistoryCache.storeLatestCachedRevision(FileHistoryCache.java:595)
	at org.opensolaris.opengrok.history.FileHistoryCache.finishStore(FileHistoryCache.java:306)
	at org.opensolaris.opengrok.history.FileHistoryCache.store(FileHistoryCache.java:403)
	at org.opensolaris.opengrok.history.Repository.createCache(Repository.java:327)
	at org.opensolaris.opengrok.history.HistoryGuru.createCache(HistoryGuru.java:495)
	at org.opensolaris.opengrok.history.HistoryGuru.ensureHistoryCacheExists(HistoryGuru.java:692)
	at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:349)
	at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:168)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
09:14:56 SEVERE: Problem updating lucene index database: 

java.io.EOFException: read past EOF: MMapIndexInput(path="/data/index/data/index/main/_de.cfs") [slice=_de_Lucene41_0.tip]
	at org.apache.lucene.store.ByteBufferIndexInput.readByte(ByteBufferIndexInput.java:78)
	at org.apache.lucene.store.DataInput.readInt(DataInput.java:84)
	at org.apache.lucene.store.ByteBufferIndexInput.readInt(ByteBufferIndexInput.java:129)
	at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:126)
	at org.apache.lucene.codecs.BlockTreeTermsReader.readIndexHeader(BlockTreeTermsReader.java:207)
	at org.apache.lucene.codecs.BlockTreeTermsReader.<init>(BlockTreeTermsReader.java:132)
	at org.apache.lucene.codecs.lucene41.Lucene41PostingsFormat.fieldsProducer(Lucene41PostingsFormat.java:437)
	at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsReader.<init>(PerFieldPostingsFormat.java:195)
	at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat.fieldsProducer(PerFieldPostingsFormat.java:244)
	at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:116)
	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:96)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:62)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:843)
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:52)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:66)
	at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:352)
	at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:168)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by robp85** [comment]
OK, I figured out how to get the history cache to generate. I can view the cache contents on the file system without a problem. However, I'm still getting "Error: File Note Found" when I attempt to access the history from the web site. Any suggestions on what might be going on?

**Comment by ymnick** [comment]
Have the same problem discussed here with no resolution https://github.com/OpenGrok/OpenGrok/issues/926
